### ISSUE TITLE
@value & cssnano

### ISSUE THREAD

**Issue by neverfox** [css-modules/css-modules#104]
It seems that including cssnano in the list of postcss plugins (which I imagine is a pretty common plugin) kills the functionality of `@value`, at least with the default settings. Anyone know how to get these two to play nicely?

**Comment by sinkpoint** [comment]
@neverfox, I managed to get this working. 

For me, the problem is that cssnano normalizes the paths from related ('./mypath/file') to ('mypath/file'), and css-modules will interpret the as module path, and throw cannot resolve module errors. 

The solution is to pass: 
```javascript
    postcss: function () {
        return {
            defaults: [  
                postcssImport({
                    addDependencyTo: webpack
                }),
                autoprefixer,
                precss,
                cssnano(
                {
                    'postcss-normalize-url':false,
                    'autoprefixer':false,
                }
                ),
            ]
        };
    }    
```
See [cssnano docs](http://cssnano.co/optimisations/) for any additional options you might want to disable.

**Comment by neverfox** [comment]
Great! I'll try this out.

**Comment by neverfox** [comment]
BTW, unrelated question, but is there a reason you run autoprefixer independently rather than using it as part of cssnano? Isn't it the same?

**Comment by sinkpoint** [comment]
It's because cssnano's autoprefixer option is to **remove** unnecessary prefixes, 
while I actually want to keep all the prefixes added by postcss-autoprefixer for now. 

It's not really related to this question though, you can ignore it.

**Comment by neverfox** [comment]
@sinkpoint Oh, I thought the autoprefixer option on cssnano was just passing things along to an included copy of autoprefixer, and takes the same options object. so that you could just remove the other autoprefixer and do:

```
cssnano({
  autoprefixer : {
    remove : false
  }
})
```

Also, I believe the default for autoprefixer is `remove: true` so are you sure that's giving you what you want?
