### ISSUE TITLE
sharing variables between css and js

### ISSUE THREAD

**Issue by Bloomca** [css-modules/css-modules#106]
Hi there!

There are plenty of issues about importing, but almost all of them somehow refer to JSS, which I ain't fond of.

So, the question is simple – can I share variables between js and css, writing css in usual way?

Thanks.

**Comment by CubedEye** [comment]
You sure can! Just export the variables from the css and use them in your JS (have only tested this with the webpack css-loader) - I believe this is what you're after?

```css
.root {
    /* ... some CSS ... */
}

:export {
    numberOfThings: 15;
    defaultBackground: #FFCC00;
}
```

```javascript
    var styles = require("myStyles.css-modules");
    var numberOfThings = parseInt(styles.numberOfThings);
    var defaultBGColor = styles.defaultBackground;
```

**Comment by axelson** [comment]
Related issue: https://github.com/css-modules/css-modules/issues/86

**Comment by joshwnj** [comment]
Anything defined as a `@value` will be exported by the css module, and can be used in js. `@value` docs here: https://github.com/css-modules/postcss-modules-values

Eg.

```
/* styles.css */

@value faveColor: #F0F;

.box {
  border: 1px solid faveColor;
}
```

```
/* index.js */

var styles = require('./styles.css')
console.log('My favourite color of all time is', styles.faveColor)
```

**Comment by pnkapadia6** [comment]
Is it possible to pass a variable from js to the css module?
@CubedEye @joshwnj

**Comment by joshwnj** [comment]
@pnkapadia6 you can pass values from js to css with a postcss plugin like https://github.com/macropodhq/postcss-constants or https://github.com/MadLittleMods/postcss-css-variables

**Comment by pnkapadia6** [comment]
Using `postcss-css-variables`. Thanks, @joshwnj!

**Comment by nostophilia** [comment]
Also you can use`postcss-cssnext`. It utilizes `postcss-custom-properties`under the hood. `postcss-custom-properties` is similar to`postcss-css-variables` but with [some differences](https://github.com/MadLittleMods/postcss-css-variables#differences-from-postcss-custom-properties). After you set it up, you can do something like this:
```js
// variables/index.js
module.exports = {
  navWidth: "48px"
}
```
```js
// postcss.config.js
module.exports = {
  plugins: [
    require("postcss-cssnext")({
      features: {
        customProperties: {
          variables: require("variables/index.js")
        }
      }
    })
  ]
}
```
```css
/* style.css */
.sidebar {
  width: var(--navWidth);
}
```
BTW, I've spent much time researching and installing separate `postcss` plugins in order to do things like sharing variables, writing global classes, nesting, calculating......In the end I found all I need is to set up and configure `cssnext` and it can solve more problems than this. You should give it a try.

**Comment by pietrofxq** [comment]
@stanleysq this is working great, except that webpack doesn't trigger a compile when this file changes. I've set webpack to watch my /src folder, and my variables.js file is inside this folder, but adding variables doesn't make webpack compile again (thus throwing a compile error when I use a new variable). Do you know how to fix this? My webpack first compile takes around 3 minutes, so I'd like to avoid having to restart webpack every time I add a new variable.

**Comment by stanleysq** [comment]
@pietrofxq Unfortunately, I can't get it working either and I don't see clearly a solution. The best I can get is this:

change your `customProperties` setting in your `postcss.config.js`
```js
customProperties: {
  variables: (function() {
    const variableFile = require.resolve("variables.js")
    delete require.cache[variableFile]
    return require(variableFile)
  })()
}
```
(remember to use `require.resolve` the cache can be deleted with an absolute cache)

Now you need to go to the css file which contains the variables to trigger a manual save. Then styles will be reloaded. You see, the main obstacle here is that our `variables.js` isn't actually required in our css files (it is required by postcss). So the css files reloading isn't triggered. If you find a way to force reloading relevant or even better, all css files, then you will be able to get it working.

**Comment by stanleysq** [comment]
@pietrofxq Sorry, I'm afraid you're supposed to ask this type of questions on Stackover Flow instead with code snippets to explain what you want to achieve precisely.

**Comment by Andsbf** [comment]
I'm using cssModules with `react-scripts 3.0.1`. Would anyone have any idea why this would not work: 

```
/* styles.css */

@value faveColor: #F0F;

.box {
  border: 1px solid faveColor;
}
```
/* index.js */

var styles = require('./styles.css')
console.log('My favourite color of all time is', styles.faveColor)
```

**Comment by jmagrippis** [comment]
@Andsbf 
`style,css` should be `styles.module.css`.

In order to actually use css modules with Create React App / `react-scripts`, you must have that suffix.

https://facebook.github.io/create-react-app/docs/adding-a-css-modules-stylesheet

**Comment by eggei** [comment]
I wanted to share an underrated library I have started to use for this purpose recently. In my opinion, it saves you from all the suffer of the solutions above. After reading this convo here, there is no better solution than this: https://www.npmjs.com/package/css-global-variables

It is as easy as 
```javascript
//set
CssGlobalVars.myVar = '#ffefef'
//get
CssGlobalVars.myVar
```

```css
background: var(—myVar)
```

Give it a try, you will like it.

**Comment by sultan99** [comment]
I have created an extension for ❤CSS-Module, which solves some issues with variables and typing:
https://bit.ly/2OqcxzQ

Any feedback or wishes are welcomed!
