### ISSUE TITLE
Issue with the hover

### ISSUE THREAD

**Issue by jacko99** [css-modules/css-modules#107]
Hi all,

I have an issue. When I move my mouse over the graph, I have 3 figures instead of one. I didn't change anything. Can someone help me?

Example : http://preprod.conseilsparissportifs.fr/bilan-pronostics/

**Comment by nkbt** [comment]
It does seem not related to css-modules at all =)

Though, look at this function (unminified) from Chart.js (for Line chart)
```
    getPointsAtEvent: function(t) {
      var i = []
        , s = e.getRelativePosition(t);
      return e.each(this.datasets, function(t) {
        e.each(t.points, function(t) {
          t.inRange(s.x, s.y) && i.push(t)
        })
      }, this),
      i
    },
```
It returns multiple points (in vicinity), so after that it `this.showTooltip(i)` for each of the point.

And close the issue please ;). I reckon it is better to use StackOverflow for such things

**Comment by jacko99** [comment]
Thanks mate for your answer and sorry for the wrong forum.

However, my function is like that in chart.js. What should I do (I'm a noob my I try to learn)? Replace that by your function?

getPointsAtEvent : function(evt){
			var mousePosition = helpers.getRelativePosition(evt),
				fromCenter = helpers.getAngleFromPoint({
					x: this.scale.xCenter,
					y: this.scale.yCenter
				}, mousePosition);

			var anglePerIndex = (Math.PI * 2) /this.scale.valuesCount,
				pointIndex = Math.round((fromCenter.angle - Math.PI * 1.5) / anglePerIndex),
				activePointsCollection = [];


Thanks a lot.
