### ISSUE TITLE
Dependency and import order - how to handle circular dependencies with composes

### ISSUE THREAD

**Issue by Ambroos** [css-modules/css-modules#11]
Hi!

I've been exploring CSS modules and came across an issue/quirk. Because of how composes works now, I think there might be arise some issues with large/complex codebases, maybe?

Currently, when `.specific` composes from `.general`, CSS modules simply adds both classes to the element `.specific` and relies on the order the CSS files were imported in the browser to make sure everything overrides correctly. This works fine as long as everything is simple and the hierarchy only flows in one direction in all cases.

But, how do you handle circular dependency in that case? Just like circular dependencies in Javascript modules, which means, simply fail? I suppose that's not that much of a problem, again, as long as everything in the hierarchy flows downwards. Am I right in thinking this?

**Comment by geelen** [comment]
We've talked about this, and we actually have a [test case](https://github.com/css-modules/css-modules-loader-core/tree/master/test/test-cases/multiple-dependencies) to verify that the output is in a certain order, but you're right, we should add it into the specification file.

For the record, circular references can't be handled properly, so it should either crash the build or simply return `{}` if the file is already on the stack. And the order needs to be deterministic, with dependencies coming before parents but siblings being included in source order (that's what our test confirms)

Will leave this open until I've had a chance to add it to the spec

**Comment by Ambroos** [comment]
I've been doing some more thinking, and the thing that was eating away at me turned out to be #12, not this. But good to hear circular references are dealt with as good as possible.
