### ISSUE TITLE
best practise for external libraries like bootstrap or foundation

### ISSUE THREAD

**Issue by timaschew** [css-modules/css-modules#113]
I didn't see any working solutions to `@import` libraries like twitter bootstrap, zurb foundation, etc.

**Comment by StevenIseki** [comment]
I have a few examples of importing css module libraries like Bootstrap or Pure. I am not sure if it is best practice, but it does work pretty well so far and I have been using it in production sites:

- [bootstrap-css](https://github.com/StevenIseki/bootstrap-css)
- [css-skeleton](https://github.com/StevenIseki/css-skeleton)
- [pure-css](https://github.com/StevenIseki/pure-css)

**Comment by timaschew** [comment]
Wow this is cool, what is your favorite?

But this doesn't _scale_, so if you want to use for instance foundation without to wrap it.
So let's rewrite my question to: __Best practise to mix local and global css modules in webpack__.

There is this issue that `@import` is not working in the `:global` scope.

**Comment by epilande** [comment]
@timaschew a possible solution would be to have two css loaders. One for global styles & one for css modules. 

For example: 
```javascript
{
  test: /\.global\.css$/,  // only files with .global will go through this loader. e.g. app.global.css 
  loaders: [
    'style-loader',
    'css-loader?sourceMap&importLoaders=1',
    'postcss-loader'
  ]
}, {
  test: /^((?!\.global).)*\.css$/,  // anything with .global will not go through css modules loader
  loaders: [
    'style-loader',
    'css-loader?modules&sourceMap&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]',
    'postcss-loader'
  ]
}
```

This way you can `@import` all the things in `app.global.css`

Warning: The problem with using frameworks like foundation or bootstrap is their styles can be very specific making it hard/impossible to override some of the styling with css modules.

**Comment by SohKai** [comment]
@timaschew You might interested in the discussion in #65 as well.

**Comment by chemoish** [comment]
I do what @epilande mentioned above, but it is seemingly a pain in the butt to mix global and local styles… html elements, etc.

**Comment by geelen** [comment]
Closing this in favour of #65. Future discussion can take place there.

**Comment by rwngallego** [comment]
@epilande 's is the final approach I've decided to use, however I've to point out that as the docs suggest Global styles should be handled with caution. It's usage is only recomendable for normalization: https://github.com/gajus/react-css-modules#global-css
