### ISSUE TITLE
Allow using emoji for generated classnames

### ISSUE THREAD

**Issue by wmertens** [css-modules/css-modules#119]
https://twitter.com/addyosmani/status/702976873467408386

It makes for very compact html and recognizable classnames… Plus it looks awesome :smile:

**Comment by Kovensky** [comment]
If using webpack, you can now do it using `css-loader@^0.14.0` and using `[emoji:n]` as the `localIdentName`, e.g. `[emoji:4]`.

**Comment by wmertens** [comment]
Looks like it is implemented in css-loader via https://github.com/css-modules/css-selector-tokenizer/issues/11 , so this is done, cool!
