### ISSUE TITLE
Pseudo element styling not applied from external file

### ISSUE THREAD

**Issue by Chrisriis** [css-modules/css-modules#120]
Hello! When I create a class that gets composed in the same file, the styling applied to its :before etc. works and is outputted. However, when I compose the same class from an external file, the pseudo stylings won't work anymore. Any ideas?
I use Webpack.js btw.

An example class:

```
.container {
  position: relative;
  margin-left: auto;
  margin-right: auto;

  &:before,
  &:after {
    clear: both;
    content: " ";
    display: table;
  }
}
```

In my case, when I compose this class from another file, the :before and :after gets ignored.

**Comment by TrySound** [comment]
@Chrisriis Can you show result css with this class?
