### ISSUE TITLE
Best practice using icon font

### ISSUE THREAD

**Issue by Igor10k** [css-modules/css-modules#125]
Not sure how to use icon fonts with css-modules the right way.

What I came up with first was an `<Icon>` React component that takes a `name` argument that looked something like this

```js
import css from './Icon.sass';

export default class Icon extends Component {
  render() {
    return <i className={css[this.props.name]}/>;
  }
}
```

and SASS file that looked something like this

```sass
.icon
  vertical-align: middle
  font-family: 'AI-Solid-Icons' !important
  ...

.arrowUp
  composes: icon

  &:before
    content: "\e953"

.arrowDown
  composes: icon

  &:before
    content: "\e954"

...
```

And I thought I got it right at first, but then I needed to add a way to change the color, so I added a `color` attribute and inside the component I started composing the final `className` using something like `[css[this.props.name], css[this.props.color]].join(' ')`. This goes against the concept of css modules that implies using single class, but looked like a nice compromise so I went with that.

But then I noticed that some icons were wrongly aligned vertically and this is usually easily fixed by adjusting the vertical-align using the parent selector like

```sass
.btn
  [class*="icon-"]
    vertical-align: -2px
```

And the only thing I can come up with to make it work with css-modules is to add another attribute like `valign` passing the number to it and either applying the vertical align directly using React inline styles or create a set of classes for all the possible `vertical-align` values which sounds even worse.

And in the end I'll get a component that is very far from the original css-modules concept.

Is there a correct way to do this? How do you use icon fonts with css-modules?

**Comment by joshwnj** [comment]
Hi @Igor10k , we've been using a similar approach with an Icon component, eg `<Icon name="star">` and it's been working quite well. We didn't run into the vertical alignment issue that you mentioned, however we did have a need to adjust the color and size. We did this with additional props `color` and `size`, which are used as inline styles.

>  This goes against the concept of css modules that implies using single class

Not sure what others think, but I don't know whether this rule is something to strictly keep. I think using `composes` to combine classes is useful for a few reasons, but there's also times when it's totally fine to manually add multiple classnames to an element.

Does that clear things up or are you running into other issues using icon fonts?

**Comment by Igor10k** [comment]
@joshwnj thanks for the reply. I've used the similar approach, just instead of inline styles I generate classes from passed params like `colorBlue` and `size16` and use multiple classes for the element since I prefer to keep CSS outside of JS where possible.

I kind of solved the vertical align issue by wrapping the `<Icon/>` element around another element where it's needed and applying the vertical align to that container element.
