### ISSUE TITLE
"universal" usage?

### ISSUE THREAD

**Issue by joeybaker** [css-modules/css-modules#13]
I'm looking for some help to figure out the best way to use css-modules in a "[universal](https://medium.com/@mjackson/universal-javascript-4761051b7ae9)" (server and client rendered) environment. Life is good on the client, but on the server, things get tricky.

Using React and css-modulesify, things I've considered:

1. using browserify to compile React components on the server, using the css-modulesify plugin, and then `eval`ing the result. I've not gotten this work yet, but I dislike any solution that involves eval and it's slow to go through the whole browserify pipeline.
2. using a babel plugin to parse css `require` calls in the same way css-modulesify works. Would this work?
3. just monkey patching `require` to do the same thing.

Has anyone tried this yet?

**Comment by joshwnj** [comment]
I was wondering about a babel plugin too. But for this case it would seem just as well to set a `require.extensions` handler, right?  That part should be easy, the thing that might make it hard is that transforming the css is an asynchronous task.

So rather than trying to make an alternate synchronous version, it might be less work to do something like:

- on application startup, `glob` for all css files and create a lookup of export tokens for each file
- once all files have been processed, register a require extension like

```
  require.extensions['.css'] = function(module, filename) {
    module.exports = lookup[filename];
  };
```

- and finally `require` the entrypoint of your node application. 

This way everything should work as expected, just with a slightly slower startup time.  Would that work for your case?

**Comment by geelen** [comment]
Why would it have to be asynchronous? It's just that one CSS file might require another, but that's the same with any JS as well..

**Comment by joshwnj** [comment]
Yeah there's no reason why it has to be async, that's the way it is now. 

I suggest sticking with async would be a quicker solution to get started, since writing a synchronous version seems like it might require updates to multiple packages. But either way would be cool

**Comment by joeybaker** [comment]
@joshwnj Thanks! The `require` extension is a good hack. I kinda agree though: for long-term, it would be great to have a way to do everything in a sync pattern to match `require`'s behavior.

**Comment by joeybaker** [comment]
@joshwnj Just for the record: here's where I landed: https://gist.github.com/a99b909f333eefbc2bea

usage:

```js
setupCSS(__dirname, (err) => {
  if (err) throw err
  require('my-front-end-components-that-require-css-files.js')
})
```

This seems "good enough" for me. Would this be an interesting module for css-modules? /cc @geelen

**Comment by sullenor** [comment]
> I'm looking for some help to figure out the best way to use css-modules in a "universal" (server and client rendered) environment. Life is good on the client, but on the server, things get tricky.

I faced the same problem and decided to solve it with require.extensions. So let me share my solution with you:

Usage: https://gist.github.com/sullenor/aa1e7afa25d040c35ce6
Patched *css-modules-loader-core*: https://github.com/sullenor/css-modules-loader-core

I did small research and came to a conclusion, that the main task is to implement synchronous parser for the *postcss* module. Also patch few scripts which execute it. However I'm new to `require.extensions` and *postcss*, therefore it will take me some time to figure out the better way to implement it.

I do hope you can point out some problems for me :)

**Comment by joeybaker** [comment]
@sullenor that's nice work. I think you've got a module and a PR there :)

**Comment by sullenor** [comment]
I should send pr with `require.extensions` module to *css-modulesify*, shouldn't I? Or would it be better to make a separate package?

**Comment by joeybaker** [comment]
I'm not a maintainer, but I'd think that the require hook is a new repo.

**Comment by geelen** [comment]
This is super neat. I could certainly see this being a new css-modules repo, just trying to think of a name & how to pitch it... @markdalgleish @joshwnj @joshgillies ?

**Comment by joeybaker** [comment]
maybe `css-modules-require-hook`?

**Comment by joshwnj** [comment]
Yeah cool stuff @sullenor .  

For naming, it seems the word "register" is often used in this situation (eg. `require('babel/register')`) so I wonder if it's appropriate here?  Maybe `require('css-modules-loader-core/register')` ?

**Comment by sullenor** [comment]
> For naming, it seems the word "register" is often used in this situation (eg. require('babel/register')) so I wonder if it's appropriate here?

I think it is.

> maybe css-modules-require-hook?

I like that name. Simple and suits it :) And the usage will be simple `require('css-modules-require-hook')`.

> Maybe require('css-modules-loader-core/register')

I also like the idea to put those modules together. It will be easier to maintain dependencies. And we will have one module as a loader.

@geelen do you mind, if I'll attach that file to my [pr](https://github.com/css-modules/css-modules-loader-core/pull/11) to the `css-modules-loader-core` module?

**Comment by sullenor** [comment]
I thought a little and the idea about new repo looks more attractive to me. I think I'll pick `css-modules-require-hook` as mentioned above.

> This is super neat.

thanks :)

**Comment by joshwnj** [comment]
Good onya @sullenor

**Comment by sullenor** [comment]
Well, looks like i've got a draft version https://github.com/sullenor/css-modules-require-hook
Still need to finish work with my pr, so i can put the appropriate version of the `css-modules-loader-core` and publish it in the npm registry.

**Comment by sullenor** [comment]
I also added some scripts to build the package, so you can try it out.
To install it simply run `npm i sullenor/css-modules-require-hook`.

**Comment by maxhoffmann** [comment]
Nice that already works for me. Does this already has an option to define how class names are generated? Basically I’d need to get the same class names as with webpack using `?localIdentName='[local]--[hash:base64:5]'` or a different variation of the setting.

**Comment by sullenor** [comment]
> Does this already has an option to define how class names are generated? Basically I’d need to get the same class names as with webpack using ?localIdentName='[local]--[hash:base64:5]' or a different variation of the setting.

No, it doesn't have any. I think its a good option. Unfortunately to add it, i need to check out how webpack works with it first.

I wonder if you can provide any information about modules which you use?

**Comment by Aluxian** [comment]
I'm not sure whether this fits in here, but for those who use webpack with css-loader/locals: I forked css-loader and added a new parameter for `localIdentName`: `sourceHash`. This generate a hash from the localName and the source code, so the class names are stable.

https://github.com/Aluxian/css-loader

**Comment by joeybaker** [comment]
@sullenor it would be great to get your require hook as a part of the css-modules org!

**Comment by SimonDegraeve** [comment]
+1 indeed.

**Comment by sullenor** [comment]
I have good news for you. With Joe's help I just released the first version.

**Comment by joeybaker** [comment]
:)

**Comment by sullenor** [comment]
@Aluxian as I know `css-modules-loader-core` uses postcss plugins to parse files and build tokens with unique names. I decided to implement module in a similar way, because it was easier. So, in order to implement an option to set some kind of pattern for classnames, it is necessary to modify the certain plugins. Unfortunately, I don't how to do it currently :)

Anyways, ability to specify a pattern for the classnames can be useful. It allows you to minify your static files (shorter names -> shorter files).

**Comment by sullenor** [comment]
> @sullenor it would be great to get your require hook as a part of the css-modules org!

I don't mind. @geelen Is it possible?

**Comment by geelen** [comment]
Yes! This looks really great!

Over the last month or so, a few people have started to talk about CSS Modules (& ICSS) being available in much more places (like Rails templates), and I think this could be the key to making that happen. Can you re-submit your PR for the changes to loader-core that would be needed and we can discuss there?

**Comment by sullenor** [comment]
@geelen Finally, I figured out how the loader-core works and managed to implement independent parser. So, it is not necessary anymore to apply any changes to the loader-core. That's why I canceled my pr.

But I use your tests to check the functionality.

**Comment by geelen** [comment]
:tada: https://github.com/css-modules/css-modules-require-hook :eyes:

**Comment by fingermark** [comment]
@sullenor what do I need to get this working in a universal app using webpack?  Is your fork the the recommended solution?  Do you have any demos of how I can achieve this?  I'm using this as my sample project https://github.com/erikras/react-redux-universal-hot-example

**Comment by sullenor** [comment]
@fingermark Hi, in order to achieve this, you need to add the require hook and set up the same way of building generic class names as webpack has. Unfortunately, I haven't finished the demo yet, but you can copy the setup and use it in your project.

Here is a small example:
https://github.com/sullenor/universal-demo/blob/master/server.js#L10-L22
https://github.com/sullenor/universal-demo/blob/master/webpack.config.js#L22-L23

Looks like webpacks' algorithm strongly depends on the context and I haven't found a better way to build a standalone function. So, the example may look a bit awful.

**Comment by bdefore** [comment]
@sullenor I tried to reproduce your webpack example, but it doesn't appear to have any effect, almost as though `generateScopedName` is not being called?

**Comment by vojtatranta** [comment]
@bdefore same problem here!

**Comment by vojtatranta** [comment]
@bdefore and I know why. If you use es6 babel imports it take all the imports up including imports that use css, therefore `hook(options)` is called after all `requires('./file.css')` that does not have `generateScopedName` customize by `hook()` call.

**Comment by nkbt** [comment]
Maybe try this one https://www.npmjs.com/package/babel-plugin-webpack-loaders?

**Comment by vojtatranta** [comment]
@nkbt  wow, this seems to fix the issue, but it is still a workaround, I considered behavior I described as bug or do you think it is ok?

**Comment by nkbt** [comment]
I'm not sure, since I don't use require hook

**Comment by jcreamer898** [comment]
@sullenor looking over your example, good stuff. Did you never run into the "rendered markup is different on the server vs the client" thing?
