### ISSUE TITLE
How would this work with React Native?

### ISSUE THREAD

**Issue by kristianmandrup** [css-modules/css-modules#130]
I see great promise in this approach, just wondering if anyone is using it with React Native and how so?
Clearly, it should be possible to generate the BEM like syntax which you outlined in your ReactiveConf talk I just watched. The for React Native we simply need to:
- wrap in a `Stylesheet.create` call and generate an object which for each local selector name points to the unique (local) BEM selector name. Anyone?

**Comment by kristianmandrup** [comment]
Ah sweet, didn't see this one until now:
https://github.com/gajus/react-css-modules

**Comment by thienanle** [comment]
@kristianmandrup How were you able to get [react-css-modules](https://github.com/gajus/react-css-modules) to work with React Native?

**Comment by abhisheksoni27** [comment]
@thienanle Did you figure out how to use it with RN?

**Comment by kristianmandrup** [comment]
I quit using React Native until it matures sufficiently to be worth my attention :P

**Comment by thienanle** [comment]
@abhisheksoni27 Nope. CSS on RN is just too different. [Styled components](https://github.com/styled-components/styled-components) works cross platform, though you need to be quite selective in what CSS rules you can apply.
