### ISSUE TITLE
Request for a FAQ

### ISSUE THREAD

**Issue by axelson** [css-modules/css-modules#137]
This is a documentation request for a FAQ (Frequently Asked Questions). The setup and usage of CSS Modules is very powerful and exciting. However, it is a very large mind-shift with many specific opinions that can be difficult to learn as a beginner. A FAQ would significantly help with the transition since there are many questions (theming, raw selectors, specificity issues) that crop up for people trying to move to CSS Modules especially when transitioning existing projects. Topics that would be good to cover include:
- `composes` only works with class selectors: https://github.com/css-modules/css-modules/issues/41
- Specificity and tag selectors: https://github.com/css-modules/css-modules/issues/131
- Theming: https://github.com/css-modules/css-modules/issues/98
- Raw selectors: https://github.com/css-modules/css-modules/issues/10
- Media queries: https://github.com/css-modules/css-modules/issues/75

**Comment by SgtPooki** [comment]
I searched around for information on specificity overriding with css-modules and for some reason, the term 'specificity' is not used enough for the tools they provide specificity overrides. :global and :local are not css terms. It would be nice just to throw in the word 'specificity' a few times and give specific examples of how to override global classes. It took me too long to find that all I needed was 

```css
:global(.frameworkClass) h2.myClass {/*...styles*/}
```

was what I needed.

**Comment by TrySound** [comment]
@SgtPooki Would you like to send a PR to clarify this?

**Comment by leerob** [comment]
Hello from the future! I've updated the README a bit and cleaned up some of the docs. Open to contributions if you think FAQs would still be helpful.
