### ISSUE TITLE
Empty style got undefined

### ISSUE THREAD

**Issue by camsong** [css-modules/css-modules#140]
``` scss
// styles.scss
.example {
}
```

``` jsx
render () {
  return <div className={styles.example}></div>
}
```

When `.example` is empty, `styles.example` will become `undefined`.

How to avoid this? since I don't need to set styles to `.example` right now, but have to override its styles somewhere else, so I need to get a dedicated class name.

**Comment by joshwnj** [comment]
@camsong as far as I understand, sass will delete empty selectors, which is why CSS Module is not giving it a unique name.

**Comment by ksrb** [comment]
@camsong if you don't mind what kind of tool chain are you using to use css modules I'm assuming webpack. 

I'm actually trying to have the `undefined` show up so that I can show a warning for the undefined style using the technique @sullenor [mentioned](https://github.com/css-modules/css-modules/issues/146#issuecomment-222208061).

If you don't mind could you share you sass loader or whatever config your using?

Mine
```json
      {
        test: /\.scss$/,
        loaders: [
          'style?',
          'css?modules&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5]',
          'postcss',
          'sass'
        ]
      }
```

**Comment by TrySound** [comment]
Will be fixed with new css-loader

**Comment by morgs32** [comment]
Is there no way for css-loader to just provide the classname anyway? Even if it's undefined?

**Comment by selcet** [comment]
Problem still is.

`css-loader v5.0.1`

Example of webpack config:
![Screenshot 2020-12-15 at 18 04 16](https://user-images.githubusercontent.com/6522667/102239876-f866c780-3eff-11eb-8327-87719b5d8800.png)

**Comment by edwardfhsiao** [comment]
Encountered the same problem after upgrading ```css-loader``` from ```2.1.1``` to ```5.0.1```.

```json
"css-loader": "^5.0.1",
"webpack": "^5.13.0",
"webpack-assets-manifest": "^5.0.1",
"webpack-cli": "^4.3.1"
"webpack-dev-server": "^4.0.0-beta.0"
```
```css
/*style.css*/
.a{} 
/*or even an empty file*/
```

```js
// index.js
import _STYLE_ from './style.css';
console.log(_STYLE_) // => undefined
...
return <div className={_STYLE_['wrapper']} />
```

```js
  loader: 'css-loader',
  options: {
    modules: {
      localIdentName: '[path][name]__[local]--[hash:base64:5]',
      localIdentContext: path.resolve(__dirname, 'src'),
    },
}
```

and then the app just stop running because it cannot read property wrapper of ```undefined```
I think it makes more sense to return an empty ```object``` for an empty css file instead of a ```undefined```

**Comment by Vladi4-gh** [comment]
Could it be fixed? Just provide class name anyway. The workaround is to provide an unused rule like display: block, but I don't want it.

**Comment by 7iomka** [comment]
Any workarounds in 2022?

**Comment by sanderkranz** [comment]
Any workarounds in 2023?

**Comment by alexbaumgertner** [comment]
I use
```css
.component {
  --add-class-for-empty-declaration: true;
}
```
but it seems too long...

**Comment by 7iomka** [comment]
> Any workarounds in 2023?

```css
.componentClassName {
  /*! keep */
}
```

**Comment by roshal** [comment]
```scss
.crutch {
  /*!*/
}
```

**Comment by FarisMarouane** [comment]
> > Any workarounds in 2023?
> 
> .componentClassName {
>   /*! keep */
> }

Inserting a comment works
