### ISSUE TITLE
Failing or Warning on using undefined style.

### ISSUE THREAD

**Issue by kriegerd** [css-modules/css-modules#146]
I'm just starting out with css-modules. Great work btw!.
I was wondering if it is possible to get warnings or errors when using undefined styles. 
Ideally I would like something like className={styles.notFound} to warn me it doesn't exist.

**Comment by joshwnj** [comment]
Hi @kriegerd, good question. Since the `styles.notFound` part is occurring in js, rather than in the css file, CSS Modules probably won't be able to help with it. A CSS Module just exports a js object of classname tokens, but what you do with it after then is your responsibility :)

I haven't tried this myself but it seems some people are successfully solving the problem you described with things like:

- flowtype: https://gist.github.com/lambdahands/d19e0da96285b749f0ef
- typescript: https://github.com/Quramy/typed-css-modules

Another less-cool-but-maybe-useful thing to do would just be open a js console and run `document.querySelectorAll('.undefined')` to find any places where an undefined style was used.

**Comment by sullenor** [comment]
@kriegerd if you are working with react you can try [react-css-modules](https://github.com/gajus/react-css-modules#whats-the-problem). It usually helps with missing properties.

Also there is a good approach from @markdalgleish — you can global style for the `.undefined` class name to detect missing props :)

**Comment by royriojas** [comment]
Actually with the `Proxy` object this can be solved at least when available. I've made a custom webpack loader that add this at the end of the local required css file

```
if (typeof global.Proxy !== 'undefined') {
  module.exports =  new Proxy(content.locals, {
    get: function(target, name) {
      if (!(name in target)) {
        throw new Error('local class for ' + name + ' not found!');
      }
      return target[name];
    }
  });
}
```

so for a file like 

```scss
.test {
  display: block;

  .demo {
    display: inline-block;
  }
}
```

you can use it like 

```javascript
import styles from './test.scss'

styles.test // .test__xxxx
styles.notFoundLocal // will throw (at least in browsers that support chrome)
```

**Comment by geelen** [comment]
Yep I find https://github.com/css-modules/css-modules/issues/146#issuecomment-222208061 to be the simplest approach. At least, until Proxies get widespread support (since they can't be polyfilled).

**Comment by joshwnj** [comment]
Here's a demo of combining css modules with flowtype, if anyone would like to try it: https://github.com/joshwnj/css-modules-with-flow

It's a little bit hacky, but cool to see it working.  And there's plenty of opportunity to make the integration more seamless with a little work.

**Comment by TrySound** [comment]
Will be fixed with new css-loader

**Comment by testerez** [comment]
@TrySound how is it fixed in new css-loader?

**Comment by morgs32** [comment]
@TrySound bueller! What does it mean to be fixed?

**Comment by TrySound** [comment]
Webpage 4 will land css as first class citizen and will rule it as we modules.

**Comment by a7madgamal** [comment]
by `Webpage 4` you mean Webpack 4 I guess :D
can someone confirm that webpack 4 solved this?

**Comment by bes** [comment]
This might be a blast from the past, but I made a simpler Proxy version based on @royriojas work, which only Proxies the `locals` (aka the actual class names -> global class names mapping object), and nothing else.

This way you don't need to modify your codebase if you want to introduce crash/checking behavior.

I posted the code here: https://github.com/bes/css-module-selector-exists
