### ISSUE TITLE
Issues with local scope inside global

### ISSUE THREAD

**Issue by jnatherley** [css-modules/css-modules#150]
```
Error: composes is only allowed when selector is single :local class name not in 
".ui-basket :local(.button-disabled)"
```

Except my css is:

```
:global .ui-basket {
    :local .button-disabled {
      composes: button-disabled from 'components/Button/button.scss';
      background: red;
    }
}
```

The Error isn't useful and the examples in documentation for local is sparse. Is composes possible under an initial global scope and then a `:local .button-disabled` scope?

**Comment by chemoish** [comment]
I am also using composition for `:local`, but a library is winning the specificity wars. I need to target the library globally.

^ what he said.

**Comment by geelen** [comment]
Composition only works with single top-level classes. It's something we really need to explain better, but for now, this comment of mine is probably the most comprehensive summary: https://github.com/css-modules/css-modules/issues/33#issuecomment-133623241
