### ISSUE TITLE
README.md not clear enough

### ISSUE THREAD

**Issue by edwinm** [css-modules/css-modules#151]
I you've never heard of CSS Modules (like me) and you read README.md, the questions only stack up.

"A CSS Module is a CSS file in which all class names and animation names are scoped locally by default." - Scoped? To what? How? Is it auto generating BEM notation? What is the prefix? The folder name?

"CSS Modules compile to a low-level interchange format called ICSS or Interoperable CSS" - Why do you want to do that?

"When importing the CSS Module from a JS Module" - Why would you want to import CSS from JavaScript?

Please start your README.md with the problem it is solving en preferably an example.

**Comment by mikeerickson** [comment]
+1

Having agreed, lets remember this is OSS so have some compassion.

**Comment by edwinm** [comment]
I'm fully aware :-) I did not intent to sound harsh.

**Comment by joshwnj** [comment]
Thanks @edwinm it's great to hear questions like this so that we can communicate the ideas better :)

> "A CSS Module is a CSS file in which all class names and animation names are scoped locally by default." - Scoped? To what? How? Is it auto generating BEM notation? What is the prefix? The folder name?

Would you find it clearer if we said _"A CSS Module is a CSS file in which all class names and animation names are prefixed to make them globally unique"_ ?

> "When importing the CSS Module from a JS Module" - Why would you want to import CSS from JavaScript?

Maybe this would be clearer as _"When importing the CSS Module into a JS Module"_. What do you think?

**Comment by edwinm** [comment]
@joshwnj Please start with describing which problem CSS Modules is solving. Add a little code example. Show the problem without CSS Modules and show the fix by using CSS Modules.

**Comment by neekey** [comment]
+ 1, the whole idea seems cool, but the documentation does not make much sense to me.

**Comment by neekey** [comment]
after reading @markdalgleish 's amazing article, it makes more sense to me now: https://medium.com/seek-ui-engineering/the-end-of-global-css-90d2a4a06284#.ow8bnkjh4

I guess the documentation need to bring out some background knowledge for those ( like me ) didn't know much about "local scope css"

**Comment by kevnk** [comment]
Does this count for documentation? https://github.com/ruanyf/css-modules-demos

If not, what other details do you still need?

**Comment by 100ideas** [comment]
I was confused too - experience level is too low for me to successful decipher what *extending* refers to in the [Implementations > Webpack](https://github.com/css-modules/css-modules#webpack) section at the bottom of the readme:

> "Extending adds the source class name(s) to the exports."
>
> "Extending from other modules first imports the other module and then adds the class name(s) to the exports."

CSS-tricks has an article (3-part series) that goes into more detail about [CSS Modules and how they work with webpack](https://css-tricks.com/css-modules-part-1-need/).

**Comment by dvkndn** [comment]
I think we should also have an example code on README to show how the "scoped" classes will look like, like in the section about css module on postcss website:

```css
// input
.name {
  color: gray;
}
// output
.Logo__name__SVK0g {
  color: gray;
}
```

**Comment by leerob** [comment]
Hello from the future! I've updated the README a bit and cleaned up some of the docs. Open to contributions.
