### ISSUE TITLE
Does css-modules work with webpack HotModuleReplacementPlugin?

### ISSUE THREAD

**Issue by smilingpoplar** [css-modules/css-modules#166]
The webpack hot reload stops working after I used css-modules instead of plain css. 
I have to use [webpack-module-hot-accept](https://github.com/loggur/webpack-module-hot-accept) in development to make HRM work.

**Comment by sanpojoe** [comment]
how are you using webpack-module-hot-accept? I'm having the same problem and it doesn't seem to help me.

**Comment by smilingpoplar** [comment]
@sanpojoe I just add `webpack-module-hot-accept` after the `babel` loader, as the README says
