### ISSUE TITLE
image not found inside :global

### ISSUE THREAD

**Issue by kabadesu** [css-modules/css-modules#173]
I'm a little out of my depth with explaining what is happening because I'm not really familiar with webpack and I'm pretty terrible at JavaScript.

The problem is this:

```
/*Works*/
.Select-arrow {
   background-image: url('images/icon_chevron_down-blue.svg');
}

/*Doesn't work*/
.selectable :global .Select-arrow {
  background-image: url('images/icon_chevron_down-blue.svg');
}

/*Works but undesirable as it's inconsistent with the rest of my css*/
.selectable :global .Select-arrow {
  background-image: url('../../../../../images/icon_chevron_down-blue.svg');
}
```

We are using react-select, so `:global` is necessary to be able to access it's internal class names without hashing it.

I'm wondering how to get the second example to work without having to do anything that is inconsistent to the rest of my styles?

At the moment my work around is to either use a relative path as above, or something like this which, again is something I'd like to avoid because it could be confusing for anyone who has to take over from me:

```
@value icon-chevron-down-blue "images/icon_chevron_down-blue.svg";

.selectable :global .Select-arrow {
  background-image: url(icon-chevron-down-blue);
}
```

Background stuff:

I just started contract with a team who is using webpack, react, css modules, and I was getting a bit frustrated with all of the relative paths being used in `composes` and `@value`, so I fixed that by doing

```
resolve: {
  root: [
    path.resolve('./src')
  ]
}
```

That has work really well for everything except this one line of code.

**Comment by kabadesu** [comment]
If it helps, the error I get when running `npm start` is:

```
ERROR in ./~/css-loader?modules&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5]!./src/modules/shared/components/widgets/interactive/css/NumericDropdown.css
Module not found: Error: Cannot resolve 'file' or 'directory' ./images/icon_chevron_down-blue.svg in C:\Projects\Blah\src\modules\shared\components\widgets\interactive\css
 @ ./~/css-loader?modules&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5]!./src/modules/shared/components/widgets/interactive/css/NumericDropdown.css 7:5954-6000
```

**Comment by dvkndn** [comment]
Hm.. this is weird.. as far as I know this might not related to CSS Modules.. CSS Modules doesn't resolve anything at all. This might be an issue with CSS Loader..
