### ISSUE TITLE
Using css-modules in Webstorm

### ISSUE THREAD

**Issue by Zephir77167** [css-modules/css-modules#176]
Hello,

Not really an issue with css-modules (which is awesome by the way), but is there a way to have code completion in Webstorm? And also get rid of warnings such as 'Unkown CSS at-rule'?

Thanks in advance and cheers for your work!

**Comment by dvkndn** [comment]
Hi @Zephir77167 , as far as I know.. CSS Modules only introduces 1 new keyword that is `composes … from`.  Why do you need code completion for CSS Modules? And also, why do you received "Unknown CSS at-rule" warnings? Is there any at-rule in CSS Modules?

**Comment by Zephir77167** [comment]
Hi,

There is also @value (hence the warning). It would be nice to have completion for `classes` present in `file` when typing `composes: classes from file;`, and same goes for `@value classes from file`.

**Comment by dvkndn** [comment]
Oh right.. well.. sadly, at the moment I also don't see any solution for this too.. maybe CSS Modules is not popular enough..

**Comment by Zephir77167** [comment]
That's a shame for such a useful library!

Anyway, thanks!

**Comment by jimkyndemeyer** [comment]
@Zephir77167 Just published https://github.com/jimkyndemeyer/react-css-modules-intellij-plugin for WebStorm and IntelliJ. Also, WebStorm 2016.3 now completes on "composes" and ":global". Only thing missing is the new at-rules, but you can disable that inspection.

**Comment by Zephir77167** [comment]
Hi, thank you for this, but my team and I are using the styles.class syntax in all of our project... So this isn't much use for us. Anyway nice contribution to the css-modules community!

**Comment by jimkyndemeyer** [comment]
Yeah, it's a shame about the "dot" style, but it's only one extra character to type since WebStorm auto-closes `[` and `'`. Then you've got full type-ahead for class names.

A quick regex search-replace can convert your existing code. It might be worth considering to get the additional tooling.

In any case, I'll bump this thread if "dot" style becomes possible in a later version.

**Comment by patrickgordon** [comment]
@jimkyndemeyer would be super keen on support for `styles.someClass`

Great job for what you've done so far

**Comment by skrivitsky** [comment]
But what is about decorator ?
