### ISSUE TITLE
 How about css-module's browser compatibility?

### ISSUE THREAD

**Issue by season19840122** [css-modules/css-modules#177]
I checked the document and a lot of other places, but did not find the relevant instructions.
People who want to know can tell me.thks!

**Comment by joeybaker** [comment]
If you're asking how css-modules affects browser compatibility, the short answer is: it doesn't.

The longer answer: css-modules is a build step that automatically gives you class names that you can apply in JavaScript. Your browser compatibility is determined by how you write your CSS and what you do in your JavaScript, but not by css-modules.

**Comment by season19840122** [comment]
@joeybaker You mean there is no browser compatibility issues, the problem has been very troubled me, thank you for your answer!

**Comment by joeybaker** [comment]
Correct. css-modules doesn't impact browser compatibility in any way. If that answers your question, please close the issue.

**Comment by season19840122** [comment]
@joeybaker OK
