### ISSUE TITLE
Can you optimize compose output when building a project?

### ISSUE THREAD

**Issue by marchdoe** [css-modules/css-modules#179]
Currently, when I utilize the compose feature, and then build my project, instead of it only writing styles used in the referenced stylesheets, it pulls the entire stylesheet into the build.

Is it possible to only build CSS files with composed CSS selectors, instead of the entire file those classes live in?

**Comment by dvkndn** [comment]
Hi @marchdoe,

**First,** selectors that are not related to "composes" at all are still neccessary, and can be used directly:
```css
/* button.css */
.main {
  color: red;
}
```
```jsx
// button.jsx
import styles from './button.css';
…
<button className={styles.main}>
...
```
Therefore, I think it is not make sense to excluding these selectors.

**Second,** if your idea is that we should exclude selectors that actually weren't used at all, then I don't think it is possible. CSS Modules is just a specs, which is implemented as an option in CSS Loader. CSS Loader then just returned the processed result, and does not (and should not) care how it will be used after that.

**Comment by marchdoe** [comment]
@dvkndn Thanks for the response

> Second, if your idea is that we should exclude selectors that actually weren't used at all, then I don't think it is possible. 

Exactly my question, and based on your comments realize now why it is not a possibility with just css-modules.

**Comment by dvkndn** [comment]
@marchdoe anyway, please also note that althought this is not possible with CSS Modules, it **is** possible with another tool/plugin/library. For example, if you are using Webpack, there is https://github.com/purifycss/purifycss-webpack-plugin which I guess is what you are looking for: it scans your app to find unused css and remove them

**Comment by marchdoe** [comment]
@dvkndn - great!  Going to give that a try.
