### ISSUE TITLE
Parameterization of css modules & media queries?

### ISSUE THREAD

**Issue by serapath** [css-modules/css-modules#18]
# Goal
* I'm trying to always write **components** which contain all the html/css/js they need.

# Status Quo
* In `javascript` I can export a function and pass in options, e.g.
```javascript
// DEFINITION [componentX.js]
module.exports = function (componentX) {
  var color1 = componentX.color1;
  var border1 = componentX.border1;
  // ...
};

// USAGE (e.g. [componentY.js])
var componentX = require('componentX')({color1:'#f00', border1:'1px solid black'};
// ...
```
* But in `css` I **CANNOT** pass `arguments` to an `@import` statement. 
```css
/* DEFINITION [componentX.css]
/* ??? how would that even look like ??? */

/* USAGE (e.g. [componentY.css]) */
@import 'componentX' {  /* doesnt work! */
  color1: #f00;
  border1: 1px solid black;
}
```
# (My) Status Quo
* Currently, I'm using [`atomify`](https://github.com/atomify/atomify)
* It allows the `package.json` to contain:
```json
  "main": "index.js",
  "style": "index.css",
```
**...and it watches those and all dependencies and processes them like:**
* all javascript `require('...')`s
* all css `@import ...`s
* all html/templates which get required and inlined as a string into javascript
* all `assets` used in any html/template or css
...and `"onChange"` updates a `bundle.js` and `bundle.css` file which live updates in the browser via `browsersync`

# Problem
* `atomify` allow me to write
```css
:root {
  --ComponentName-variableName1:  value;
  --ComponentName-variableName2:  value;
  --ComponentName-variableName3:  value;
  /* ... */
  --SubComponentName-variableName1: var(--ComponentName--variableNameX1);
  --SubComponentName-variableName2: var(--ComponentName--variableNameX2);
  /* ... */
}
```
* My `component`s define their "css input" through an INTERFACE as a set of
* `--ComponentName-variableNameX: value;`
* If I re-use a component as a `"sub-component"`, I can customize/overwrite the defaults specified in the sub-component itself (see above)

**My questions:**
* What if my "css variables" change in response to media queries matching?
* How would I approach the above and media queries with `css-modules`?

The following doesn't work when using `atomify`
```css
:root {
  --Theme-font-size1             : 6.5vw;
  --Theme-font-size2             : 3vw;
  --Theme-font-size3             : 2.3vw;
  --Theme-borderwidth            : 4vw;
  /* Sub Components */

  --Markdownbox-font-size1             : var(--Theme-font-size1);
  --Markdownbox-font-size2             : var(--Theme-font-size2);
  --Markdownbox-font-size3             : var(--Theme-font-size3);
  --Markdownbox-borderwidth            : var(--Theme-borderwidth);
}
@media all and (min-width: 0px) and (max-width: 450px) {
  :root {
    --Theme-font-size1             : 6.5vw;
    --Theme-font-size2             : 3vw;
    --Theme-font-size3             : 2.3vw;
    --Theme-borderwidth            : 4vw;
  }
}
@media all and (min-width: 450px) and (max-width: 600px) {
  :root {
    --Theme-font-size1             : 6.5vw;
    --Theme-font-size2             : 3vw;
    --Theme-font-size3             : 2.3vw;
    --Theme-borderwidth            : 4vw;
  }
}
```

**Comment by geelen** [comment]
Hi @serapath, thanks for your suggestions, and my apologies I haven't been able to respond until now.

I think it's probably helpful to point out what the goal of CSS Modules is and what it isn't. CSS Modules is about addressing some of the problems inherent in the current CSS workflow by adopting *some* techniques from the JS world. It isn't about addressing every possible styling problem and inventing syntax for it. In fact, I think one of the biggest strengths of CSS Modules over atomify & any of the JS frameworks is just how *little* new syntax there is to learn.

I've expressed a similar sentiment in response to this issue as well: https://github.com/css-modules/css-modules/issues/12

I feel like understanding theming of reusable components is a whole separate issue, and I'm really really resistant to adding any syntax to CSS Modules to support it at this stage. @markdalgleish has some thoughts on his project here: https://github.com/markdalgleish/react-themeable so it might be worth raising an issue there if you can find a use case his project doesn't cover.

**Comment by nkbt** [comment]
@geelen :+1: strongly agree.
It is much better to post-process (or pre-process) css modules independently.

After all you can still use `less` and preprocess with `less-loader` before it comes to `css-loader?modules` one.

**Comment by Naveenkumar2205** [comment]
i need to make my website responsive. help me with writing media queries in css modules. hit me naveenkumaramujuru@gmail.com for code .
