### ISSUE TITLE
What do you think about Atomic CSS and using it with CSS Modules?

### ISSUE THREAD

**Issue by jitendravyas** [css-modules/css-modules#184]
http://acss.io/

**Comment by tivac** [comment]
I don't see a whole lot of benefit to mixing the two ideologies, they're pretty fundamentally different approaches to solving CSS issues.

That said, once the tooling proposed in #181 exists it would be an interesting approach to author using CSS Modules but reap some of the benefits of Atomic CSS at build time.

**Comment by jitendravyas** [comment]
Thanks for reply @tivac. With ACSS I think I can keep CSS output as small as possible which is I think not the case with CSS Modules. With CSS Modules we can still have lots of duplicate declarations throughout the project.

**Comment by tivac** [comment]
Yeah, you just have to be willing to commit to the ACSS style of styling pages. I've tried it a couple of times and really didn't enjoy it. I think the idea is neat, it's just not for me.
