### ISSUE TITLE
general sibling selector?

### ISSUE THREAD

**Issue by dciccale** [css-modules/css-modules#185]
Hi, I'm very new to css modules and I'm moving all my styles into this approach.

I've found something I don't know how to convert into css modules, or if is even possible I would appreciate some help since I can't find anything in the docs or anywhere I've looked.

It's about [General sibling selector](https://developer.mozilla.org/en-US/docs/Web/CSS/General_sibling_selectors)

_variables.scss

``` sass
$navbar-height: 50px;
```

Navbar.scss

``` sass
.navbar {
  height: $navbar-height;
}
```

Body.scss

``` sass
.body {
  margin-top: 10px;
}

.navbar ~ .body {
  margin-top: $navbar-height;
}
```

So as you can see, the default margin-top for the .body is 10px. However If they html layout has a .navbar I want the .body to have a margin-top of $navbar-height.

How can I do this without making a global class navbar? can I import somehow the .navbar class name into my Body.scss file and use it?

Thanks in advance

**Comment by dvkndn** [comment]
Hi @dciccale , I think CSS that related to the relationship between components (like `margin-top`) shouldn't be placed in those components themselves. Instead, it should be placed in the parent of them.

So, in your case, this is how I currently do it:

app.jsx
```jsx
import styles from './app.css';
import Nav from './nav';
import Body from './body';

const App = () => (
  <div>
    {haveNav ? (
      <div className={styles.nav}>
        <Nav />
      </div>
    ): null}
    <div className={styles.body}>
      <Body />
    </div>
  </div>
);
```

```css
.body {
  margin-top: 10px;
}
.navbar ~ .body {
  margin-top: $navbar-height;
}
```

**Comment by dciccale** [comment]
Thanks @dvkndn works for me!
