### ISSUE TITLE
Styling 3rd party components with descendent selector

### ISSUE THREAD

**Issue by aaronbeall** [css-modules/css-modules#188]
I have a 3rd party component (actually they are 3rd party SVG elements pulled in at runtime and inlined in React using innerHtml) that uses an internal class name system like `bg` and `text` to style things. 

Imagine the resulting markup is like this:
```
<external-component>
  <div class="bg">
    <p class="text">Hello World</p>
  </div>
</external-component>
```

Using native CSS I would override it like this:

```
.my-component {
  & .bg { fill: red; }
  & .text { color: blue; }
}

.my-component-variant {
  & .bg { fill: black; }
  & .text { color: gray; }
}
```
```
<external-component class="my-component" />
<external-component class="my-component-variant" />
```

But this doesn't work in CSS Modules because `.bg` and `.text` get transpiled into a different name, but the external component expects `bg` and `text` class names verbatim. 

If it were my own component I guess the expected solution is to pass `bg` and `text` as props to the component, which would be fine. However since this is a 3rd party component I cannot do this. Is there any way to preserve the naming of `bg` and `text` in this context? Is there any other way to make this work?

**Comment by dvkndn** [comment]
Yes it is possible. Have you tried:
```css
.my-component :global(.bg) {
  color: red;
}
.my-component-variant :global(.bg) {
  color: gray;
}
```

**Comment by aaronbeall** [comment]
No I didn't make the connection but it seems `:global` is exactly the behavior I needed. Thanks!

**Comment by dvkndn** [comment]
You are welcome. We should put common use case like this to the Readme..

**Comment by wootencl** [comment]
+1 For putting this use case in the README. So simple yet provides a lot of power.
