### ISSUE TITLE
Multiple class selectors same class?

### ISSUE THREAD

**Issue by alexemorris** [css-modules/css-modules#189]
I am having various issues throughout my app whereby having selections for selecting only items with more than one class does not work with CSS Modules, am I doing something wrong or is this a limitation? 

Its getting styles for `.tab`css but not `.tab.active`. I've included some code but I'd be happy to explain more, thanks a lot! 

```javascript
    return (
     <div>
      <div className={styles.appTab} ><p>Color should be light grey</p></div>
      <div className={`${styles.appTab} active`} /><p>Color should be black</p></div>
    </div>
    );
```

```css
  .appTab {
    margin-bottom: $padding;
    cursor: pointer;
    color: $light_grey;
    &.active {
      color: black;
    }
}

```

I'm aware I could just add the style styles.active, however my example is very oversimplified and the reason I'm asking is to try and implement it with an existing module (react-split-pane) as I'm current having to use global styles for that.

Alex

**Comment by dvkndn** [comment]
Hi @alexemorris , can you explain more what do you want to achieve? You could also remove not related CSS in your example and provide more related component (for example, those `flex` css is not related to your question, while we can't see what is `activePane` or `tabs`. Without knowing their structure, it is hard to tell anything)

Anyway, I think what you want to achieve is possible (multiple class, child selector, etc...) with CSS Modules. However, I can't understand what you want and your current structure.

**Comment by dvkndn** [comment]
Actually, you can just explain what do you want to achieve in words (like "If parent tag has ".inactive" class, then the child is grayed out"), I can give a code example for you in CSS Modules :D

**Comment by alexemorris** [comment]
Can you check new example? I've tried to simplify, but I wrote it straight into github so there maybe syntax errors I haven't tried running it!

**Comment by dvkndn** [comment]
ok, thank you @alexemorris it is a lot more clear now.

The issue is that in CSS Modules, all classes are hashed. Therefore, in your case, both "appTab" and "active" will be hashed, so you can not use "active" directly like that. Or in other words, use `${styles.active}` instead of just `active`

Full example:
```jsx
return (
  <div>
    <div className={styles.appTab}><p>Color should be light grey</p></div>
    <div className={`${styles.appTab} ${styles.active}`}><p>Color should be black</p></div>
  </div>
);
```
```css
.appTab {
  color: gray;
}
.appTab.active {
  color: black;
}
```

**Comment by chbdetta** [comment]
But what if the `active` class can't be local? In case where the `.active` comes from an external library. How you achieve multiple class containing both local and global class?

**Comment by pietrofxq** [comment]
For anyone having the same issue, this is how you would fix it:

```
tbody {
    border: none;

    tr {
      cursor: pointer;
      transition: all 0.1s;
      box-shadow: 0 1px 3px rgba(0, 0, 0, 0.2);
    }

    :global tr.active,
    :global tr:hover {
      transition: all 0.1s;
      box-shadow: 0 0 5px 2px var(--colors-primary);
    }
}
```

**Comment by pietrofxq** [comment]
For class, this is the only way I could do it (the it doesn't work without parenthesis in :local)

```
:local( .actions-bar ) {
  position: fixed;
  width: 100%;
  left: 0;
  bottom: -100%;
  background: white;
  transition: all 0.2s;
  
  :global &.active{
    bottom: 0;
  }
}
```

**Comment by pavan-shipmnts** [comment]
> ok, thank you @alexemorris it is a lot more clear now.
> 
> The issue is that in CSS Modules, all classes are hashed. Therefore, in your case, both "appTab" and "active" will be hashed, so you can not use "active" directly like that. Or in other words, use `${styles.active}` instead of just `active`
> 
> Full example:
> 
> ```js-jsx
> return (
>   <div>
>     <div className={styles.appTab}><p>Color should be light grey</p></div>
>     <div className={`${styles.appTab} ${styles.active}`}><p>Color should be black</p></div>
>   </div>
> );
> ```
> 
> ```css
> .appTab {
>   color: gray;
> }
> .appTab.active {
>   color: black;
> }
> ```

Would it pick .apptab.active automatically if we do styles['active']?

**Comment by dvkndn** [comment]
@pavan-shipmnts no, it's exactly like traditional CSS. If you do `styles['active']`, it means use use the "active" class, not the "appTab" (and thus the style won't be applied)

In fact, this makes using CSS Modules very easy and flexible and powerful in the long run

**Comment by kimgysen** [comment]
Wny not just fix it so that it _does_ work. Intuitive things that have existed for decades being broken by vendor specific apis that complicate things that should be simple. It turns the entire industry into a fragmented mess.

**Comment by Rubon72** [comment]
styles.prev works well, `${styles.prev}` - see class name undefined in browser

**Comment by usernameisMan** [comment]
maybe you can try 
```
&:global.ant-form-inline {

} 
```

**Comment by ctsstc** [comment]
This is what ended up working for me in the latest Next JS v11 and React v17

`shared.module.scss`
```scss
.plyrFix {
  :global .plyr, :global .plyr__video-wrapper {
    height: 100%;
  }
}
```

`component.js`
```javascript
import styles from 'shared.module.scss'

// ... basic component here
//  example of component internals

<div className={styles.plyrFix}>
  <Plyr  />
</div>
```

**Comment by lethithanhtruc** [comment]
> maybe you can try
> 
> ```
> &:global.ant-form-inline {
> 
> } 
> ```

It's work!!!! Thank you so much!

**Comment by pedegago** [comment]
This does not works:

`.slick-dots li.slick-active button {
    @apply bg-brand-green-300;
    @apply scale-125;
}`

So, I rewrite to this and.. it works!

`.slick-dots li[class="slick-active"] button {
    @apply bg-brand-green-300;
    @apply scale-125;
}`

**Comment by ctsstc** [comment]
@pedegago if you want more flexibility try using `[class~="slick-active"]` so that there can potentially be other classes.

https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors#:~:text=is%20exactly%20value.-,%5Battr~%3Dvalue%5D,-Represents%20elements%20with
