### ISSUE TITLE
String usage

### ISSUE THREAD

**Issue by ai** [css-modules/css-modules#19]
Some of React fans said, that most amazing thing in JSX is that all code (HTML template and JS) is in one file.

Maybe we should do some syntax like this for CSS Modules:

``` js
import react from 'react';
import css   from `css-modules/string`;

let style = css`
  .link {
  }
  .link:hover {
  }
  @media (min-width: 500px) { .link {} }
`;

export default class Link exted React.Component {
    render() {
        <div class={style.link}>
        </div>
    }
}
```

Main question, how we can extract this styles from JS file too put them to CSS bundle.

**Comment by nkbt** [comment]
[Some other people](https://www.youtube.com/watch?v=ERB1TJBn32c) say that it is good to keep visual styles separated and state-styles in JS.

Which perfectly works. Visual styles go to component's CSS file and used for `className` prop, state-styles are simple JS styles and go to `style` prop.

**Comment by geelen** [comment]
I quite like this idea, but I can see a couple of problems.

1 - First, as you said, extracting into a CSS bundle isn't straightforward. It's pretty easy to generate `Stylesheet.create` calls from an inline CSS module, or even do something like this:

```
import react from 'react';
import css   from `css-modules/string`;

let style = css`
  .link {
  }
  .link:hover {
  }
  @media (min-width: 500px) { .link {} }
`;

export default class Link exted React.Component {
    render() {
        return <div class={style.link}>
          {css.toStyle()}
          ... other content here
        </div>
    }
}
```

where `toStyle()` equates to `React.createComponent('style', null, css.rawText)`. This would mean the CSS you use is injected directly into the DOM and so can be server-side snapshotted. And only the components that get their `render` method called will actually appear in the DOM. Which I kind of like!

2 - The runtime cost of on-client CSS processing. The advantage of CSS Modules is that the loader does the transpilation work, and so the output can be cached & bundled. With CSS in-line like that, it feels more like you want `css-modules/string` to work like a JSX extension, where it compiles the CSS as a source-level transformation, so there's no work to do at runtime. I suppose that's possible! But not simple :)

3 - Handling `composes`. My CSS Modules code reads like:

```css
.link {
  composes: blue underlined from "./branding.css";
  composes: medium small-caps from "./typography.css";
}
```

So almost every component refers to other files. We'd need to translate them into `require` statements of some fashion. Something to think about...

If we could figure out a way to make an inline CSS Modules syntax, effectively a JSX for CSS, that would be super cool and really open up a new workflow. So let's keep the discussion going hey? Thanks for kicking this off, @ai.
