### ISSUE TITLE
Composes using Sugarss

### ISSUE THREAD

**Issue by lagden** [css-modules/css-modules#192]
Is there anyway to make composes using sugarss syntax?

**Exemple**

```styl
// shared.sss
.some
	font-size: 2em

.another
	box-sizing: border-box
```

```styl
// component.sss
.super-btn
	composes: some from '../../shared.sss'
	background: green
```

Nowadays, I am running the postcss twice...

1. `.sss` to `.pre.css`
2. `.pre.css` to `.css`

**Comment by TrySound** [comment]
New major version css-loader will not parse css. All css processing will handled by postcss-loader
