### ISSUE TITLE
CSS Modules With Selenium?

### ISSUE THREAD

**Issue by jabacchetta** [css-modules/css-modules#194]
I'm using [identity-obj-proxy](https://github.com/keyanzhang/identity-obj-proxy) for unit testing.

However, our QA team is having trouble with the obfuscated class names from CSS Modules while using Selenium — which I'm not too familiar with myself.

Are there any solutions here?

**Comment by dvkndn** [comment]
Hi @jabacchetta , so far we have seen some ways people used to solve this:

**1. Combine hashed class with normal class**

Don't forget that classes hashed by CSS Modules are just strings (returned by CSS Loader if you use Webpack). Therefore, you can use them together with your classes, like this:

```jsx
import styles from 'app.css';
<div className={`${styles.sidebar} app-sidebar`} />
```

it will be compiled to:

```jsx
<div class="_s8js2 app-sidebar" />
```

**2. You other attribute for selector** 

```jsx
<div className={styles.sidebar} id="app-sidebar" />
```

You can use `data-…` attribute for more control if you want

**Comment by TheSisb** [comment]
Option 3 is the way to go with this.

**Comment by jabacchetta** [comment]
Yup, localIdentName worked great, thanks!

**Comment by Glogo** [comment]
If you don't want to turn off CSS hashing for testing, you can for example something like:
```js
const selector = '[class^="MainLayout__menu"]';
```

This would match each element that has class name starting with "MainLayout__menu". For example:
```html
<div class="MainLayout__menu_s8js2">...</div>
````

**Comment by williamboman** [comment]
> Option 3 is the way to go with this.

How do you ensure class names doesn't conflict using this method? Sort of defeats a major feature of CSS modules.

**Comment by amannn** [comment]
I experimented a bit with `[class^="MainLayout__menu"]` kind of selectors, but noticed this is problematic when an element has multiple class names. E.g. when you try to match `<div class="Menu__root_d2K1 MainLayout__menu_s8js2">...</div>` with the mentioned selector it fails because you only match that the attribute value of `class` and not individual class names.

So I ended up generating deterministic class names (in my case `MainLayout-menu`) which works fine. This comes with the restriction that all component names are unique, but this is fine for me and maybe even desirable. A nice side effect is that if you use something like [Sentry](https://sentry.io), you get clear names of the elements a user interacted with in bug reports.

**Comment by williamboman** [comment]
Thanks for sharing @amannn. Do you accomplish this entirely by setting the `localIdentName` configuration string?

What's your thoughts on this way of solving it (React):

```jsx
const TestTargetElement = ({children, ...rest}) => {
    if (__TEST__) {
        return (
            <span {...rest}>{React.Children.only(children)}</span>
        )
    } else {
       return React.Children.only(children)
    }
}

const App = () => {
    return (
        <main>
              <TestTargetElement data-sidebar>
                 <Sidebar />
             </TestTargetElement>
             <TestTargetElement data-content="main">
                  <Content />
              </TestTargetElement>
        </main>
    )
}

// and to select Sidebar and Content in our acceptance tests
const content = browser.element('[data-content="main"] > *')
const sidebar = browser.element('[data-sidebar] > *')
```

The only downsides I can see would be polluting the React component tree hierarchy.

**Comment by amannn** [comment]
@williamboman Yes, I just went for `localIdentName: '[name]-[local]'`.

I think your approach can work fine.

Personally I wouldn't do it for the following reasons though:
 - If you want to avoid class selectors entirely, you'd have to resort to tag selectors if you want to target an element within a component (e.g. `[data-sidebar] > div:nth-child(2) > button`). These selectors can be fragile.
 - I think that extra span can break some layouts, especially if it contains block level elements.
 - You now need a separate build for testing as well as production, right? If the build isn't 100% deterministic this could be problematic.

If you want to avoid deterministic class names, I think I'd hardcode the data attributes, so they are also there in production. Do you see a downside of that?

**Comment by williamboman** [comment]
> If you want to avoid deterministic class names, I think I'd hardcode the data attributes, so they are also there in production. Do you see a downside of that?

Yeah after playing around with my idea a bit more I realised it'll just complicate things a lot, with very little gain. I initially didn't want to use hardcoded `data-*` attributes because it felt wrong to include "test artefacts" in production, but it's a really minor pet peeve that I definitely can live with. I decided to continue with hardcoded `data-*` attributes.

**Comment by jackocnr** [comment]
@amannn you got me thinking with this:

> I experimented a bit with `[class^="MainLayout__menu"]` kind of selectors, but noticed this is problematic when an element has multiple class names

Did you try the `[class*="MainLayout__menu"]`? It matches classes that contain the given string, so should work with multiple classes as well.

I guess there could potentially be a clash if you have two components with similar names which use the same class name e.g. if you had Button and LargeButton components, both of which had a "green" class, then `[class*="Button__green"]` would match both of them, but I don't think that would happen very often.

**Comment by linorabolini** [comment]
I decided going for aria attributes instead of data attributes. If you also think about it is a win win because you also test that the app makes sense for screen readers !
