### ISSUE TITLE
Convert css file to css-modules

### ISSUE THREAD

**Issue by cynicaldevil** [css-modules/css-modules#197]
I have a css file that I copied from the web which I want to use in my project, and I want to convert it into a css-modules file. I can't figure out how to convert some of the selectors like:
```
.contactsGrid figure {
   ...
}

.contactsGrid figure img {
    ...
}

.contactsGrid figure figcaption > a {
    ...
}
```
I could give each element (like `figcaption` and `img`) a separate class name and use compose to inherit from `contactsGrid`, but then there's the problem of coming up with names for all the classes. Also, I have no clue how to convert the relation-based selectors (like the one in the example above).

**Comment by TheSisb** [comment]
> I could give each element (like figcaption and img) a separate class name

That is the recommended approach. 

> but then there's the problem of coming up with names for all the classes

By default CSS modules are locally scoped, so naming should be less difficult than in traditional CSS.  For example I name the outermost class `.root` in all my css module files.

> I have no clue how to convert the relation-based selectors (like the one in the example above)

They should work just fine in CSS Modules.
Example input:
```css
.apple .banana
```
output:
```css
.3121321-apple .312321321-banana {}
```
