### ISSUE TITLE
why not link classnames with component

### ISSUE THREAD

**Issue by sir-marc** [css-modules/css-modules#198]
It's more like a question than a problem.

The goal of css modules is to reduce naming conflicts. This is done by importing the className directly to the component in a Javascript-Object way.
This is the main reason for me not to use css modules, because it breaks the known way on how to write css in html. Why not just declare a css classname matching the components name.

scss:

```
.my-custom-component {
  .header { font-size: 40px; }
}
```

react component:

```
render() {
  <div className="my-custom-component">
    Hello <span className="title">World</span>  
  </div>
}
```

with this approach you can stick to the old fashioned way in declaring "css in html" and not get the into troubles because of naming conflicts.

Please tell me what you think about it.

**Comment by dvkndn** [comment]
There are use cases where we want to use hashed classes together with normal classes:

```jsx
<div className={`${styles.hashed} normal`} />
```

**Comment by sir-marc** [comment]
I dont think i get the point of point 1.

2. My approach does not use CSS Modules at all. I was wondering, why I should use it. (react-css-modules) points out the disadvantages.

3. Yes this looks very nice, but again, whats the point of using it over just normal classes?

**Comment by joshwnj** [comment]
@sir-marc you're right that you can get a lot of the same benefits of CSS Modules by following a naming convention. But that can also introduce a lot of mental overhead when your project reaches a certain size.

There's a lot of other things that CSS Modules does, beyond reducing naming collisions. I guess the core benefits, that would be difficult to produce by hand, spring from having a bridge between css code and js code. This means we can get more out of our other tools as well (eg. building, linting, static type checking, optimization).

Does that address your question or are there still other things?
