### ISSUE TITLE
Do attribute selectors work with CSS Modules?

### ISSUE THREAD

**Issue by hidace** [css-modules/css-modules#199]
Hi, 

I'm using CSS modules for styling, like so:

`<div className={styles.book__title}>Title: {book.title}</div>`

Because class names are hashed, the compiled output is something like:

`<div class="book__title_adsfj4">Title: The Lord of the Rings</div>`

I've added an event listener on a button that, when pressed, adds the 'title' class to this element to offer additional styling:

`<div class="book__title_adsfj4 title">Title: The Lord of the Rings</div>`

In order to get around the fact that this 'title' class is not hashed since it's being added through the button click and not within the React element beforehand, I'm trying to use a css attribute selector to style 'title' (and any other elements that begin with "title"), but it doesn't seem to work:

Here's what I have in my css file:

```
div[class^="title"] {
  /* styles here */
} 
```

Does CSS Modules work with attribute selectors or should I be approaching this differently?

Thanks (and thanks for all your awesome work)!

**Comment by joshwnj** [comment]
@hidace attribute selectors should work, but there might be a better option.

Is it possible to pass the `styles` object to the event listener?  That could lead to better encapsulation since you'll still be using classes within the module's namespace.

**Comment by hidace** [comment]
@joshwnj Yes! This is a great point, works and like you said, the better option. Thanks for your help - appreciate it!

**Comment by joshwnj** [comment]
thanks for sharing your solution @hidace !
