### ISSUE TITLE
Motivation for camelCase naming

### ISSUE THREAD

**Issue by ronny** [css-modules/css-modules#20]
`For local class names camelCase naming is recommended, but not enforced.`

What was the motivation behind the camelCase naming recommendation? Perhaps we could add it to the README, it's not very obvious to me.

**Comment by nkbt** [comment]
import styles from 'styles.css';
... className={styles.camelCaseClass}
...className={styles['non-camel-case']}

First is definitely better.

**Comment by ronny** [comment]
Ah, of course. Thanks.
