### ISSUE TITLE
App layout using CSS modules.

### ISSUE THREAD

**Issue by Extra-lightwill** [css-modules/css-modules#206]
It's not immediately obvious to me how you would approach overall layout (and what best practices regarding layout might be) using CSS modules.

Say you wanted a global responsive grid.css file to do stuff like:

`<div col-xs-12> `etc. 

Could this be used in tandem with CSS modules and would there be any issues?

I realise that maybe you could avoid this issue by using a component-based grid approach but it's not something i'd like to do for my particular use-case.

**Comment by bernardodiasc** [comment]
If I understood your question, being in other words the need of reuse classes on application wide level instead component level, what you can do is to have these classes in some global place and use it with `compose` inside components css.

**Comment by joshwnj** [comment]
@Extra-lightwill here's an example of using a 3rd-party grid library with css modules: https://github.com/x-team/starting-css-modules/tree/master/03-grid

Is that the kind of thing you had in mind?
