### ISSUE TITLE
Nested Components

### ISSUE THREAD

**Issue by ChrisSargent** [css-modules/css-modules#207]
Hi, I'm just trying out CSS Modules in a React App and I'm trying to work out the best way to use nested components with CSS Modules.

For a simple Blog Post for example, lets say I have a Generic Header component:

``` jsx
import React from 'react';
import styles from './header.sass'

function Header(props) {
  const {subtitle, title} = props;

  return (
    <header className={styles.header}>
      <h1 className={styles.title}>{title}</h1>
      <span className={styles.subtitle}>{subtitle}</span>}
    </header>
  );
}

export default Header;
```

That I might call from a Post Component:

``` jsx
import React from 'react';
import Header from '../article-header';
import styles from './_post.sass';

function Post(props) {
  const {post} = props;

  return (
    <article className={styles.article}>
      <Header title={post.title} subtitle={post.subtitle}/>
      <div>{post.content}</div>
    </article>
  )
}

export default Post;
```

But then I also want to reuse that Header component from my 'Author' component like so:

```jsx
import React from 'react';
import Header from '../article-header';
import styles from './_author.sass';

function Author(props) {
  const {author} = props;

  return (
    <aside className={styles.aside}>
      <Header title={'Written by ' + author.name} subtitle={author.dob} />
      <div>{author.description}</div>
    </aside>
  );
}

export default Author;
```

And then let's (reasonably) assume I want the Header to be styled different depending on whether it's called from the Author Component or the Post Component. What are you recommendations for doing that?

I realise I could pass down the unique classnames in the props but I think that will get pretty messy, pretty quickly with multiple nested components.

**Comment by joeybaker** [comment]
@ChrisSargent This is a frequent question, but not one that we've really documented anywhere. There are a few of theories:

## Pass down `className` as a prop
**Pros**: This is easy to figure out and implement. 
**Cons**: Breaks isolation of components. It breaks the guarantee that if you change the CSS of `<Header>` you won't accidentally break something in `<Author>` or `<Post>`.

##

**Comment by joeybaker** [comment]
Edited to complete my comment. (Sorry, pressed "enter" too soon!)

**Comment by ChrisSargent** [comment]
Hi Joey,

Thanks for the approaches, I appreciate it. I'm not so keen on the third because it seems an anti-pattern to have a multiple identical html / js components that only differ in their CSS class names.

The other way I just tried (I don't think the approaches above include this) was to just pass down the entire styles object as a prop and not giving Header any styles of its own (just use extends / mixins instead). So:

```jsx
import React from 'react';

function Header(props) {
  const {subtitle, title, styles} = props;

  return (
    <header className={styles.header}>
      <h1 className={styles.title}>{title}</h1>
      <span className={styles.subtitle}>{subtitle}</span>}
    </header>
  );
}

export default Header;
```

```jsx
import React from 'react';
import Header from '../article-header';
import styles from './_post.sass';

function Post(props) {
  const {post} = props;

  return (
    <article className={styles.article}>
      <Header title={post.title} subtitle={post.subtitle} styles={styles}/>
      <div>{post.content}</div>
    </article>
  )
}

export default Post;
```
```jsx
import React from 'react';
import Header from '../article-header';
import styles from './_author.sass';

function Author(props) {
  const {author} = props;

  return (
    <aside className={styles.aside}>
      <Header title={'Written by ' + author.name} subtitle={author.dob} styles={styles} />
      <div>{author.description}</div>
    </aside>
  );
}

export default Author;
```

Then the css files from Post and Author will contain all the rules for Post / Header and Author / Header respectively.

Obviously this could get cumbersome with several levels of nesting but that's kind of always an issue with React or any other componentized system.

What do you think to this - am I missing something or..?

Chris

**Comment by tivac** [comment]
I prefer the approach that was discussed here using `:external` https://github.com/css-modules/css-modules/issues/147#issuecomment-217926425

It hasn't been added to CSS Modules yet. 😕

**Comment by joeybaker** [comment]
@tivac is right, `:external` would be a great answer here. 

@ChrisSargent your approach is another "standard" idea; most people call it "theming". It's not a bad idea if your goal is to open source your components or if you need to have dramatically different style changes in your app (e.g. a "dark mode").

However, it does come at a downside: it means your components are no longer self-contained. It's really nice to just `import MyComponent from '../my-component/'` and be done. 

Obviously, there's no wrong answer, but from what I've seen, components rarely wind up having the same markup with dramatically different styling. It's way more common to have slight markup or behavior differences that make it worth it to adopt the mental consistency of

**Comment by hyperh** [comment]
+1

**Comment by smperng** [comment]
@ChrisSargent There is a slight variant to your idea which makes the component both self-contained and fully customizable. I call it the "Pluggable CSS Modules Pattern". See my blog at https://medium.com/@shyanmingperng/pluggable-css-modules-pattern-30d7a83acd5e#.xmsozfzap

**Comment by ChrisSargent** [comment]
@smperng Interesting, I'll try to look into that a bit further at some point soon.
