### ISSUE TITLE
Nesting local classes in separate module

### ISSUE THREAD

**Issue by mwillmott** [css-modules/css-modules#21]
Drawing from Bootstrap, i have `Button` and `ButtonGroup` components (React variety). Each has it's own CSS module. What i'd like to do is nest the Button component class in the ButtonGroup so that its styling changes. At the moment

```css
/* button.css */
.button { ... }

/* buttongroup.css */
.buttonGroup > .button { .... }
```

transforms to something like:

```css
.button---3h-GD { ... }
.buttonGroup---3qigr > .button---3t-2h { ... }
```

The nested button class has no reference to the button module so ends up with a difference class name, hence the styling for that component doesn't change when contained within a ButtonGroup.

I've been trying to figure out if the following can/should be done with `composes` or, rethinking how the component works (e.g. the ButtonGroup component could apply a new class to each child rather than using nested selectors.). Maybe what i'm trying to do is against what is being achieved with CSS modules but if so, what do you see as the suitable alternative to achieving the same behaviour?

**Comment by joeybaker** [comment]
If you want to, you can work around the problem with the `:global` syntax, but I think this is a place where you'll find that bootstrap's way of thinking and the "component" way of thinking endorsed by css-modules don't agree. Bootstrap's `ButtonGroup` breaks one of the core-tenants: no more conflicts. If a parent component can change the way a child behaves, we no longer have encapsulation. 

Some alternative approaches:

1. Have buttons take a prop that allows their styling to match what a button group would do. This might come close to eliminating the need for a `ButtonGroup` component.
2. Have your button group component set its own classnames on its button `children`. This is kinda "magical" and breaks encapsulation, but might come the closest to what you want.
3. Create a whole new `ButtonGroup` component that doesn't use the `Button` component at all.

IMHO

**Comment by oliverbenns** [comment]
I did @joeybaker 's second suggestion not too long ago. [Gist](https://gist.github.com/oliverbenns/21ff754c2a30b77c6fb2#file-button-set-js-L9)

**Comment by nkbt** [comment]
:+1: to @oliverbenns 

I do the same and believe this is the most reasonable approach. Let's stop adding side-effects and do just plain composition.

**Comment by princed** [comment]
There's one _trick_ to make this work:

```css
/* button.css */
.button { 
  composes: button from ".../buttongroup.css"
  ... 
}

/* buttongroup.css */
.buttonGroup > .button { ... }
```

still transforms to something like

```css
.button---3h-GD { ... }
.buttonGroup---3qigr > .button---3t-2h { ... }
```

but exported from "button.css" styles object now looks like

```js
{
  button: "button---3h-GD button---3t-2h"
  //  ...
}
```

Thus any modification you may want to apply to `.button` in`buttongroup.css` will work inside button group.

**Obvious downside:** `button.css` has `buttongroup.css` as a dependency.

**Comment by bladeSk** [comment]
For anyone coming here from the search, here's another trick you can use. This one uses a `@value` import and is arguably cleaner/less hacky: https://github.com/css-modules/css-modules/issues/147#issuecomment-530160136
