### ISSUE TITLE
Question: are empty classes removed from code in production?

### ISSUE THREAD

**Issue by rhysburnie** [css-modules/css-modules#212]
Hi,

Just a question out of curiosity.
When you have lots of classes that simply compose from others will the empty ones be removed from the production css? or is this considered unimportant?

```
.c759P99YX_jEf0Zqf_e80 {
}
.BEKr3o14s8_mvVPDKCP0G {
    background: #ff5722;
    color: rgba(255, 255, 255, 1);
}
```

**Comment by taion** [comment]
Your minifier usually takes care of that.

**Comment by Benno007** [comment]
css-loader?root=.&localIdentName=[hash:base64:5]&**minimize**&modules&importLoaders=1 in a webpack config will remove the empty class from the CSS, but it will not remove the class from the DOM element.
