### ISSUE TITLE
import style from index.less      nodejs  SyntaxError

### ISSUE THREAD

**Issue by a573367014** [css-modules/css-modules#214]
![s1rfx_0yw0djwlqco8 i g](https://cloud.githubusercontent.com/assets/14799720/23297893/4647d7ce-fab6-11e6-9b32-f5ec206b33ab.png)
![uz4 z op k0 bslj buj](https://cloud.githubusercontent.com/assets/14799720/23297895/468f9d16-fab6-11e6-9fec-eb1a6d9e2262.png)

**Comment by TheSisb** [comment]
This might not be a css modules error.  You have a syntax error in your CSS.  Either your build isn't parsing LESS files correctly or you have a genuine typo.
