### ISSUE TITLE
Ampersand not in docs

### ISSUE THREAD

**Issue by hyperh** [css-modules/css-modules#215]
Is the ampersand part of the CSS modules spec? I was always under the impression it was for SCSS or LESS and not CSS.

But I just tried this with CSS and I got what I expected: `TEST` has a red background, while `TEST 2` does not. 

I think this should be reflected in the docs.

```
// styles.css
.wrapper {
   &.blah {
      background: red;
   }
}
```

```
import classNames from 'classnames';
import styles from './styles.css'
const Test = () => (
   <div>
      <div className={classNames(styles.wrapper, styles.blah)}>TEST</div>
      <div className={classNames(styles.blah)}>TEST 2</div>
   </div>
)
```

However, other SCSS stuff doesn't work like this.
I would expect this to be equivalent to `.wrapper .blah {...}`, and `TEST` and `TEST 2` should be red. But they aren't.
```
.wrapper {
  .blah {
    background: red;
  }
}
```

**Comment by taion** [comment]
That's not CSS modules; that's a PostCSS add-on.

**Comment by hyperh** [comment]
@taion Oh ok my mistake. Thanks for the info.
