### ISSUE TITLE
animation-name: none encodes "none"

### ISSUE THREAD

**Issue by dzearing** [css-modules/css-modules#216]
Input:
animation-name: none;

Expected output:
animation-name: none;

Resulted output:
animation-name: none_abc123;

**Comment by TheSisb** [comment]
This is intended afaik.  What's the issue?

**Comment by tivac** [comment]
@TheSisb `none` is a special value for `animation-name`.

https://developer.mozilla.org/en-US/docs/Web/CSS/animation-name

**Comment by TheSisb** [comment]
Oh right.  Bug indeed.

**Comment by TrySound** [comment]
Works here
https://github.com/css-modules/postcss-icss-keyframes
