### ISSUE TITLE
Sharing CSS Modules As Packaged Components

### ISSUE THREAD

**Issue by Undistraction** [css-modules/css-modules#217]
I've just extracted some React components from my main project into to a separate npm module and My module structure is pretty standard. The React components use ES6, so I need to transpile the jsx and compile the css modules across from my src directory to a lib directory.

```
    src 
     - Alpha
       - Alpha.jsx
       - Alpha.css
     - Beta
       - Beta.jsx
       - Beta.css
    lib
     - Alpha
       - Alpha.jsx
       - Alpha.css
     - Beta
       - Beta.jsx
       - Beta.css
```

I can't find any reliable way to do this. There is a CSS modules babel loader, but it is built for server-side use and using babel --watch doesn't pick up changes to CSS files. I started down the Webpack route, but Webpack doesn't seem to like dealing with multiple output files/locations. PostCSS CLI only works for the style part of the equation. 

What is the recommended way of doing this?

**Comment by borela** [comment]
[I just precompile the jsx files](https://github.com/ctrine/react-ui/blob/master/package.json#L11) and copy the raw CSS files. Projects that use that lib will use [webpack and the css modules loader](https://github.com/ctrine/webpack-settings/blob/master/src/rules/sass-module.js) which can takes care of compiling the CSS modules in the end product.

**Comment by Undistraction** [comment]
@borela Thanks. So do you whitelist any `node_modules` that contain CSS Modules in your webapack config. Otherwise if you add `node_modules` to your included paths for the loader it will treat everything inside as a CSS Module won't it?

**Comment by borela** [comment]
I use different extensions `mcss` for modules and `css` for normal CSS. In previous projects I had to whitelist certain modules but it was not fun.

**Comment by Undistraction** [comment]
@borela Thanks. That makes sense. For your own packages at least.

**Comment by borela** [comment]
I personally would like to precompile the CSS too, but I see more and more projects either requiring that you whitelist some packages or using custom extensions.

**Comment by Undistraction** [comment]
@borela I think the custom extensions would be great if there was a consistent extension, and I guess the beauty of not compiling the css is that the app can compose classes from the libraries which would be impossible with compiled css.

**Comment by borela** [comment]
@Undistraction yeah, a custom extension standard would be great as even the sass loader is limited by the [lack of settings to override them](https://github.com/webpack-contrib/sass-loader/issues/339).

**Comment by jonathanadler** [comment]
@borela @Undistraction 
Could this: #229  be something you'd find helpful?

**Comment by dmi-dmi-dmi** [comment]
@borela would you mind sharing how you organize JSX precompilation? I am having hard time trying to understand how precompilation works because components should refer final CSS class names which are not know at the time of precompilation.

Thanks
