### ISSUE TITLE
`:global` and `:local` keywords syntax for `sass` or `stylus` without curly braces

### ISSUE THREAD

**Issue by merraysy** [css-modules/css-modules#221]
Hey there,

I can't write this :
```scss
:global {
    .global-class-name {
        ...
    }
}
```
in indentation based nesting syntax like in `.sass` and `.styl` files e.g. :
```sass
// this is not working for me
:global
    .global-class-name
        ...
```

Is this not supported yet ? what am I missing ?

**Comment by TheSisb** [comment]
`:global(.global-class-name)`

**Comment by merraysy** [comment]
Thanks @TheSisb, but why is this not available in the README ?

**Comment by TheSisb** [comment]
Readme needs updating, but I don't have that access. I'm just a passerby.

**Comment by merraysy** [comment]
👍
