### ISSUE TITLE
[Question] CSS Modules should or shouldn't handle animation names?

### ISSUE THREAD

**Issue by kud** [css-modules/css-modules#225]
CSS modules is amazing in order not to be overrided by other libs or whatever, because it generates a unique class name for each element.

Well okay. But what about animation names?

Imagine I call an animation `@keyframes myAnimation` and another lib does the same, conflict, right?

So CSS Modules should or shouldn't handle animation names too?

Thanks.

**Comment by tivac** [comment]
From the first line in the [readme](https://github.com/css-modules/css-modules/blob/f989e7028cacc6e6813b326b5e35330c72a1cd32/README.md)

> A CSS Module is a CSS file in which all class names and animation names are scoped locally by default.

Animation names are already scoped.

**Comment by kud** [comment]
Interesting. Because when I tested it via webpack+hot-reload, I had my class classic name. But you're right.

Sorry for the noise. Thanks.
