### ISSUE TITLE
Using variables as css modules classnames.

### ISSUE THREAD

**Issue by gl2748** [css-modules/css-modules#226]
I am sure this has been answered elsewhere as it seems facile. Apologies for that.

Basically I have a react component and I would like to determine my classname with a variable (one of the props of the react component).

In the below example I have attempted to use a string literal like this:
```
<button className={Styles.`${props.buttonStyle}`}>
```
which obviously isn't working.

What's the best way to achieve this?

```js
import React from 'react'
import Styles from './styles.scss'

export const Button = (props) => {
  const typeo = 
  return (
    <div>
      <button className={Styles.`${props.buttonStyle}`}>
        {props.buttonText}
      </button>
    </div>
  )
}

Button.propTypes = {
  buttonType: React.PropTypes.string.isRequired,
  buttonStyle: React.PropTypes.string.isRequired,
  buttonText: React.PropTypes.string.isRequired
}
```

**Comment by joeybaker** [comment]
Looks like you're just accessing the property name incorrectly. 

Just change:

```js
Styles.`${props.buttonStyle}`
```

to:

```js
Styles[props.buttonStyle]
```

That should do it.

**Comment by gl2748** [comment]
Thanks, that is indeed working. For completeness this solution references: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer
For example to concat two prop values, for your style name:
`<button className={styles[props.buttonStyle]+[props.buttonType]}>`

**Comment by joeybaker** [comment]
You're very welcome.

Just clarify though. To contact two names together, things are a bit more complicated:

```js
className={`${styles[props.buttonStyle]} ${styles[props.buttonType]}`}
```

You need to separate each class with a space, and grab the properties off `style` each time.

You also might want to look at https://www.npmjs.com/package/classnames

**Comment by joeybaker** [comment]
@gl2748 if this answers your question, feel free to close the issue.
