### ISSUE TITLE
How do you write styling for generated content?

### ISSUE THREAD

**Issue by epavletic** [css-modules/css-modules#230]
So in this particular example, I have a Changelog.md that gets parsed via `markdown-loader` and its result gets injected into a React-component like this:

``` jsx
import changeLog from '../../../../CHANGELOG.md';
import styles from './ChangeLog.pcss';

const ChangeLog = () => (
  <div className={styles.changeLog} dangerouslySetInnerHTML={{__html: changeLog}}/>
);
```

The generated content has no classes on the individual nodes due to the way that `markdown-loader` (and markdown in general) works, but there is still a need to apply some styles to the changelog-content _without_ introducing truly global classes, i.e. I don't want to do a simple `@import 'global-styles-for-changelog'` in `ChangeLog.pcss` since that would give me REALLY global styles for `h2`, `h3` etc.

The result I hope I can achieve here is rather:
``` css
.-css-modules-generated-hash-for-changelog- h2 {…}
.-css-modules-generated-hash-for-changelog- h3 {…} 
.-css-modules-generated-hash-for-changelog- p {…}
// etc…
``` 
…so that the ”global” styles are stil scoped to that small part of my app and don't pollute the rest of the app.

Am I out of luck? I couldn't get it to work with `:global` but maybe I've been doing it wrong…

**Comment by ndresx** [comment]
This should be enough. You don't need `:global` for tags like `h2` or `p` in this case, but it should also work with it.
```
.changelog {
  h2 {}
}
```

**Comment by epavletic** [comment]
That's the thing – I felt like that would work, but it didn't (maybe something with my PostCSS-setup that screws something up though).

But I actually got it to work – the answer was (as it is in many cases) not to complicate things more than you have to:
``` css
.changeLog h2 {
  font-size: 1.6rem;
}

.changeLog p {
  margin-bottom: 1rem;
}
```
Looking at it, I can't believe I didn't try the easiest approach first. Sorry if I took up any of your time!

**Comment by ndresx** [comment]
@epavletic I was using `changelog` (like it is displayed in your example), but you have actually used `styles.changeLog` (capitalized L instead). I think this is the problem here.
