### ISSUE TITLE
when importing css file from node_modules with global, it's still importing it as local

### ISSUE THREAD

**Issue by idangozlan** [css-modules/css-modules#233]
```
:global {
    @import '/node_modules/react-select/dist/react-select.css';
}
```

It's generally working when im using `@import` from local (non node_modules) file. 

Is there anyway to force the global import? is that something on my webpack config?

my conf:
```
...
     {
        loader: 'style-loader'
      },
      {
        loader: 'css-loader',
        options: {
          modules: true,
          sourceMap: true,
          camelCase: true
          // localIdentName: '[path]__[local]__[hash:base64:5]',
        }
      },
      {
        loader: 'postcss-loader',
        options: {
          // sourceMap: 'inline',
        },
      },
      {
        loader: 'resolve-url-loader',
      },
      {
        loader: 'sass-loader',
        options: {
          sourceMap: true,
        },
      }
...
```

Using `webpack` v2.4.1 and `css-loader` v0.28.1

**Comment by tsargent** [comment]
I'm having the same problem, also with `react-select`

**Comment by TheSisb** [comment]
Don't import the CSS from a CSS Modules stylesheet file.  Import it from your JS.

i.e.:
```js
import '/node_modules/react-select/dist/react-select.css';
import Styles from './MyComponent.css';
```

Make sure your webpack config is set to load non-project css without css modules

**Comment by idangozlan** [comment]
Thanks @TheSisb for the work around, @TrySound why did you close the issue? it's a bug!

**Comment by TrySound** [comment]
It's not a bug. Because imports should be top level. And mode should be described by config and paths.

**Comment by idangozlan** [comment]
So are you saying that webpack users should not use import on scss file?!

**Comment by TrySound** [comment]
If this scss. Report should contain file after scss processing. Otherwise I can't help.

**Comment by pietrofxq** [comment]
If you want to import from CSS, you can setup your webpack to not parse with css modules files that end with .global.css. Then you can add all your imports there
