### ISSUE TITLE
Use PostCSS 6.0

### ISSUE THREAD

**Issue by ai** [css-modules/css-modules#235]
We released new major release for PostCSS with less dependencies and lower memory usage ([full changelog](https://github.com/postcss/postcss/releases/tag/6.0.0)).

@geelen @markdalgleish I think you just need to update dependencies and check warnings after tests. API changes are really small.

If you need any help, I could send PRs too.

**Comment by TrySound** [comment]
I can help with maintaining.

**Comment by ai** [comment]
@TrySound I wrote email to @geelen in case if project still have problems with response rate

**Comment by geelen** [comment]
Ok! All PRs merged and new minor version releases have been pushed to NPM. Thanks for prepping all the PRs, and apologies for being so absent on this project.

I've set up a new Gitter room where I'd like to discuss handing over maintenance of these repos to people with more time to dedicate to it. Please join and put your hand up if you'd like to be involved: https://gitter.im/css-modules/maintainers

**Comment by taion** [comment]
@geelen We actually had a Discord set up from https://github.com/css-modules/css-modules/issues/187#issuecomment-261071671 – might be easier just to keep using that?

**Comment by ai** [comment]
@geelen It was really fast. Thanks a lot.

**Comment by TrySound** [comment]
It's not quite ready. I'm stuck on windows tests passing in core loader.
