### ISSUE TITLE
Isn't scoped components in Vue.js similar to CSS Modules?

### ISSUE THREAD

**Issue by jitendravyas** [css-modules/css-modules#237]
https://egghead.io/lessons/vue-use-scoped-css-in-vue

I'm not sure if I would need CSS Module in Vue and it can do something different and useful than Vue's own Scoped CSS feature

**Comment by borela** [comment]
It is similar to Vue's scoped style but CSS modules don't require Vue and you can use it with SASS, LESS, Stylus etc...

**Comment by jitendravyas** [comment]
@borela So if I'm using Vue and don't need Sass, Less, Stylus then I think won't need CSS Module, Am I right? 

And there will be no Vue equivalent like this https://github.com/gajus/react-css-modules

**Comment by borela** [comment]
Yes, if there are no restrictions in your project and you want to go pure Vue, you probably won't need CSS modules.

**Comment by jitendravyas** [comment]
Vue also has support for CSS-Modules though I'm not sure what benefit it will have over vue's own scoping

https://vue-loader.vuejs.org/en/features/css-modules.html

**Comment by borela** [comment]
The only benefit is if you are importing a library that requires CSS modules. I believe that behind the scenes Vue is using PostCSS for the scoped feature which could make SASS, LESS and Stylus unnecessary too as the are many plugins for PostCSS that can give you all the features you would need in those libraries.
