### ISSUE TITLE
question: tilde selector

### ISSUE THREAD

**Issue by mendrik** [css-modules/css-modules#244]
hi how do I reference a local class in the pcss file

```
.myclass {

   &.selected ~ .myclass {
   }
}
```
should that be `&.selected ~ :local(.myclass)`  or something?

**Comment by TrySound** [comment]
With local enabled by default you don't need `:local` modifier. Do you have any problem with it?

**Comment by mendrik** [comment]
ok let me check, there is also a high chance of the problem being between keyboard and chair here. thanks for the fast reply

**Comment by mendrik** [comment]
I'm sorry turns out it works out of the box,  just had forgotten to use styles.selected in my component
