### ISSUE TITLE
Deciding when to use the global scope

### ISSUE THREAD

**Issue by tomprats** [css-modules/css-modules#249]
I'm new to css-modules but I've been reading and trying to understand what's going on in the specific implementations as well as the general ideology.

I think I found a use-case that might be helpful to further document. I was hoping a developer with more css-modules experience could offer some insight [here](https://stackoverflow.com/questions/44640925/how-can-i-use-css-modules-local-selectors-in-multiple-components).

At this point I'm not sure if there's a clean solution. If there isn't, it might be helpful to show when using global class names may still be necessary.

**Comment by TrySound** [comment]
In other words you want to use local class from one file as a child of local class name in another file?

**Comment by tomprats** [comment]
I think that's pretty close. I think the complication is that I want to use a local class from one file as a child of 1 of 2 local class from elsewhere.

I think this example explains it better than I can

```
.horizontal-form {
  .form-field {
    // ...
  }
}
.vertical-form {
  .form-field {
    // ...
  }
}
```

So a form would be either horizontal or vertical, and the `form-field` inside would be styled based on which form it was nested under.

**Comment by TrySound** [comment]
This works as well
```
.form-field {}
.horizontal-form {
  .form-field {
    // ...
  }
}
.vertical-form {
  .form-field {
    // ...
  }
}
```

This will work in the next version which I develop right now.
```css
@value form-field from './form-field.css';
.horizontal-form {
  .form-field {
    // ...
  }
}
.vertical-form {
  .form-field {
    // ...
  }
}
```

**Comment by tomprats** [comment]
What if the two forms are in different files? Would you do something like this?

```
@value formField from './form-field.css';
.horizontalForm {
  .formField {
    // ...
  }
}
```

```
@value formField from './form-field.css';
.verticalForm {
  .formField {
    // ...
  }
}
```

Would that give each form the same identifier for `formField`. So I could use it with:

```
import styles from "./form-field.css";

formElement.innerHTML = '<div class="' + styles.formField + '">';
```

PS: Thanks for your help!

**Comment by TrySound** [comment]
@tomprats Yep. css-modules has single instance like es-modules. But keep in mind that it doesn't work well until we release new version of css-loader (or whatever you use).

**Comment by tomprats** [comment]
Awesome! I'll keep my eye out for that. Thanks again for your help
