### ISSUE TITLE
-webkit-box-orient removed from css

### ISSUE THREAD

**Issue by freynolds** [css-modules/css-modules#253]
Hi y'all, thanks for reading this.
I'm trying to use -webkit-line-clamp for a test and found that the following code
```
.Abstract {
    width: 120px;
    overflow: hidden;
    display: -webkit-box;
    -webkit-line-clamp: 3;
    -webkit-box-orient: vertical;
}
```

Ends up compiled like the following

```
.style__Abstract___1dnxi {
    width: 120px;
    overflow: hidden;
    display: -webkit-box;
    -webkit-line-clamp: 3;
}
```

`-webkit-box-orient: vertical;`

gets discarded.

I'm going to use a different route, since this is webkit only, but wanted to post this here so this finding might help someone.

My regards
Francisco.

**Comment by TrySound** [comment]
css-loader uses cssnano under the hood, which is uses autoprefixer to remove dead prefixes according global configuration (browserlist)

**Comment by freynolds** [comment]
Thank you for your response!
