### ISSUE TITLE
how to handle css  from node_modules 

### ISSUE THREAD

**Issue by wuyalingo** [css-modules/css-modules#254]
First, my english is poor.
I have a problem, i imported a react component from node_moduels that has owner css and react components, the way likes:
<Button type="primary"/>
I mustn't add className property,so now i can how to use css-modules to it

**Comment by TrySound** [comment]
@wuyalingo If I understand you correctly, using webpack you can add `exclude: /node_modules/` to your `css-loader` rule.

**Comment by wuyalingo** [comment]
@TrySound  First, thank you for your reply. I already  solve it as you say!
