### ISSUE TITLE
less functions error in css module

### ISSUE THREAD

**Issue by echosoar** [css-modules/css-modules#256]
.fun_back(@link) {
    background: url(@link) no-repeat center/contain;
}

body {
    .fun_back("https://i.loli.net/2017/08/01/598049c65da03.png");
}

**Comment by TrySound** [comment]
Show your config

**Comment by echosoar** [comment]
{test  : /\.less$/, loaders: ['style-loader', 'css-loader?modules&localIdentName=[name]__[local]-[hash:base64:5]', 'less-loader', 'postcss-loader']}

**Comment by echosoar** [comment]
`
{	
    test  : /\.less$/, 
    loaders: ['style-loader', 'css-loader?modules&localIdentName=[name]__[local]-[hash:base64:5]', 'less-loader', 'postcss-loader']
}`

**Comment by TrySound** [comment]
@echosoar It's an error in postcss-loader. You should pass it after less loader
```js
{
    test  : /\.less$/, 
    loaders: [
      'style-loader',
      'css-loader?modules&localIdentName=[name]__[local]-[hash:base64:5]',
      'postcss-loader',
      'less-loader'
    ]
}
```
