### ISSUE TITLE
Add Examples, maybe a spec

### ISSUE THREAD

**Issue by jasonLaster** [css-modules/css-modules#26]
The blog post shares lots of examples that are not in the documentation:

http://glenmaddern.com/articles/css-modules

It'd be great if the documentation outlined a full list of supported features. It'd be better if there were a formal way of expressing the functionality.

---

I'm not sure if the place for this is in another markdown file or more examples...

**Comment by serapath** [comment]
+1, especially i'd like to see pure javascript example, that do not use some kind of bigger framework or libraries that very essentially change the way you write your code (e.g. React)

**Comment by joshwnj** [comment]
@serapath I made some very simple examples that use browserify and plain js, maybe they could be useful? https://github.com/x-team/starting-css-modules

Also if there are things you think would be good to demonstrate that aren't included in these examples, please let me know

**Comment by leerob** [comment]
Added a bunch here: https://github.com/css-modules/css-modules/blob/master/docs/get-started.md
