### ISSUE TITLE
Composing from global selector (or arbitrary string)

### ISSUE THREAD

**Issue by juanca** [css-modules/css-modules#267]
# Motivation

I have some server-side rendered stylesheets (for historical reasons) which expose non-modularized class names. As I'm migrating to modules, I am trying to use CSS composition to declare my dependencies across my stylesheets. Being able to declare dependencies to my global class names would facilitate my migration (and even further exemplify the amazingness of CSS composition!)

# Example

I have a component which consumes the following stylesheet:

```
.input {
  composes: basic-input from './styleguide/input.css'
  border-color: grey;
}
```

At the moment, the input adds its styling and an additional classname:

```
import styles from './styles.css';

export default function Input(props) {
  return <input className={`${styles.input} global-input`} />
}
```

# Ideal example

```
.input {
  composes: basic-input from './styleguide/input.css';
  composes: :global(global-input);
  border-color: grey;
}
```

```
import styles from './styles.css';

export default function Input(props) {
  return <input className={styles.input} />
}
```

This would help encapsulate the styling responsibilities to the stylesheet.

Is there a way to do this right now? Or would it even qualify as a new feature?

**Comment by juanca** [comment]
So, there is undocumented (?) support for this:

```
composes: foo from global;
```

does the trick.

Should this be documented? I can make a PR but I'm not sure if it's desired.

**Comment by TrySound** [comment]
@juanca Sure. In this repo, please.

**Comment by juanca** [comment]
Appreciate the response. Went ahead with the changes. Will close this.
