### ISSUE TITLE
Add compile-time error if duplicate properties are composed

### ISSUE THREAD

**Issue by garetht** [css-modules/css-modules#28]
As the [readme notes](https://github.com/css-modules/css-modules#dependencies), if there are duplicate properties from compositions the order of application is undefined. In addition, the silent overriding of properties would seem to introduce hard problems of debugging if multiple identical properties are composed together even if they happened to be in the right order. Adding a compile-time error, or an option to enable a compile-time error, when multiple identical properties are composed would seem to help to alleviate these problems.

**Comment by geelen** [comment]
Hmm, the order isn't exactly undefined, it's totally deterministic, but driven on the order in which certain dependencies are encountered. This issue has a more detailed discussion on the topic: https://github.com/css-modules/css-modules/issues/12 (particularly my response at the end)

I definitely see where you're coming from, though. There's a few stylistic things that aren't _technically_ errors but are unadvisable like using tag or other global selectors without the `:global` syntax. Initially we were throwing an exception, but it was too abrupt to people porting their code. What I think we'd like to do is start a **css-modules-lint** project that checks for these higher-level errors.

What do you think?

**Comment by garetht** [comment]
Ah got it. I think the readme might need to be updated. The primary motivation for this is the thought that one of the large benefits of local scoping is the prevention of accidental cascading from namespace clashes. To do this requires quite a bit of discipline with regards to naming. In introducing a set of tools to all but eliminate namespacing bugs, however, a [new discipline is now needed](https://github.com/css-modules/css-modules/issues/12#issuecomment-113937851) in creating composable modules. While more tractable, the maintenance of this new discipline is as prone to error as preventing namespace clashes, which formal verification methods should be able to solve. A linter sounds like a great idea to help solve this problem.
