### ISSUE TITLE
@import files don't worked

### ISSUE THREAD

**Issue by goonwzz** [css-modules/css-modules#281]
file: globle.lessm
.width-1200() {
  width: 1200px;
  margin: 0 auto;
}
@custom-info-color: #00A990;

file:__globle.lessm
@improt './globle.lessm'
@custom-success-color: #87d068;

cssfile: index.lessm
@improt './__globle.lessm'
.index{
  clolr:@custom-info-color;// error @custom-info-color is undefined
 .width-1200()//error undefined
}

my webpack.config

  {
        test: /\.lessm$/,
        //css-modules name=文件名 local--样式名 hash:base64:8 hash8
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: 'css-loader?modules&localIdentName=[name]--[local]--[hash:base64:8]!less-loader',
        })
      },

node 9.2.0
webpack 2.6.1

**Comment by TheSisb** [comment]
Sounds like a postcss config/plugin issue?
