### ISSUE TITLE
HOC

### ISSUE THREAD

**Issue by 951759534** [css-modules/css-modules#284]

**Comment by 951759534** [comment]
HOC and CSSModule  used for a same Component with Decorator
display a error   
React does not recognize the `styleName` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `stylename` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**Comment by TrySound** [comment]
I guess it's [react-css-modules](https://www.npmjs.com/package/react-css-modules) issue

**Comment by 951759534** [comment]
yeah you are right  
I change to react-css-modules to submit my issue
