### ISSUE TITLE
dose this supprt nest style?

### ISSUE THREAD

**Issue by walker-jiang** [css-modules/css-modules#302]
dose this supprt nest style?
like this:
   `
.small {
      .antCheckbox {
          margin-right: 5px;
      }
   }
`
in component: 
`
import CheckboxStyle from 'components/antd/style/checkbox.scss'; 
<Checkbox  className={CheckboxStyle.small} /> </Checkbox>
`
style dose not work, hope for help,thanks.

**Comment by leerob** [comment]
Hey, here from the future! Where CSS nesting is supported cross browser. What a time to be alive.

https://caniuse.com/css-nesting
