### ISSUE TITLE
Lost specificity when using localIdentName format of [sha1:hash:hex:5]?

### ISSUE THREAD

**Issue by rdalfonso** [css-modules/css-modules#325]
Has anyone else had an issue with lost specificity when using the obfuscated format [sha1:hash:hex:5]? My development environments works fine when using [name]__[local]___[hash:base64:5]. The minute I build in production with [sha1:hash:hex:5] certain styles get overridden by parent selectors and/or lose specificity. What gives? It's the same SASS code, same webpack compilation with [name]__[local]___[hash:base64:5]. 

Anyone else have this issue?

**Comment by merksam** [comment]
I have the same issue too. Have you resolved it?
