### ISSUE TITLE
inline css modules

### ISSUE THREAD

**Issue by andykais** [css-modules/css-modules#338]
I just had an interesting idea I wanted to share. Ive been looking at svelte recently and I really like how it re-encapsulates css and markup in the same file. E.g.
```svelte
<script>
  export let items = ['milk', 'eggs', 'flour']
</script>

<style>
.item {
  background-color: red;
}
</style>

<h1>Shopping list</h1>
<ul>
  {#each items as item}
    <li class='item'>{item}</li>
  {/each}
</ul>
```

Id love to apply that idea to css modules & react (or any other framework where js is the module). What I am imagining is something like this:
```jsx
import { csm } from 'css-modules-inline'

const styles = csm`
.item {
  background-color: red;
}
`
export const ShoppingList = ({ items }) => {
  return <>
    <h1>Shopping List</h1>
    <ul>{items.map(item =>
        <li className={styles.item}>{item}</li>)
    }</ul>
  </>
}
```

Does this seem useful to anyone else? I imagine I could hack this together if I can convince webpack/babel that the `styles` string is actually an import.

**Comment by tivac** [comment]
This proposal looks a lot like what [`astroturf`](https://github.com/4Catalyzer/astroturf) does?

**Comment by andykais** [comment]
thanks! That appears to be what I was looking for.
