### ISSUE TITLE
Apologies

### ISSUE THREAD

**Issue by peduarte** [css-modules/css-modules#34]
I'd like to apologise for my behaviour when raising #32.

I expressed my frustration in a rather aggressive way but in no way I meant to disrespect the project or the authors.

I love the idea of css-modules, being primarily a presentation developer, I always try out whatever is new in the CSS world.

I guess that with the vast amount of new frameworks coming out every day, it's hard to keep up, and I felt cheated when such a basic behaviour wasn't documented clearly. Regardless, I shouldn't have expressed this in the way that I did.

So on that note, @geelen, @nkbt, @henriquea and anyone whom I may have offended, please accept my apologies.

🙏

**Comment by henriquea** [comment]
Nice one @peduarte it's easy to offend but just a few assume your own mistakes and ask sorry publicly 👌🏼

**Comment by geelen** [comment]
Thanks for this @peduarte. It takes a lot of integrity to apologise publicly in this manner, and I really appreciate your doing so. I fully accept your apology and consider the matter resolved.

I hope you find CSS Modules a useful project and you should feel welcome submitting issues or contributing discussion or code from here on.

Many thanks. :open_hands:

**Comment by nkbt** [comment]
Thank you @peduarte <https://github.com/peduarte> :+1:
