### ISSUE TITLE
What would be the best way to use with Angular.js (1.x) ?

### ISSUE THREAD

**Issue by fabm22** [css-modules/css-modules#35]
Hi,

With the given example in mind (https://github.com/css-modules/webpack-demo) and without speculating into Angular 2.0 territory, what would be the best way to incorporate CSS modules with webpack use to a AngularJS app ?? 

Systematically using directives only when using Modules CSS for example ?

Thanks for help

**Comment by nkbt** [comment]
We do it in our project. Works well. Will give some examples later when at
my computer.

**Comment by fabm22** [comment]
Hi, please do, yes, I would really appreciate it @nkbt

**Comment by nkbt** [comment]
@fabm22 check out this little hello-world demo https://github.com/nkbt/ng-modular

Here is an example of this kind of directive https://github.com/nkbt/ng-modular/blob/gh-pages/src/hello/hello_directive.js

**Comment by geelen** [comment]
This is great @nkbt! @fabm22, if that answers your question, would you mind closing this issue?

**Comment by fabm22** [comment]
This does answer it. Please do thanks!

**Comment by mikeerickson** [comment]
@nkbt Thanks for posting this, even though it was many months ago.  Always good to find nuggets like this searching to examples on how others have done things.

**Comment by nkbt** [comment]
@mikeerickson :ok_hand:
