### ISSUE TITLE
How can I not obfuscate class names in development mode?

### ISSUE THREAD

**Issue by atav32** [css-modules/css-modules#350]
The class name obfuscation is really useful for avoiding collisions, but makes debugging a lot harder.

Is there a way to configure CSS Modules to preserve some part of the original class name during development mode?

(Sorry if this is already answered somewhere, but I searched around and couldn't find anything obvious.)

**Comment by tivac** [comment]
Looks like the webpack css-loader supports it using [`localIdentName`](https://github.com/webpack-contrib/css-loader#localidentname)?

**Comment by atav32** [comment]
@tivac 💯  thanks!

**Comment by n4j1Br4ch1D** [comment]
Check out this postcss plugin:
https://www.npmjs.com/package/postcss-obfuscator
