### ISSUE TITLE
dark class tailwindcss not work

### ISSUE THREAD

**Issue by webtinax** [css-modules/css-modules#360]
hi 
dark mode not work when use in xxx.module.scss 
please help : 

[https://github.com/tailwindlabs/tailwindcss/issues/3258](url)

**Comment by Capati** [comment]
Hi. Have you managed to fix?

**Comment by leerob** [comment]
Closing as stale, but I am guessing this has been resolved on the Tailwind side (I haven't ever ran into it). Let me know if it's still an issue for you.
