### ISSUE TITLE
:global is confusing

### ISSUE THREAD

**Issue by martpet** [css-modules/css-modules#369]
I had a discussion with coworkers whether we should use `:global` at all.

In xyz.module.scss:
```
.foo {
  :global(.bar) {}
}
```
They believe `.bar` would escape from the ancestor as if a Sass `@at-root` rule were used.

They pointed me to the docs:

> :global switches to global scope for the current selector respective identifier.

It didn't clear the confusion, and we removed all "globals" from our CSS modules.

I suggest an alias is added, such as `:unprefixed`.

**Comment by hennii** [comment]
I see you closed this but I 💯 agree that `:global` invokes the mental model of `@at-root` rather than "not-prefixed".
