### ISSUE TITLE
Best Approach / Example For Use In MeteorJs

### ISSUE THREAD

**Issue by edolyne** [css-modules/css-modules#37]
Hi, I had noticed that you have some example projects built, and was wondering if one for Meteor is a possibility.  The meteor community is great, and I think with the many advantages of Meteor that CSS Modules, along with a Spacebars(Handlebars) integration it would be a great fit.  Thanks for any help.

**Comment by joshwnj** [comment]
Hi @edolyne I'm not aware of any existing examples, how would you like to make the first? :) very happy to help if you have any questions along the way

**Comment by nathantreid** [comment]
@edolyne, I've created a meteor build plugin for CSS Modules: [nathantreid:css-modules](https://github.com/nathantreid/meteor-css-modules).
