### ISSUE TITLE
Recommended way to "extend" native HTML elements

### ISSUE THREAD

**Issue by fabm22** [css-modules/css-modules#38]
Hope I don't act as stupid by doing so but I repost here the question above asked by another user as we are invited by repo maintainer at end of the now closed (for non question itself related reasons) issue thread. 
( https://github.com/css-modules/css-modules/issues/32)

----

"I've been experimenting with css-modules and came across an issue to which I found no sensible solution for.

I would like to know how I can create variables with css-modules and re-use them across my CSS components. I am aware that the workflow with css-modules is a little different than with Sass/Less, but take this as an example:

The sass way
```sass
// variables
$size-small: 0.8em;
$color-faded: #eee;

// rules
small {
  font-size: $size-small;
}

footer p {
  color: $color-faded;
}
```
css-modules way... well, what I tried anyway
```sass
// typography.css
.small {
  font-size: 0.8em;
}

// colors.css
.faded {
  color: #eee;
}

// rules
small {
  composes: small from 'typography.css';
}

footer p {
  composes: faded from 'colors.css';
}
```
But we cannot use composes in native HTML elements.

What am I missing here?
Maybe I am approaching this the wrong way?

If the solution is to add a class to every element, then... goodbye css-modules 👋

Any advice, recommendation or insults will be very helpful.

👊"

**Comment by joshwnj** [comment]
Hi @fabm22, for context can you please tell us a little about your use case? Would you describe it more as "web site" or "web app"?

**Comment by geelen** [comment]
There is another issue that picked up that discussion, https://github.com/css-modules/css-modules/issues/33, so maybe add your comments there?

**Comment by fabm22** [comment]
Thanks for the heads up
