### ISSUE TITLE
Late styles loading in Next 13

### ISSUE THREAD

**Issue by Wojtazzzz** [css-modules/css-modules#385]
### **Problem**
CSS Modules styles are fetched and loaded after page rendered. Error appears only on first subpage visit, on every subpage.

### **Example**
Open https://polskifrontend-cmx8dv3pq-typeofweb.vercel.app/ and click `O SERWISIE` in the top navigation. As you can see main container has 100% width, then styles are loaded and container has correct width.

### **Versions**

- NextJS 13.1.1
- React 18.2.0

**Comment by su-pull** [comment]
It was reproduced in my environment as well. 
Specifically, it only occurs on the page where I am doing SSG with CSS Modules. I have decided to use styled-jsx and Next.js version 13 to address this issue.

**Comment by leerob** [comment]
Hey! If you are still seeing this, could you open an issue in Next.js? It's been a bit but I am guessing this is resolved on the latest version by now. If not, happy to look into it. Thank you!

**Comment by najeebputhiyallam** [comment]
i have same issue. i posted to next.js but no one replying.

https://github.com/orgs/vercel/discussions/6618
