### ISSUE TITLE
typo in https://github.com/css-modules/css-modules/blob/master/docs/local-scope.md

### ISSUE THREAD

**Issue by jakubkloc** [css-modules/css-modules#389]
![image](https://user-images.githubusercontent.com/99250816/230571433-b9d2cadf-c57a-429c-a0e7-06fa56b71077.png)
In code are : ```backdrop, prompt, pullquote``` but in text are the classes ```backdrop, field, pullquote```

**Comment by leerob** [comment]
Fixed!
