### ISSUE TITLE
Question: Inconsistent rule global/local

### ISSUE THREAD

**Issue by st32lthx** [css-modules/css-modules#39]
I am using a grid that was written in sass and trying to use it but not sure if I am using css-module correctly. I am getting the following error:

> Inconsistent rule global/local result in rule '.l-wrap:before, :global .wrap:before, .l-wrap:after, :global .wrap:after' (multiple selectors must result in the same mode for the rule)

I know it is hard to tell without knowing the grid, but this is how I am using it:

```
@import "~grid/grid";
:global {
  .wrap { @include l-wrap }
}
```

I would like to make the `.wrap` class globally accessible. It works if I don't include the `global`.

Below is the relevant line in the webpack config:

`{ test: /\.scss$/, loader: ExtractTextPlugin.extract('style-loader', 'css?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!sass') }`

 Would appreciate any pointers.

**Comment by geelen** [comment]
Aha, right, yes. This looks like a problem with Sass & CSS Modules conflicting. Your mixin is adding `:before` and `:after` selectors, but for some reason not putting `:global` in front of all of them.

Try this and see if the error is any different:

```scss
:global(.wrap) {
  @include l-wrap;
}
```

A definite (although less nice) fix would be to put all your globals in a single file/directory and use webpack's config to only use `?modules` on the ones without globals. But try the above suggestion first.

**Comment by aminmeyghani** [comment]
Awesome, `:global(.wrap) { ... } ` worked like a charm. Thanks !
