### ISSUE TITLE
 How pseudo class :global should work？

### ISSUE THREAD

**Issue by suxin2017** [css-modules/css-modules#395]
```
//input
.a:global{}
```
Which of the following should be the output

```
.__local__a{}
```
or
```
.__local__a:glob{}
```

**Comment by pascalduez** [comment]
Hello,

the global syntax is the following:

```
:global(. foo) { ... }
```
Or
```
:global . foo { ... }
```

But the syntax without braces is not necessarily supported by all CSS modules implementations.

Which should output the class unmodified, so `.foo { ... }`.
