### ISSUE TITLE
composes with absolute path

### ISSUE THREAD

**Issue by nsisodiya** [css-modules/css-modules#44]
``` css
    composes: redBackground from "../../../../css/common/style.css";
```

I am using react-css-module.
this path is working file but If I change the location of file, I need to recalculate path again. It is possible to give absolute path ??
Life will be easy.

**Comment by sokra** [comment]
The same rules as with normal `require`s or `import`s apply: you can use `resolve.alias`, `resolve.root` or a modules folder (either `web_modules` or a custom one added to `resolve.modulesDirectories`). see configuration documentation page.
