### ISSUE TITLE
import class as local classes

### ISSUE THREAD

**Issue by nsisodiya** [css-modules/css-modules#46]
it is possible to have this kind of behaviour ?
https://github.com/gajus/react-css-modules/issues/17

**Comment by nsisodiya** [comment]
I have defined 
`style.css` like
```
.font-lg {
    font-size:large;
}
.rfloat {
    float:left;
}
```
now, i am using this class in my 
`HelloComponent.css` like this

```
.rfloat {
    composes: rfloat from '../../../../css/common/style.css';
}
.font-lg {
    composes: font-lg from '../../../../css/common/style.css';
}
.saveBtn {
      //CSS for save button
}
```
is it possible to do this kind of operations in 
`HelloComponent.css` 
```
import rfloat, font-lg from '../../../../css/common/style.css';
.saveBtn {
      //CSS for save button
}
```

**Comment by NekR** [comment]
@nsisodiya see this: https://github.com/css-modules/css-modules/issues/25

**Comment by geelen** [comment]
Covered by https://github.com/css-modules/css-modules-loader-core/pull/28
