### ISSUE TITLE
Composes with global class name

### ISSUE THREAD

**Issue by juanluispaz** [css-modules/css-modules#49]
Composes is really useful, but when I work with a shared css, sometimes, I need to compose with a global class name, but currently it is not allowed.

There is two variants:
1.- Compose with an global external class name, e.g.: from a shared css library.
2.- Compose with a global local class name. It is less useful, It currently doesn't work too, but actually I don't need this kind of functionality.

Thanks for all.

**Comment by dubert** [comment]
:+1:

YES THIS. I need this.

**Comment by tslocke** [comment]
:+1:

I'd like this not for names from a library but for global classes from my own project.

It's a pretty interesting use-case, but would take a fair bit of describing. I was getting ready to write up the argument but saw, to my surprise, this issue already here : )

If folks are curious as to how I want to use this, I'll write it up.

In the mean time, I figured out a juicy hack to make this work now. I declare the class twice - one local, with no declarations inside, which I can use in `composes`, and one global, with all the declarations. I then hack the imported JS object -- using a regex to replace the local name with the global one. Works great, and doesn't pollute my code too badly.

**Comment by geelen** [comment]
Implementing this now, how's this syntax:

```css
composes: foo bar baz from global;
composes: something-else from "somewhere-else.css";
```

Ok?

**Comment by tslocke** [comment]
+1

**Comment by dubert** [comment]
@geelen looks good!

**Comment by bcomnes** [comment]
> ```css
composes: foo bar baz from global;
composes: something-else from "somewhere-else.css";
```

Seems to be working!  Should this get documented in the README?

**Comment by juanluispaz** [comment]
It looks good! Thanks!

**Comment by geelen** [comment]
Oh hey this should be closed! We're just finishing up documentation to tell everyone about this & `@values` and calling 1.0 done!

**Comment by ctaepper** [comment]
is this working? i don't see any documentation of this?

**Comment by nielk** [comment]
I'm currently using the `composes: className from global;` but I don't see any documentation on this. Is this syntax always be available?

**Comment by Avivhdr** [comment]
Hi @geelen 
Do you know what's wrong with the following piece of code?
it doesn't work.

```
/* style.css */
:global .globalText {
  color: green;
}
```

```
/* otherStyle.css */
.text {
  composes: globalText from "../2-GlobalSelectors/GlobalSelectors.css"; 
  background-color: #777;
}
```

This doesn't works as well (error in compilation):
```
/* otherStyle.css */
.text {
  composes: globalText from global;
  background-color: #777;
}
```

**Comment by graingert** [comment]
@nielk documented here: https://github.com/css-modules/css-modules#composing-from-global-class-names
