### ISSUE TITLE
Debugging tips

### ISSUE THREAD

**Issue by yoni-tock** [css-modules/css-modules#53]
Hey there,

I'm using css-modules right now with webpack and css-loader and style-loader and the one big pain point we're having is it's hard to go from looking at a browser to finding the class definition. The mangled names make it hard to backtrace where the css is coming from. Are you familiar with a "sourcemaps" mode or a debug mode that includes the original name in the mangled name? Any pointers here would be great!

**Comment by crysislinux** [comment]
Agree, sourcemap is definitely needed for debugging.

**Comment by geelen** [comment]
I'd like to see source maps as well, but changing the generated class names is usually sufficient to figure out what's going on. If you're using webpack's css-loader, the README has information about how to configure those names in the "Local Scope" section: https://github.com/webpack/css-loader#local-scope

**Comment by yoni-tock** [comment]
w00t! This totally worked for me. For anyone who finds this my loader is

```js
{
      test: /\.scss$/,
      loader: 'style!css?modules&localIdentName=[path][name]---[local]---[hash:base64:5]!sass?sourceMap'
}
```
