### ISSUE TITLE
Isomorphic support

### ISSUE THREAD

**Issue by empaempa** [css-modules/css-modules#56]
We're writing an isomorphic app and would love to use CSS Modules but the import of styles doesn't really work server side. Is there any plan for this or an idea on how to solve this?

**Comment by markdalgleish** [comment]
Webpack can compile for Node, not just the browser. If you're building an isomorphic app with CSS Modules, it's recommended that you use Webpack for both. This is what I'm doing on a current project at work and it's working out really well.

@jlongster wrote a really great series of blog posts that explain how to set this up:

[Backend Apps with Webpack (Part I)](http://jlongster.com/Backend-Apps-with-Webpack--Part-I)

[Backend Apps with Webpack (Part II)](http://jlongster.com/Backend-Apps-with-Webpack--Part-II)

[Backend Apps with Webpack (Part III)](http://jlongster.com/Backend-Apps-with-Webpack--Part-III)
