### ISSUE TITLE
Best Practices structuring composable classes?

### ISSUE THREAD

**Issue by andreasklinger** [css-modules/css-modules#57]
Hi 

Are there currently best practices around how to structure composable classes without those becoming a huge pile + mess?

I am looking for:
- when/where to cut and dice
- how to bundle 
- how to name
- how to structure directories
- where to accept duplication / where not
- what to avoid 
  - eg there is a strong movement against variables
    - how does the alternative pattern look like (in reality - eg if you have the color used for 20 things)
- etc

Just to make sure… ;)
"The beauty is you can do everything as you like" is not a useful answer atm. ;)
No doubt we will still adapt to own needs, but i would love to hear if there are already lessons learned by others.

Thanks a ton in advance!

**Comment by ctaepper** [comment]
i'm in for it too

if i have
```js
// margins.css
.large-margin {
  margin: 20px
}
```
and 
```js
// paddings.css
.large-padding {
  padding: 20px
}
```
is there a way to bundle these files?
so i can use it for an actual module like this
```js
// module.css
.box {
  composes large-padding, large-margin from 'bundle.css';
}
```

**Comment by geelen** [comment]
Actually, `@value` makes that possible:

``css
/* margins.css */
.large {
  margin: 20px
}
```
and 
```css
/* paddings.css */
.large {
  padding: 20px
}
```

```css
/* bundle.css */
@value large as large-padding from "./padding.css";
@value large as large-margin from "./margin.css";
```

```css
/* module.css */
.box {
  composes: large-padding, large-margin from 'bundle.css';
}
```

This works because every `@value` exports itself.

As for @andreasklinger's original question, I think a good example project (as being asked for in https://github.com/css-modules/css-modules/issues/72) will go a long way to helping provide some guidance there.
