### ISSUE TITLE
Question: how too use both global and local css?

### ISSUE THREAD

**Issue by lapanoid** [css-modules/css-modules#59]
Css modules are awesome, and I hope that people will soon use it and kill global css. But we have global css everywhere and I not sure how to use them both in one project.
Now I have this
```
{
      test: /\.less$/,
      loader: 'style!css?modules&importLoaders=2&sourceMap&localIdentName=[local]___[hash:base64:5]!less'
})
```
```
{
      test: /\.less$/,
      loader: 'style!css!less'
})
```
what I want is 
```
require('bootstrap.less')
var localstyle = require('mylocal.less')
```
worked somehow together
Any ideas?

**Comment by andreypopp** [comment]
@lapanoid I ended up using `.module.css` extension for CSS modules so I can apply `css-loader?modules` only for those.

**Comment by lapanoid** [comment]
@andreypopp Thanks! I guess this is my only option for now

**Comment by sokra** [comment]
You can configure the css-loader multiple times in the config. Just make sure that only one of them match. See module.loaders documentation `include`, `exclude`.

**Comment by sokra** [comment]
You can use an array for xor in module.loaders.

Example:

```
loaders: [
[
{
      test: /\.less$/,
      include: path.resolve(__dirname, "app"),
      loader: 'style!css?modules&importLoaders=2&sourceMap&localIdentName=[local]___[hash:base64:5]!less'
},
{
      test: /\.less$/,
      loader: 'style!css!less'
}
],
...
]
```

**Comment by lapanoid** [comment]
@sokra Yes I currently do that. I just thought if there is any other option. I'd like too be able to choose between loaders like require('global!file.less') I thought I can make some magic with loader alias but it seems that I cannot alias composition of loaders like style!css!less.

**Comment by andreypopp** [comment]
@lapanoid you can write a loader which function as an "alias" for a chain of loaders if you want.

**Comment by lapanoid** [comment]
I also made regexp to solve some issues when two loaders collides, so final version is this.

```
{
      test: /\.module.less$/,
      loader: 'style-loader!css-loader?modules&importLoaders=2&sourceMap&localIdentName=[local]___[hash:base64:5]!less-loader',
      include: [/topico-content/, /topico-styles/]
}
{
      test: /^((?!\.module).)*less$/,
      loader: 'style!css!less'
}
```

**Comment by chentsulin** [comment]
It's great if we can document a suggested approach about how to work with non-module css files.

**Comment by lapanoid** [comment]
I think this approach is better ```require('local!somefile.less')``` but it requires "loader composer" that

**Comment by lapanoid** [comment]
@andreypopp @chentsulin @sokra Please let's continue discussion here - https://github.com/css-modules/css-modules/pull/65.
