### ISSUE TITLE
The Purpose Of `CSS Modules`

### ISSUE THREAD

**Issue by serapath** [css-modules/css-modules#6]
#### JSS
> **Develop a convention for ensuring globally-unique selectors**

* [https://medium.com/@oleg008/the-important-parts-131dda7f6f6f][medium]
* [https://github.com/jsstyles/jss#composable-and-reusable-style-sheets][jss]

=> [`JSS`][jss] is generating [`CSS-Class-Prefixes`][medium]
[medium]: https://medium.com/@oleg008/the-important-parts-131dda7f6f6f (medium blog entry)
[jss]: https://github.com/jsstyles/jss#composable-and-reusable-style-sheets (JSS)

### atomify-css

* [https://github.com/atomify/atomify-css][atomifycss]

=> In `package.json`, define a `"style":...` property, that points to the `entry css file` of a component

[atomifycss]: https://github.com/atomify/atomify-css (Atomify CSS)

### Final Thought

Maybe it's worth communicating with the authors of those packages to brainstorm about a convention. If `JSS` generated prefixes would be combined with a standard way of export like in `atomify-css`, a convention could be agreed upon and implemented and spread :-)

**Comment by serapath** [comment]
Currently, I have a lot of projects that look similar to:

Given:
* `projectName/`
  * index.css
  * index.js
  * index.template.html

```js
  // [index.js]
  var template  = require('./index.template.html');
  var __        = document.createElement('div');
  
  module.exports = function projectName (parameter) {
  
    var arguments       = {};
    arguments.container = parameter.dom     || document.body;
    arguments.title     = parameter.title   || "Hello World";
    arguments.message   = parameter.message || "Welcome to components";

    var component = (__.innerHTML=template;__.querySelector('.projectName'));
    var __title   = component.querySelector('.projectName__title');
    var __message = component.querySelector('.projectName__message');
    
    __title.innerHTML   = arguments.title;
    __message.innerHTML = arguments.message;
    arguments.container.appendChild(component);
  }

```

I handle modular CSS by using `atomify`, but it requires manual discipline to namespace the css via BEM conventions, as you can see above from the `querySelectors` I use.

**Comment by geelen** [comment]
Yeah, the manual BEM discipline is what we're trying to avoid. CSS Modules does so by randomly generating classes in the CSS then passing them to JS, the opposite could work as well.

I think the key difference between the approaches you've described are that CSS Modules is very much a "CSS First" idea — we should continue to write CSS, but add some cleverness around what CSS is actually being generated and how it's used. JSS and other CSS-in-JS approaches seem to take the opposite approach, and so I don't quite understand what kind of "convention" might make sense between the two. Happy to be better-informed here.

As for atomify, I think it's too tied to the file system to be integrated. CSS Modules depends upon and offloads work to the loader (Webpack, JSPM, Browserify), so it's totally ignorant of where the files are coming from (over the network in JSPM, the file system in the other two). In fact, it allows us to simply define a series of PostCSS transformations to target [CSSI](https://github.com/css-modules/css-modules/blob/master/INTERCHANGE_FORMAT.md), so the actual surface area of code for CSS Modules is quite small.

But to the title of your issue, the "purpose" of CSS Modules at this stage is to explore these new capabilities of the loaders with a few conventions and a small amount of additional syntax. There's no need to try to converge with other projects that are exploring competing ideas, that would defeat the purpose. The greater diversity of approaches and ideas we have, the quicker we'll learn about what works and what doesn't.
