### ISSUE TITLE
Question: Redefinition levels

### ISSUE THREAD

**Issue by sullenor** [css-modules/css-modules#60]
Hello,

I'd like talk to about "redefinition levels" feature in BEM. Actually it is an interesting feature which allows you to customize components from the external libraries on your project level:

> The final implementation of a block can be divided into different redefinition levels. Each new level extends or overrides the original implementation of the block. The end result is assembled from individual implementation technologies of the block from all redefinition levels in a pre-determined consecutive order.
...
Let's say we need to modify the appearance of one of the library blocks. That doesn't require changing the CSS rules of the block in the library source code or copying the code at the project level. We only need to create additional CSS rules for that block at the project level. During the build process, the resulting implementation will incorporate both the original rules from the library level and the new styles from the project level.

From https://en.bem.info/method/definitions/#redefinition-level

So, I wonder if it is possible to use the same mechanism with CSS Modules. In beginning I thought about `compose` key word, but it is quite challenging to guarantee the order of the styles in the final bundle.

Ideas?

**Comment by fabm22** [comment]
I would be interested too to hear about what people with experience in css-modules would say is the best way to have the same feature

**Comment by sullenor** [comment]
Well, I thought about it a lot and looks like if we want to use modules and forget about global namespace, we should also learn not to use the `redefinition levels`. 

Let's look on the `redefinition levels` closely. It makes an assumption, that you can make another folder with the same filename and the same selector inside and overwrite rules from the previous declaration. So we have to tell bundler the right order to concat our files and also save the global selectors (which are bad). So we loose all the benefits from the CSS Modules and modules itself. So, we should learn to think in terms of modules when we are talking about CSS Modules.

When you want to overwrite values from a module, usually, you make the new module on top of old one. I found a good example in twitter, which illustrates it well:
https://twitter.com/i/likes

**Comment by sullenor** [comment]
> When you want to overwrite values from a module, usually, you make the new module on top of old one. I found a good example in twitter, which illustrates it well:
https://twitter.com/icelabaratory/status/668945538839130113

I think that example solves the issue, so I'll close it.
