### ISSUE TITLE
Example using it with typescript?

### ISSUE THREAD

**Issue by lasseyls** [css-modules/css-modules#61]
I've tried setting up the webpack demo with TypesScript support, but the
import styles from ''./button.css';
syntax doesn't seem to be compatible with TypesScript, do you have any recommendations on how to use css-modules alongside TypeScript? Doesn't have to be a webpack way to do it, anything else is good.

**Comment by NekR** [comment]
const styles = <any>require('./buttons.css');

**Comment by MartinJohns** [comment]
FYI - relevant issues:

Microsoft/TypeScript#2709 - Importing files other than TS modules
Microsoft/TypeScript#6615 - Support shorthand ambient module declarations and wildcard chars in module names

**Comment by Quramy** [comment]
Hi guys !

I've created [typed-css-modules](https://github.com/Quramy/typed-css-modules) to write `import * as styles from "button.css";` . This tool creates .d.ts file from .css file.

For example: 

```css
/* button.css */
.button {
  color: red;
}
```

```ts
/* button.css.d.ts */
export const button: string;
```

So you can write :

```ts
/* button.ts */
import * as styles from "button.css";

/* and IDE(e.g. VSC) completes the "button" property in this styles ! */
console.log('<button class="`${styles.button}`" >click me</button>');
```

If you use TypeScript and CSS Modules, please check it out.

**Comment by yoime** [comment]
I think it's not working.
i have 
```js
import * as styles from "Button.css";
```
in my tsx file.
I have Button.css.d.ts file generated by typed-css-modules and it's not working.
Example 	
above also not working.
can you provide working example with react, webpack and tsx.

Thank you.

**Comment by oojacoboo** [comment]
@Quramy any examples of that working with webpack?

**Comment by Quramy** [comment]
@oojacoboo sorry, I don't have any example with webpack. I've created a working demonstration with browserify, https://github.com/Quramy/typescript-css-modules-demo .
And @olegstepura created https://github.com/olegstepura/typed-css-modules-loader .

**Comment by Quramy** [comment]
Hi @yoime .  Sorry, I've mistaken at the above comment.  You should write 

```ts
import * as styles from "./Button.css"; /* explicit relative path */
```

I've updated my working repo(https://github.com/Quramy/typescript-css-modules-demo) with TypeScript 2.0.3 and `tsc` works fine.

**Comment by tridon777** [comment]
```
module: {
        loaders: [
             { test: /\.css$/, loaders: ["style","css?modules&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5],typed-css-modules"]},
            { test: /\.js$/, loader: "source-map-loader" },
            { test: /\.tsx?$/, loader: "ts-loader" }
        ],
    }
```
@oojacoboo @yoime   here is how I got everything to work .

**Comment by zakdances** [comment]
Any examples with Webpack2?

**Comment by rfgamaral** [comment]
Here's an example of how I got this working (with some caveats) with TypeScript2 + Webpack2:

```json
"devDependencies": {
    "awesome-typescript-loader": "^3.0.0-beta.18",
    "css-loader": "^0.26.1",
    "source-map-loader": "^0.1.6",
    "style-loader": "^0.13.1",
    "typed-css-modules": "^0.1.13",
    "typed-css-modules-loader": "0.0.4",
    "typescript": "^2.1.5",
    "webpack": "^2.2.0-rc.7",
    "webpack-dev-server": "^2.2.0-rc.0"
}
```

```javascript
module: {
    rules: [
        {
            include: path.join(__dirname, 'app'),
            loader: 'awesome-typescript-loader',
            test: /\.tsx?$/
        },
        {
            include: path.join(__dirname, 'app'),
            loader: 'source-map-loader',
            test: /\.js$/,
            enforce: 'pre'
        },
        {
            include: path.join(__dirname, 'app'),
            test: /\.css$/,
            use: [
                {
                    loader: 'style-loader'
                },
                {
                    loader: 'css-loader',
                    options: {
                        modules: true,
                        importLoaders: 1,
                        camelCase: true,
                        localIdentName: '[name]_[local]_[hash:base64:5]'
                    }
                },
                {
                    loader: 'typed-css-modules-loader',
                    options: {
                        camelCase: true
                    }
                }
            ]
        }
    ]
}
```

Some caveats:

- Webpack (or Webpack Dev Server) will need to invoked twice. The first `*.d.ts` files generation and the second to use them. The first compilation will always give an error like `Cannot find module './Component.css'.`. I wasn't able to find a work around for this...
- I tried to use `outDir` on the `typed-css-modules-loader` but then I wasn't able to include that new output directory into my app in a way that that I could easily import the `.css` files without complex paths in import statements.
- I wasn't able to get the `extract-text-webpack-plugin` plugin working. I'm sure it can be done, I just didn't waste to much time there.

**Comment by rfgamaral** [comment]
I'd much prefer to use the `import * as Style from "./Component.css";` syntax above, but given the issues around the current implementation (see [previous comment](#issuecomment-273107869)), I resorted to something else...

**Import CSS styles:**

```typescript
const Style = require<any>("./Hello.css");
```

**Load CSS with Webpack2:**
```javascript
module: {
    rules: [
        {
            loader: 'awesome-typescript-loader',
            test: /\.tsx?$/
        },
        {
            loader: 'source-map-loader',
            test: /\.js$/,
            enforce: 'pre'
        },
        {
            test: /\.css$/,
            loader: ExtractTextPlugin.extract({
                fallbackLoader: 'style-loader',
                loader: {
                    loader: 'css-loader',
                    query: {
                        modules: true,
                        importLoaders: 1,
                        camelCase: true,
                        localIdentName: '[name]_[local]_[hash:base64:5]'
                    }
                }
            })
        }
    ]
},

plugins: [
    new ExtractTextPlugin({
        filename: '[name].[hash:8].css',
        allChunks: true
    })
]
```

**For reference this is my entry point:**

```javascript
entry: {
    app: path.join(__dirname, 'app', 'src', 'Index.tsx')
}
```

**Next to `Index.tsx` I have a `Global.d.ts` file with the following:**

```typescript
/**
 * Describe a new type to require non-typescript source files like CSS and other resources.
 */
declare const require: {
    <T>(path: string): T;
    (paths: string[], callback: (...modules: any[]) => void): void;
    ensure: (paths: string[], callback: (require: <T>(path: string) => T) => void) => void;
};
```

Hope this is helpful... :)

**Comment by xumix** [comment]
Here is a nice article for drop in replacement for css loader: https://medium.com/@sapegin/css-modules-with-typescript-and-webpack-6b221ebe5f10

**Comment by iNaps** [comment]
My modules.d.ts:

declare module "*.less" {
  const styles: any;
  export default styles;
}

**Comment by kirillgroshkov** [comment]
> My modules.d.ts:
> 
> ```
> declare module "*.less" {
>   const styles: any;
>   export default styles;
> }
> ```

Genious! It helped me, thanks!
