### ISSUE TITLE
Root directory for dependencies?

### ISSUE THREAD

**Issue by tslocke** [css-modules/css-modules#64]
I've found myself needing to do:

    .foo {
      composes: baa from "../../somewhere/stuff.css";
      ...
    }

The ../.. feels brittle. Is there any way to give a path relative to the root of my css tree?

**Comment by joshwnj** [comment]
@tablatom take a look here for an example of using webpack's `resolve` field: https://github.com/css-modules/webpack-demo/blob/master/webpack.config.js#L31-L33

Then you can do things like https://github.com/css-modules/webpack-demo/blob/master/src/components/3-ClassComposition/StyleVariantB/StyleVariantB.css#L7

I believe there's an equivalent in browserify but haven't looked into that yet :)

**Comment by tslocke** [comment]
Thanks you!

Got it working in browserify. You need to set the `path` option. There doesn't seem to be a command line option, but the `NODE_PATH` environment var does the same job, so my command ended up as:

    NODE_PATH=./node_modules:./styles browserify -p [ css-modulesify -o public/main.css --rootDir styles] styles/css_modules.js -o public/css_modules.js

But in the end I decided to bite the bullet and learn webpack. So now my command is `webpack` :smile:

**Comment by joshwnj** [comment]
Good stuff, thanks for sharing what you found :)

**Comment by delijah** [comment]
Also related to #170.
