### ISSUE TITLE
Constants and pseudo selectors?

### ISSUE THREAD

**Issue by sgwilym** [css-modules/css-modules#68]
Working on a project where I'm really trying to get into the CSS modules way of doing things, and really enjoying doing so. I've also enjoyed bumping into limitations and reading the discussions on this repo as to why those limitations are justified and encourage better practices.

However, there's one thing I'd like to do that I can't figure out.

Like many people, I would like to define some colours that are constant across all my styles.

```
.niceShadeOfBlueBackground {
  background-color: rgb(116, 194, 238);
}
```

Great, now I can compose `niceShadeOfBlueBackground` wherever I need it. But I've got some buttons that I'd really like to appear grey at first, and then only turn blue — my nice shade of blue — when I hover over it. But I can't compose `niceShadeOfBlueBackground` into `blueOnHover:hover` because it's a pseudo selector.

I think there’s lots more cases you'd want to use externally defined constants like colours or metrics within pseudo selectors, but currently I can't see how you'd do it. I know you can compose classes with pseudo selectors into others, but that doesn't solve how I'd get style constants into those pseudo selectors to begin with. 

What would be the CSS Modules way of tackling this problem?

**Comment by tivac** [comment]
https://github.com/css-modules/postcss-modules-values adds `@value` support, which sounds like what you're looking for.

Doesn't look like it's been pulled into https://github.com/css-modules/css-modules-loader-core though, so unsure if it's ready to use.

**Comment by geelen** [comment]
It's very very close, only a few issues on that repository remain. But yep, this is the exact use case we couldn't solve with `composes` alone, hence why values will be part of the whole equation (soon!!)

**Comment by sgwilym** [comment]
Cool, looking forward to that then!
