### ISSUE TITLE
More demos needed

### ISSUE THREAD

**Issue by fingermark** [css-modules/css-modules#72]
It would be nice to have a demo that showcased how to use CSS Modules properly.

For example, I'd like to see 

Multiple pages or components where forms need to be styled consistently.  Right now I don't really know how to best style input fields.  Do I just have a global style for all input[type="text"]?

Also, is there something better than using bootstrap and css modules?

**Comment by rossPatton** [comment]
i agree. css modules sounds like an awesome idea, but it would be nice to see some non-trivial examples

**Comment by geelen** [comment]
Yep, I agree. We're working on a homepage for the project which will give us a place to put them, and also serve as an example in and of itself.

**Comment by ctaepper** [comment]
:+1:

**Comment by mr-wildcard** [comment]
:+1:

**Comment by nkbt** [comment]
Example of npm-publishable UI component using CSS modules: https://github.com/nkbt/css-modules-component-template

**Comment by StevenIseki** [comment]
I have some examples using both React and Deku. https://github.com/StevenIseki/webpack-css-loader-examples I plan to work on some more soon

**Comment by sgtpep** [comment]
FYI, [CSS Modules BEM Demo](https://github.com/sgtpep/css-modules-bem-demo).
> A demo of using [CSS Modules](https://github.com/css-modules/css-modules) within HTML files following the [BEM](http://getbem.com/) approach and powered by [Gulp](https://github.com/gulpjs/gulp) and [Lo-Dash/Underscore templates](https://lodash.com/docs#template).

**Comment by delijah** [comment]
As far as i know BEM is obsolete when using CSS Modules?

**Comment by sgtpep** [comment]
@delijah Technically, I agree. My point was to show that CSS Modules could be used for the regular websites the same way as BEM to achieve the similar output and usage.
