### ISSUE TITLE
uncss support ? 

### ISSUE THREAD

**Issue by mydearxym** [css-modules/css-modules#74]
amazing work! 

it this project support [uncss](https://github.com/giakki/uncss) to remove unused css ?

**Comment by gajus** [comment]
No. But in theory, CSS Modules implementation (e.g. `style-loader`) could track which properties of the `styles` object have been accessed and remove any styles from the build that have not been accessed, e.g.


car.css

```css
.bonnet {
    color: #fff;
}

.tyre {
    color: #000;
}
```

car.js

```js
import styles from 'car.css';

<div classNames={styles.type}></div>
```

In the above example, `styles` object knows that `bonnet` style name was not read (e.g. by using ES6 getters/setters) and could exclude it from the build.

Though, thats CSS Modules implementation specific feature.

**Comment by mydearxym** [comment]
thanks @gajus
