### ISSUE TITLE
Disable CSS mapping for a code of block

### ISSUE THREAD

**Issue by gajus** [css-modules/css-modules#79]
I want to use http://facebook.github.io/fixed-data-table/example-sort.html. According to the docs, I need to load their CSS (https://github.com/facebook/fixed-data-table/blob/master/dist/fixed-data-table.css) document. Unfortunately, this approach pollutes the entire namespace.

A simple workaround would be a combination of HTML and CSS, e.g.

```html
<div styleName='my-namespace'>
    <Table />
</div>
```

Then in ICSS I could have something like:

```
.my-namespace {
    :do-no-map {
        /**
         * Copy paste all the Fixed Data Table CSS, e.g.
         */
        .foo,
        .another-very-generic-class {
            display: table;
        }
    }
}
```

This should generate:

```
.my-namespace-some-unique-hash-ST241 .foo,
.my-namespace-some-unique-hash-ST241 .another-very-generic-class {
    display: table;
}
```

As far as I can tell, this is not part of the spec at the moment.

**Comment by kilianc** [comment]
+1 on avoiding rewrites on nested classes

**Comment by gajus** [comment]
@sokra What are your thoughts on this?

**Comment by tivac** [comment]
Isn't that exactly what `:global()` is for?

Not 100% sure how you'd apply it to all child classes, but it does exactly what `:do-no-map` in your example does afaik.

**Comment by gajus** [comment]
> Isn't that exactly what :global() is for?
> 
> Not 100% sure how you'd apply it to all child classes, but it does exactly what :do-no-map in your example does afaik.> 

`:global` is just that – global style. I want to have an unmapped style under a CSS module.

I think that the example I have mentioned illustrates the use case quite well. Here is another example: https://github.com/gajus/react-css-modules/issues/114

> For example i use `react-bootstrap` button, and want to override padding of `.help-block` to which i have no direct access. 
> 
> ```javascript
> <div className={styles.myDiv}>
>     <Input value={this.state.value}/>
> </div>
> ```
> 
> 
> With scss everything is simpe:
> 
> ```scss
> .myDiv{
>     /*my styles */
>     .help-block{ /* <-- this is bootstrap's layout */
>         font-size: 1em;
>     }
> }
> ```
>
> But how can i do this with [css modules]?

**Comment by gajus** [comment]
@geelen any official comment?

**Comment by gajus** [comment]
I had a second look at the documentation (https://github.com/css-modules/css-modules#exceptions). I did not realise that `:global` is relative to the parent selector, i.e.

```css
:local .foo :global .bar {
    background: #f00;
}
```

translates to:

```css
.foo___3mYge .bar
```

The name (`:global`) is a bit misleading in this use case (class is not made global), but it does exactly what I was asking to introduce `:do-no-map` for.
