### ISSUE TITLE
JavaScript in CSS code

### ISSUE THREAD

**Issue by amannn** [css-modules/css-modules#81]
I'm really inspired by css-modules and I already use it on a smaller project of mine. So far really amazing!

I just watched the talk from Mark Dalgleish from Reactive 2015, where [he shared his thoughts on JSS-loader](https://youtu.be/BfzjuhX4wJ0?t=4h4m30s).

I was thinking if you could actually do the opposite: writing mostly CSS, but extending it at some points with JavaScript.

What comes to mind, is something like JSX, where it's basically HTML, but can be extended with JS when you use curly braces:

``` html
<div className={className} style={{color: red}}>test</div>
```

What if you could apply that to CSS?

``` js
import colors from 'config';
import ColorUtils from 'utils';

.button {
  padding: 10px;
  color: {colors.green};
  background-color: {ColorUtils.darken(colors.green, 0.8)};
}
```

A more sophisticated example could be something like this:

``` js
import colors from 'config';
import ColorUtils from 'utils';

.button {
  padding: 10px;
}

// Generate .button-blue, .button-red, …
{Object.keys(colors)map(key =>
  .button-{key} {
    color: {colors[key]};
    background-color: {ColorUtils.darken(colors[key], 0.8)};
  }
)}
```

This isn't so much about the actual syntax, but rather about the idea. You can still use all the CSS knowledge that you have, but – if needed – may use some JavaScript to make things a bit more dynamic.

Does somebody know if there's already an approach like this?

**Comment by mykz** [comment]
I think [PostCSS](https://github.com/postcss/postcss) is what your after.

**Comment by rossPatton** [comment]
PostCSS, as well as any of the pre-processors based on it. Stylus for instance, makes it very easy to pass things in from javascript.

**Comment by amannn** [comment]
Are there some pre-processors in particular that you're thinking of? After a first research I couldn't find anything existing that suits the described idea roughly. Also with Stylus I couldn't find a good integration of JavaScript.

Would you mind pointing me to something?

**Comment by rossPatton** [comment]
Sure, Stylus is what I know best and it's all js under the hood. The [documentation](https://learnboost.github.io/stylus/docs/js.html) regarding it's js hooks is pretty bad though.

I figured out how to do it by looking at [nib](https://github.com/tj/nib) and implemented something similar [here](https://github.com/rossPatton/composure-grid).

My example mostly involves defining global variables base on a js config, and then does most of it's logic in stylus, but there's no reason why you can't do some of that logic on the javascript side. Nib for example has a color gradient generator, which most of that logic being on the js side.

Hope that helps.
