### ISSUE TITLE
angularjs2 webpack

### ISSUE THREAD

**Issue by joaogarin** [css-modules/css-modules#83]
Hello I am having an issue trying to use css modules with angularJs2.

I have the following component inside src/components 

```
/*
 * Angular 2 decorators and services
 */
import {Component, View} from 'angular2/angular2';

import styles from './logo.css';

/*
 * App Component
 * Top Level Component
 */
@Component({
    selector: 'logo', // <app></app>
    template: `
        <div>
            Here comes the logo
        </div>
    `
})
export class Logo {
    onInit(){
        //console.log(styles);
    }
}

```

I get the message 

"error TS2307: Cannot find module './logo.css'.".

In my webpack config there are some angular specifics but the general thing is more or less simillar to the webpack demo

I have 

{ test: /\.css$/, loader: ExtractTextPlugin.extract('style-loader', 'css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss-loader') },

modulesDirectories: ['node_modules', 'components']

My "entry" setting in webpack config is a bit different from the one here. It looks like this : 

```

entry: {
    'angular2': [
      // Angular 2 Deps
      '@reactivex/rxjs',
      'zone.js',
      'reflect-metadata',
      // to ensure these modules are grouped together in one file
      'angular2/angular2',
      'angular2/core',
      'angular2/router',
      'angular2/http'
    ],
    'app': [
      // App
      './src/app/bootstrap'
    ]
  },

```

**Comment by joaogarin** [comment]
I think the issue is more around the webpack configuration. I am pretty new to webpack but it seems it cant find or understand my css file as a module..

**Comment by joaogarin** [comment]
Hello I have fixed my issue. I am making a repository of the webpack demo with Angular2. Maybe that will be of use and I can contribute it after its more complete.

Here it is : https://github.com/joaogarin/css-modules-angular2

**Comment by lanocturne** [comment]
@joaogarin Thanks man, that example is GREAT! Any suggestion I can apply it on site theme change?

**Comment by joaogarin** [comment]
I am using it on a site. The way I use it is by using webpack much like in the react examples.

In the component you do : require("./app.css"); and then apply that in the component inline HTML.

In webpack you just use css loader with css modules.

{ test: /\.css$/, loader: ExtractTextPlugin.extract('style-loader', 'css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss-loader') },

Maybe I am not answering your question:P but you can check the code on the repository. Its not updated to angualr2 beta but I will try to do that in the next days.

**Comment by fabm22** [comment]
@joaogarin May I suggest to bind the css-modules generated classes to the NgClass directive property of Angular2 ? See this comment : http://stackoverflow.com/a/30286757. 
The idea so far at least for me would be to leave the "native" class property for good old global css from third parties like bootstrap (for now)

What do you think ?

**Comment by joaogarin** [comment]
I think basically that I would actually stick to the styles property of the component that way you get also the benefit of angular's internal style system which is awesome btw. But I guess this would also work.

Libraries like bootstrap and global css stuff I generally load them in the root component using ViewEncapsulation.None that way css scoping will not be applied for sure on those.

Right now to be completely fair I am not really using CSS modules as the Angular2 system is already so advanced in terms of CSS csoping, but the repo I guess provides a good insight on how you can set those two up if you might neeed something specific from CSS modules.

I am going ahead and close the issue since there is nothing here to actually be fixed=)
