### ISSUE TITLE
CSS Modules + ReactCSSTransitionGroup in React 0.14

### ISSUE THREAD

**Issue by ArnoBuschmann** [css-modules/css-modules#84]
Hello, following this page: https://gist.github.com/markdalgleish/fab73ca3ace3b9ab6077

The animation/transition in my code is still not taking place and the element renders right away without transitioning.

What am I missing or doing wrong?

The code:

```javascript
import styles from '../assets/css/app.css';
import CSSTransitionGroup from 'react-addons-css-transition-group';

class App extends React.Component {
  renderMyTransition() {
    switch (this.props.currentPage) {
    case 'testpage':
      return <div key="one"><p>Test-Page-One</p></div>
    case 'secondtestpage':
      return <div key="two"><p>Test-Page-Two</p></div>
    default:
      return <div key="default"><p>Not found.</p></div>
    }
  }
  render() {
    return (
      <div className={styles.content}>
        <CSSTransitionGroup transitionAppear={true} transitionAppearTimeout={500} transitionEnterTimeout={500} transitionLeaveTimeout={300} transitionName={styles}>
          {this.renderMyTransition()}
        </CSSTransitionGroup>
      </div>
    );
  }
}

export default App;
```

The CSS:

```
.enter {
  opacity: 0.01;
  transition: opacity 1.5s ease-in;
}
.enter.enter-active {
  opacity: 1;
}
.leave {
  opacity: 1;
  transition: opacity 1.5s ease-in;
}
.leave.leave-active {
  opacity: 0.01;
}
.appear {
  opacity: 0.01;
}
.appear.appear-active {
  opacity: 1;
  transition: opacity 1.5s ease-in;
}

**Comment by markdalgleish** [comment]
The CSS should use camel case instead:

```css
.enter {
  opacity: 0.01;
  transition: opacity 1.5s ease-in;
}
.enter.enterActive {
  opacity: 1;
}
.leave {
  opacity: 1;
  transition: opacity 1.5s ease-in;
}
.leave.leaveActive {
  opacity: 0.01;
}
.appear {
  opacity: 0.01;
}
.appear.appearActive {
  opacity: 1;
  transition: opacity 1.5s ease-in;
}
```

**Comment by ArnoBuschmann** [comment]
Thanks Mark for your quick response. Good point. But hm, still not working, anything else I can try?

**Comment by ArnoBuschmann** [comment]
Maybe a problem with the webpack configuration?
```loader: 'style!css?modules&localIdentName=[name]---[local]---[hash:base64:5]!postcss'```

**Comment by ArnoBuschmann** [comment]
Ok, seems the effect was just not obvious now, changing the timeouts from

```<CSSTransitionGroup transitionAppear={true} transitionAppearTimeout={500} transitionEnterTimeout={500} transitionLeaveTimeout={300} transitionName={styles}>```

to

```<CSSTransitionGroup transitionAppear={true} transitionAppearTimeout={2000} transitionEnterTimeout={2000} transitionLeaveTimeout={2000} transitionName={styles}>```

finally did the trick.

**Comment by shogochiai** [comment]
I was also same situation and I solved by :global scope ()

```
// window.jsx
  render (){
    return (
      <div>
        <CSSTransitionGroup
          transitionName={"window-blur"}
          transitionAppear={true}
          transitionAppearTimeout={1000}
          transitionEnterTimeout={1000}
          transitionLeaveTimeout={1000}
          >
          <Header />
          <Body />
          <Footer />
        </CSSTransitionGroup>
      </div>
    );
  }


//window.scss

:global {
  .window-blur-enter {
    opacity: 0.01;
  }

  .window-blur-enter.window-blur-enter-active {
    opacity: 1;
    transition: opacity 500ms ease-in;
  }

  .window-blur-leave {
    opacity: 1;
  }

  .window-blur-leave.window-blur-leave-active {
    opacity: 0.01;
    transition: opacity 300ms ease-in;
  }
  .window-blur-appear {
    opacity: 0.01;
  }

  .window-blur-appear.window-blur-appear-active {
    opacity: 1;
    transition: opacity .5s ease-in;
  }
}

// webpack loaders
  {
    test: /\.css$/,
    loader: [
      'style-loader',
      'css-loader?sourceMap&modules&localIdentName=[name]__[local]__[hash:base64:5]',
      'postcss-loader'
    ].join('!')
  },

  {
    test: /\.scss$/,
    loader: [
      'style-loader',
      'css-loader?sourceMap&modules&localIdentName=[name]__[local]__[hash:base64:5]',
      'postcss-loader',
      'sass-loader?' + sassParams.join('&')
    ].join('!')
  },

```

This worked yet it is global scope so that transitionName should not be too simple.

**Comment by Andreyco** [comment]
Has anyone managed to do this without having transition name specified `:global` namespace?

**Comment by OttlikG** [comment]
As you saw in the first example, you can do with this technique:
https://facebook.github.io/react/docs/animation.html#custom-classes

Just apply the imported object to the transitionName property:
```javascript
import styles from '../assets/css/app.css';
<CSSTransitionGroup transitionName={styles} transitionEnterTimeout={500} transitionLeaveTimeout={300}>
   { content }
</CSSTransitionGroup>
```

**Comment by elrumordelaluz** [comment]
@Andreyco I solved specifying the `transitionName` Object prop. Something like:

```js
import style from './Styles.css';
// ...
<ReactCSSTransitionGroup
  transitionName={{
    enter: style.enter,
    enterActive: style.enterActive,
    leave: style.leave,
    leaveActive: style.leaveActive,
  }}
  transitionEnterTimeout={250}
  transitionLeaveTimeout={250}>
  { /*... */ }
</ReactCSSTransitionGroup>
```

and in `Styles.css`:

```css
.enter {
  transition: all 250ms;
  /* ... */
}
.enterActive { /* ... */ }
.leave { /* ... */ }
.leaveActive {  /* ... */  }
```

**Comment by SimoNonnis** [comment]
Does anyone managed to make react-addons-css-transition-group works with css-modules?
Tried all the solution above with no luck.

**Comment by amilajack** [comment]
@markdalgleish Please update your answer, as camel casing has been deprecated in favor of `kebab-case`

This is the example taken from the docs:

```css
.example-enter {
  opacity: 0.01;
}

.example-enter.example-enter-active {
  opacity: 1;
  transition: opacity 500ms ease-in;
}

.example-leave {
  opacity: 1;
}

.example-leave.example-leave-active {
  opacity: 0.01;
  transition: opacity 300ms ease-in;
}
```

**Comment by amilajack** [comment]
@SimoNonnis check if your css animation duration lasts as long as your `transitionLeaveTimeout` and `transitionEnterTimeout` durations.

**Comment by iam-peekay** [comment]
@elrumordelaluz thank you! worked like a charm.

**Comment by hidace** [comment]
Using version 15.3.2, when I would pass in an object, like so:

```
transitionName={{
    enter: style.enter,
    enterActive: style.enterActive,
    leave: style.leave,
    leaveActive: style.leaveActive,
  }}
```
I found that I was getting an error that read:

> Uncaught Error: CSSCore.addClass takes only a single class name. "[object Object]-appear" contains multiple classes.

So I had to pass my css into my ReactCSSTransitionGroupName as such - as just the imported name that points to my css file. This worked for me:

**Login.js Component**

```
import React from 'react';
import ReactCSSTransitionGroup from 'react-addons-css-transition-group';
import PageTitle from '../PageTitle';
import LoginForm from '../LoginForm';
import transitions from '../../styles/css/transitions.css';

const Login = () =>
  <div>
    <ReactCSSTransitionGroup
      transitionName={transitions}
      transitionAppearTimeout={500}
      transitionAppear={true}
      transitionEnterTimeout={500}
      transitionLeaveTimeout={300}
    >
      <PageTitle title="Login" />
      <LoginForm />
    </ReactCSSTransitionGroup>
  </div>;

export default Login;

```

**transitions.css**

```
.enter {
  opacity: 0.01;

  &.enterActive {
    transition: opacity 0.5s ease-in;
    opacity: 1;
  }
}

.leave {
  opacity: 1;

  &.leaveActive {
    transition: opacity 0.3s ease-in;
    opacity: 0.01;
  }
}

.appear {
  opacity: 0.01;

  &.appearActive {
    transition: opacity 0.5s ease-in;
    opacity: 1;
  }
}

```

The classes only seemed to work if they were camel-cased (could not get  working in kebab-case). Hope this helps.

**Comment by reznord** [comment]
@elrumordelaluz thanks a ton !! works like a chart

**Comment by reznord** [comment]
@elrumordelaluz have you implemented page transition? If so, can you show a gist how did you do that?

**Comment by elrumordelaluz** [comment]
@reznord didn't implemented, could not work the same way?

**Comment by reznord** [comment]
@elrumordelaluz Regarding the page transitions, I did a bit of homework and implemented it. 

```
import styles from './styles/animate.css;

class Test extends React.Component {
  render() {
    <ReactCSSTransitionGroup 
         transitionAppear={true} 
         transitionName={styles} 
         transitionEnterTimeout={300} 
         transitionLeaveTimeout={300} 
         transitionAppearTimeout={300}
     >
  }
}
```

and this is what I did in `animate.css`:

```
.enter {
  opacity: 0.01;

  &.enterActive {
    transition: opacity 0.3s ease-in;
    opacity: 1;
  }
}

.leave {
  opacity: 1;

  &.leaveActive {
    transition: opacity 0.3s ease-out;
    opacity: 0.01;
  }
}

.appear {
  opacity: 0.01;

  &.appearActive {
    transition: opacity 0.3s ease-in;
    opacity: 1;
  }
}

```

**Comment by alisonailea** [comment]
@hidace 

> I found that I was getting an error that read: Uncaught Error: CSSCore.addClass takes only a single class name. "[object Object]-appear" contains multiple classes.

I noticed you didn't include the renaming of the "appear" class.

have you tried something like this?

**Comment by alisonailea** [comment]
@hidace

I found that I was getting an error that read: Uncaught Error: CSSCore.addClass takes only a single class name. "[object Object]-appear" contains multiple classes.
I noticed you didn't include the renaming of the "appear" class.

have you tried something like this?

**Comment by alisonailea** [comment]
@hidace

> I found that I was getting an error that read: Uncaught Error: CSSCore.addClass takes only a single class name. "[object Object]-appear" contains multiple classes.
I noticed you didn't include the renaming of the "appear" class.

have you tried something like this?
```
transitionName={{
    enter: style.enter,
    enterActive: style.enterActive,
    leave: style.leave,
    leaveActive: style.leaveActive,
    appear: style.appear,
    appearActive: style.appearActive,
  }}
```

**Comment by daise** [comment]
i got the same issue @reznord  mentioned, any idea to make leave transition work? 
Please let me know.

**Comment by willowcheng** [comment]
To get rid of camel case CSS selectors, I find it also works by

```js
transitionName={{
    enter: style['enter'],
    enterActive: style['enter-active'],
    leave: style['leave'],
    leaveActive: style['leave-active'],
    appear: style['appear'],
    appearActive: style['appear-active'],
  }}
```

**Comment by loukitzanna** [comment]
If you're having the same issue as @reznord and @daise it was `exit` not `leave` for me
```scss
.enter {
  opacity: 0.01;

  &.enterActive {
    transition: opacity 0.3s ease-in;
    opacity: 1;
  }
}

.exit {
  opacity: 1;

  &.exitActive {
    transition: opacity 0.3s ease-out;
    opacity: 0.01;
  }
}
```

**Comment by thanhtutzaw** [comment]
Any Update ?  I was using CSSTransitions with Nextjs and CSS module .  Cannot set enter style in module css . BUt it works in global.css , How can I do in module css .
Updat: Now I can set class like that    drawer-enter-done
But I can't set css in module css . How can I set ?
I have tried these and did not work.
.drawer-enterDone 
and 
.drawer-enter-done

**Comment by thanhtutzaw** [comment]
> ```js
> transitionEnterTimeout
> ```

### This doesn't work in 2023 . Doc and Example are not enough .

**Comment by BloqX3** [comment]
i'm using `"react-transition-group": "^4.4.5"`, the following configuration worked for me:
```jsx
<CSSTransition ...
            classNames={{
                enterActive: styles.transitionEnterActive,
                enter: styles.transitionEnter,
                exitActive: styles.transitionExitActive,
                exit: styles.transitionExit
              }}
>
```
