### ISSUE TITLE
How to combine with sass

### ISSUE THREAD

**Issue by joaogarin** [css-modules/css-modules#87]
Hello,

Curious whats the approach to combining css modules with sass. Any idea on how this could work? 

Should we first preprocess the sass into css and only use css loader? should we use sass-loader at all?

Cheers

**Comment by StevenIseki** [comment]
You can use post-css and [precss plugin](https://github.com/jonathantneal/precss) I have an example project [here](https://github.com/StevenIseki/webpack-css-loader-examples/tree/master/post-css). In this one I am using only one post-css plugin autoprefixer in this project, but just add in precss to the postcss function like this

```js
postcss: function () {
    return [autoprefixer];
  },
```

**Comment by StevenIseki** [comment]
Your webpack.config needed for using css-modules, post-css and the precss plugin will be something like the file this: 

```js
var path = require('path');
var webpack = require('webpack');
var autoprefixer = require('autoprefixer');
var precss = require('precss');
var ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
  devtool: 'source-map',
  entry: ['./src/index'],
  output: {
    filename: 'bundle.js',
    path: path.join(__dirname, 'public'),
    publicPath: '/public/'
  },
  module: {
    loaders: [
      { test: /\.js$/, loader: 'babel-loader', exclude: /node_modules/ },
      { test: /\.css$/, loader: ExtractTextPlugin.extract('style-loader', 'css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss-loader') }
    ]
  },
  postcss: function () {
    return [autoprefixer, precss];
  },
  plugins: [
    new ExtractTextPlugin('style.css', { allChunks: true })
  ]
};
```

However I'm not exactly sure how to initialize precss as it mentions you also need to require `require('postcss-scss')`. If you have a chance to play around and then give an updated webpack.config that would be nice. The [precss docs](https://github.com/jonathantneal/precss) might be able to help you out

**Comment by joaogarin** [comment]
Thanks yes that sounds like a good way!

**Comment by bensampaio** [comment]
The original question was how to use CSS Modules with SASS. That is not answered here... At least from what I understood PreCSS and SASS are two different things.

**Comment by jvivs** [comment]
@bensampaio ditto...
