### ISSUE TITLE
Node support

### ISSUE THREAD

**Issue by seeden** [css-modules/css-modules#9]
Hi
css-modules is a very good idea.
I really understand that it is working like a charm with combination with webpack. But a lot of us are using the React like an isomorphic application. That means we are rendering whole page on the server with pure nodejs and babel(es6 support). The problem is that I am not able to simply use "import styles from .css" because there is no webpack in the middle.
Do you have any idea how to use this great idea with node/io on the server side?
Somehow like babel/register. If we will have this it will be like holy grail for css :)

**Comment by nkbt** [comment]
You can use webpack programmatic api (or middleware if you are into express) to process your assets.

**Comment by nkbt** [comment]
http://webpack.github.io/docs/node.js-api.html

**Comment by seeden** [comment]
@nkbt thanks for fast answer. I think that this is not a solution for this problem. Because I want to use standard import style from 'your.css'; on the server side. Like register css extension in the node. Maybe I do not understand you. Can you be more specific ?

**Comment by nkbt** [comment]
@seeden https://github.com/gpbl/isomorphic500/blob/master/webpack/prod.config.js check this config for example. With extract-text-plugin you can get all css into another chunk and serve separately.

**Comment by seeden** [comment]
I know about this. But I need to get classNames from the css for react components on the server

**Comment by andreypopp** [comment]
@seeden I think it is good idea to run client React code on server via webpack. That way you get isolated scope for each request (which is important as some front end code could not be ready to run in a shared global scope) and the same/more similar build setup as client code.

**Comment by seeden** [comment]
I am using flexible for isolating scope. And I am sharing same code on the server and client side. This is the main idea of whole of this (because speed and simplicity). I am using webpack of course but only for bundling files for clients.

**Comment by jarsbe** [comment]
@seeden Any luck getting classNames for server side rendering? I've got the same issue and would like to avoid webpack server side too.

**Comment by joshwnj** [comment]
@jarsbe one option is to use https://github.com/css-modules/css-modules-loader-core/ to extract the classNames for you. We're using this in the browserify implementation of css-modules, you can refer to the example here: https://github.com/css-modules/css-modulesify/blob/master/index.js#L37-L43

**Comment by seeden** [comment]
@jarsbe not yet. I am waiting for the better solution. @joshwnj looks interesting but it is not a good solution for this problem.

**Comment by joshwnj** [comment]
@seeden do you mean you want to still be able to do `require('styles.css')` from within a node script?  Could you please elaborate on what you are hoping to do beyond loading a css file and getting back locally-scoped classnames?

**Comment by seeden** [comment]
A need to use this names in React components rendered on the server side. I need to use a same code on the frontend and backend side because for me it is same. But server side is working without webpack.

**Comment by jarsbe** [comment]
@seeden You should bundle your react application with a separate webpack server config. Instead of bundling the entire node app bundle just the React/Flux entry point (usually routes.jsx). Check out what I've done [here](https://github.com/jarsbe/book-shelf/tree/isomorphic/)

The webpack config bundles from the routes.jsx file [here](https://github.com/jarsbe/book-shelf/blob/isomorphic/webpack/server.config.js#L6)

Which is then used during serverside rendering [here](https://github.com/jarsbe/book-shelf/blob/isomorphic/server/utils/render.js#L4)

**Comment by seeden** [comment]
@jarsbe it makes sense and it is acceptable solution. Thanks for this

**Comment by danny-andrews** [comment]
Also, there's this: https://github.com/michalkvasnicak/babel-plugin-css-modules-transform. But it looks like it's pretty early in development.
