### ISSUE TITLE
Composes includes the entire css on my webpack bundle

### ISSUE THREAD

**Issue by GuilhermeMedeiros** [css-modules/css-modules#90]
I was wondering how I could avoid that. I have something like that:

``` css
.btn {
    composes: btn from 'bootstrap'; /* bootstrap is an alias to bootstrap/dist/css/bootstrap.css */
}
```

But I end up with the entire bootstrap instead of just the necessary styles.
Is there a way I can avoid that?

**Comment by geelen** [comment]
That'd be nice, but it's really really tough given the way bootstrap works. Not just bootstrap, any global CSS library is going to be tough to integrate (the same way global JS libraries took some time to be compatible with browserify)

You might try to clone bootstrap & build only the parts that you need? Dead code elimination is a feature we're hoping to add to CSS Modules but it's a big chunk of work.

**Comment by GuilhermeMedeiros** [comment]
I could use bootstrap mixins instead, but this is not really what I'm looking for.
I believe most of the people are using css modules + jsx, right? Couldn't we use [purify](https://github.com/purifycss/purifycss) to analyse the css + jsx + composed modules altogether?

**Comment by nkbt** [comment]
Most of existing CSS rely on overrides, global styles, classes, modifiers. I doubt there is an easy way to remove dead CSS. You know... css is additive, never delete stuff, only add and override, otherwise you risk breaking everything *sarcasm here*

**Comment by GuilhermeMedeiros** [comment]
How would be the ideal approach then? Let's ignore the fact we have Bootstrap and think of a full-css-modules-compliant library and how we can compose from it without embedding the entire file. 
Should I have one file per class? That's pretty insane.

**Comment by nkbt** [comment]
If you only use one thing from the module and that module is never used anywhere else, I'd say it is better to move that particular class to the place where it is needed and do not use `composes`.

If source file is used in other places, I can't see the problem including it.

Removing dead unused css code would solve the issue of having more styles then necessary, but it seems like out of scope for css-modules. Maybe a separate lib/loader for that?

**Comment by nkbt** [comment]
For past half a year, I've never encountered this problem. We only do `composes` within a file. And rarely from couple of shared common files (some very generic styles).

**Comment by andreypopp** [comment]
> If you only use one thing from the module and that module is never used anywhere else, I'd say it is better to move that particular class to the place where it is needed and do not use composes from another file.

Just wanted to chime in and say that this is a really good practice we adopted too. It also helps to solve indeterministic CSS rule resolution which arises from using `composes` between different modules (due to arbitrary position of different CSS modules within a bundle).

**Comment by StevenIseki** [comment]
Just on the question of importing specific elements from bootstrap. I would propose setting up an additional project for bootstrap which exports each css module and can easily be composed.

```css
.btn {
    composes: btn from 'bootstrap/buttons';
}
```

I set up a similar project for purecss over [here](https://github.com/StevenIseki/pure-css)

I am not sure if this should be rolled into the actual source for purecss as I was just experimenting at this stage. 

It works nicely with importing different modules as follows:

```js
import { buttons, grids } from 'pure-css'
```

I haven't used it with composition yet but it should work okay.

Of course doing this for bootstrap would just be a case of transpiling the less files from bootstrap 
https://github.com/twbs/bootstrap/tree/master/less into valid css and publishing them as a module on npm.

I am happy to help out if anyone thinks this is a good approach. It would be great if we could add support for css modules in the actual repos, rather than creating css module specific repos. All they need is to export the css for each module and publish it to npm.

**Comment by fabm22** [comment]
@StevenIseki 
> All they need is to export the css for each module and publish it to npm.

Is it really THAT simple ? If so, and css-modules keep appearing has a stable tech, this could easily be achieved for well known frameworks

**Comment by StevenIseki** [comment]
@fabm22 I did make a start on a css module compatible version of bootstrap [bootstrap-css](https://github.com/StevenIseki/bootstrap-css) hope it can be of help. At the moment glyphicons do not work, that seems a bit hard to do, maybe with svg-loader but not sure... otherwise it works.

**Comment by trainiac** [comment]
@geelen are there any plans to support this? If so, anything one could do to help?

**Comment by terencechow** [comment]
Can we get clarification on whats going on with this? 

This should be a major goal. CSS in JSX is cluttered. Nothing is nicer then 1 classname and a css file that just `composes`. 

It would be a big weakness if we can't use `compose` on the most common styles library ever (bootstrap).

**Comment by sheerun** [comment]
I think the best option would be to teach postcss to extract important bits from already pre-compiled bootstrap. What I mean is a function with following properties:

input 1: `bootstrap.css` precompiled with css-modules
input 2: `btn`
output: bits from `bootstrap.css` that define `btn`, so any selectors like `.btn` `.something .btn` `.something.btn` etc.

this way you don't need sass or less preprocessor in project to use css modules with bootstrap

**Comment by sheerun** [comment]
maybe dead-css-loader could help
