### ISSUE TITLE
CSS Modules BEM Demo

### ISSUE THREAD

**Issue by sgtpep** [css-modules/css-modules#91]
Hi!

In case you're interested in additional demos I'd like to suggest one: https://github.com/sgtpep/css-modules-bem-demo.

> A demo of using [CSS Modules](https://github.com/css-modules/css-modules) within HTML files following the [BEM](http://getbem.com/) approach and powered by [Gulp](https://github.com/gulpjs/gulp) and [Lo-Dash/Underscore templates](https://lodash.com/docs#template).

**Comment by StevenIseki** [comment]
Just a question, why would we be trying to use BEM with CSS Modules, isn't the whole point of CSS Modules to avoid the use of BEM with locally scoped class names in components? 

Nice work on your example though it is helpful in every other respect. Especially as a lot of the examples have been using webpack and it is good to see an example with gulp.

**Comment by sgtpep** [comment]
I was trying to actually get the attention of the wider audience of BEM users. Not only those who use it for webapps when all code could be bundled to the single js-files using webpack, but those who need to write plain HTML with BEM by hand for some kind of tasks. To eliminate the confusion with BEM I've renamed the project to css-modules-html-demo. It just shows how to use CSS Modules within almost plain HTML files and gives some hints on how to reproduce some of the BEM advantages.

**Comment by StevenIseki** [comment]
Ah cool makes sense now, thanks for the clarification, it looks good.

**Comment by dnixx** [comment]
@sgtpep, thanks for the example!

As an avid user of the BEM naming convention I find CSS modules very interesting. I'm trying to figure out how CSS modules can solve some of the problems that BEM sets out to solve.

With BEM the module structure is reflected in both the CSS and the HTML; `button--primary` belongs to the button module, and is specifically _modifying_ the base block.

However, your example uses the same naming convention for both elements and modifiers. But the CSS gives us some hints on the module's structure through the use of the `composes` keyword:

```
.element {
  color: green;
}
.modifiedElement {
  composes: element;
  border: 1px solid;
}
```

`modifiedElement` is composed by, or modifies, `element`. 

However, looking at the _markup_ it is unclear whether the selector is a modifier or an element.

````
<a class="${button.primary} ${button.large}">
````

Can `$button.primary` be used alone? In most examples `$button.primary` would use `composes: root`, so the answer would be yes. But what about `${button.large}`? If I put `composes: root` on both of them, the root class is included twice in the compiled output:

```
<button class="
  button__primary
  button__root
  button__large
  button__root">
```

In BEM you would use any number of modifiers as long as you include the base element (the "block"); `.button--primary` and `.button--large` are both dependent on `button`.

I'm not sure what the best practice is with CSS modules. Its goal may not be to satisfy every need of BEM users, but it would be great if someone could address this concern or clear up any misunderstandings :)

**Comment by sullenor** [comment]
@dnixx in my opinion if you want to stick to the BEM naming with CSS Modules you try to treat all the selectors as elements and think about proper naming on the file system.

For example, if you use `[name]--[local]` naming pattern, then you can get something similar for a simple button:

```css
/* button.css */
.control
{
  /* base styles */
}
```

```css
/* button-theme-normal.css */
.control
{
  composes: control from './button.css';
  /* base styles */
}
```

so in the resulting html you'll get smthing like that: `button--control` or `button--control button-theme-normal--control`.

**Comment by tyaremco** [comment]
> some hints on how to reproduce some of the BEM advantages

I am really struggling with your demo.  I only see disadvantages:

- There are no longer consistent identifiers ("__" "--") for distinguishing between elements and modifiers when reading/writing HTML, JS, or CSS.  
- The use of 'Compose' is syntactically very weak compared to SCSS nesting where the recognizing the "parent" of an element or modifier is obvious from their indentation level.

Can you please fill me in?  What is _gained_ here?

> Just a question, why would we be trying to use BEM with CSS Modules, isn't the whole point of CSS Modules to avoid the use of BEM with locally scoped class names in components?

This is what I understood as well, @StevenIseki.  But I still don't see how CSS Modules are an improvement.  I still should be able to _trivially_ recognize  the elements and modifiers of any component regardless of what file I'm editing.  CSS Modules don't address this at all.  They give you the automatic local scoping but without ease of use that comes directly from the BEM naming convention. 

 What am I missing that makes CSS Modules desirable?

**Comment by StevenIseki** [comment]
@tyaremco @sgtpep has put together a cool example of using BEM with css modules, however I don't know why anyone would use BEM with css modules on anything other than a legacy codebase. As I said they seem like 2 different approaches to me. css modules allows you to have scoped styles which you can easily add to components, whereas BEM solves the scoping issue in an old school way, which means you don't need a build step, however you are left with verbose class names which in my opinion ends up a bit of a mess.

I have a simple example of using css modules with react here [react-webpack-example](https://github.com/StevenIseki/react-webpack-example) I hope to update it to webpack 2very soon, it is a good starting point. Also just searched and found the official [webpack-demo](https://github.com/css-modules/webpack-demo) which should get you up and running too.

There is really no complexity in using css modules if you are using webpack which is very popular for front end development. You just add style-loader and css-loader and add them to your webpack.config and you are good to go.

Also check out [styled-components](https://github.com/styled-components/styled-components) I have been using that a lot lately, it is a great way to style react and react-native apps.

**Comment by eminx** [comment]
The whole reason they invented CSS Modules is so that you don't need to adopt a logic of such complicated naming convention such as BEM, where the whole reasoning of its existence is to ensure the selectors are unique not to break other elements' styles. Though I've worked a lot at projects where "BEM was the convention", but in truth; it's so complicated that nobody truly has written it right. It always ends up with CSSers writing their own understanding of BEM and becomes a whole mess.

Besides, BEM as convention that doesn't go well with the new great trend of *Reusable Components*. Why? It's because an element that is nested within another is supposed to be built completely independent from its parent and thus be reusable. But BEM suggests to go top-down; write the classname according to parent-to-child hierarchy and therefore is not really reusable.

Such as if you have a `card` that has` inputs` with `red` or `green` borders, you would write like this using BEM:

```
.card__input {
  // some style
}

.card__input--red {
  border-color: red;
}

.card__input--green {
  border-color: green;
}
```

What's wrong with this? It is that I can not use just the `input` styling outside of the `card`. I have to reimplement it from scratch.

Whereas in the new frontend world, you start from seeds; you start writing the smallest of the components with a style that is dedicated for it. And with CSS Modules, you don't need to give a damn about the classname of it at all. Less work, better efficiency, and ultimate reusability.

I'm totally with @StevenIseki .

**Comment by JovicaMarkoski** [comment]
@eminx I think that you are using BEM the wrong way in the example you gave. If you need to use the input styling in other parts of your app, you have to make it a `block

**Comment by cattofiq** [comment]
@svnm I read your comments and I don't agree with U. We don't use BEM for only handle Global Scope problems. Yeah I know Global Scope is worth and CSS Modules solve this problem. But in general CSS Modules don't make something great it's just hash css names for avoid conflicts. 

In BEM way we get great features like avoid Global Scope conflicts, Low CSS Specifity and meaningful class names. CSS Modules just solve Global Scope but BEM have other features I talk about above. 

And also I saw some people which use CSS Modules give some shitty and meaningless names to class. And my opinion use BEM and CSS modules is better.

I use CSS modules just for make my classnames short for production. This is make small my bundle size that's all :)
