### ISSUE TITLE
@font-face is broken

### ISSUE THREAD

**Issue by camsong** [css-modules/css-modules#95]
I'm using css-modules with webpack, but it can't find the `@font-face`

Here is the scss:
```css
@font-face {
    font-family: 'custom-icon';
    url('//font-url.svg#custom-icon') format('svg');
}
```

I tried to add `:global {}` to wrap `@font-face`, but it doesn't work neither.

webpack config is:
```js
var webpack = require('webpack');
var path = require('path');
var fs = require('fs');
var autoprefixer = require('autoprefixer');
var pkg = require('./package');

module.exports = {
  devtool: 'inline-source-map',
  entry: [
    'webpack-dev-server/client?http://localhost:3000',
    'webpack/hot/only-dev-server',
    './src/index'
  ],
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'bundle.js',
    publicPath: '/watch/'
  },
  module: {
    loaders: [
      {test: /\.js$/, loaders: ['react-hot', 'babel'], include: path.join(__dirname, 'src') },
      {test: /\.scss$/, loaders: ['style', 'css?modules&sourceMap&importLoaders=1&localIdentName=[name]__[local]!sass?sourceMap']}
    ]
  },
  postcss: function () {
    return [autoprefixer];
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin(),
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify('development'),
      VERSION: JSON.stringify(pkg.version)
    }),
  ],
  resolve: {
    extensions: ['', '.js', '.jsx', '.scss'],
    modulesDirectories: [
      'node_modules',
      path.resolve(__dirname, './node_modules')
    ]
  },
};
```

Any kinds of help is really appreciated.

**Comment by vimalceg** [comment]
Try using file loader
webpack.config.js
{ test: /\.jpe?g$|\.gif$|\.png$|\.svg$|\.woff$|\.ttf$|\.otf$|\.eot$/, loader: require.resolve("file-loader") + "?name=images/[name].[ext]"}
resolve: {
    	modulesDirectories: ['app/images','node_modules']
	}

@font-face
 {
    font-family: 'custom';
    src: url('anson-regular-webfont.ttf') format('truetype');
 }

**Comment by nkbt** [comment]
You need url-loader, not file-loader.

In terminal:

```sh
npm install -SD url-loader
```

In your `webpack.config.js`

```js
  module: {
    loaders: [
      // ...
      {test: /\.woff$/, loader: 'url?limit=10240&mimetype=application/font-woff'},
      {test: /\.ttf$/, loader: 'url?limit=10240&mimetype=application/x-font-ttf'},
      {test: /\.eot$/, loader: 'url?limit=10240&mimetype=application/vnd.ms-fontobject'}
    ]
  }
```

**Comment by camsong** [comment]
@nkbt @vimalceg the font files are stored on CDN, not local. somehow can not load them in the page

**Comment by nkbt** [comment]
@camsong Webpack works with local files only and does not support external dependencies, as far as I know.

See https://github.com/webpack/webpack/issues/150 (last comments are about fonts too, btw)

Anyway it's nothing really to do we css-modules.

**Comment by josephmcasey** [comment]
I had a similar issue when trying to add a `@font-face` inside the `:global{}` selector. The only thing that worked for me was simply adding the font-face before the `:global{}` selector. Otherwise, the font-family would not load properly.

**Comment by starandtina** [comment]
Hi, Sorry to pick up this issue. I have the same problem, I add the `@font-face` inside the `:global` selector,

Before compiling:

```
@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: url("fonts/MaterialIcons-Regular.eot");
  src: local("Material Icons"),
       local("MaterialIcons-Regular"),
       url("fonts/MaterialIcons-Regular.woff2") format('woff2'),
       url("fonts/MaterialIcons-Regular.woff") format('woff'),
       url("fonts/MaterialIcons-Regular.ttf") format('truetype');
}
```

After compiling:

```
@font-face {
  {
    font-family: Material Icons;
    font-style: normal;
    font-weight: 400;
    src: url(http://localhost:3000/src/styles/fonts/MaterialIcons-Regular.eot);
    src: local("Material Icons"),local("MaterialIcons-Regular"),url(http://localhost:3000/src/styles/fonts/MaterialIcons-Regular.woff2) format("woff2"),url(http://localhost:3000/src/styles/fonts/MaterialIcons-Regular.woff) format("woff"),url(http://localhost:3000/src/styles/fonts/MaterialIcons-Regular.ttf) format("truetype")
  }
}
```

There will be one extra brace for the `@font-face` at-rule, I think this is the root cause why it doesn't work.

Any thoughts? Thanks in advance!

**Comment by elhay-av** [comment]
@starandtina did you find a solution? i'm having the same issue now...

**Comment by starandtina** [comment]
@elhay-av , it's not solved, but I find a workaround for it. As we're using Webpack to build the whole project, so we could have some files should not be treated as CSS modules. Refer to [module.loaders.exclude](http://webpack.github.io/docs/configuration.html#module-loaders).

**Comment by elhay-av** [comment]
Thank you, this is what i did.

**Comment by dingchaoyan1983** [comment]
you need to put the `@font-face` out of `:global {}` block, more details please refer https://github.com/dingchaoyan1983/ReactRedux/blob/postcss-css-modules/src/styles/app.css#L3 for more information, this is use `postcss + css modules`, also if you are using sass the same for `sass + css modules`: https://github.com/dingchaoyan1983/ReactRedux/blob/sass%2Bcss-modules/src/styles/app.scss#L3

**Comment by gtournie** [comment]
I think we should reopen this, as it's not working as intended.
I tried to import font-awesome in my project with this code:
```
:global {
  @import '~font-awesome/scss/font-awesome.scss';
}
```
But got the same error as everybody here.
If I dont use :global, fontawesome is namespaced...

**Comment by Gopikrishna19** [comment]
I second @gtournie . I am having same issues with material-design-icons. I can't use the `@import` with this double braces and I had to download a copy of the fonts to make it work. This issue should be reopened.

**Comment by jmar777** [comment]
Just ran into this as well, while trying to import styles for `video.js`.

I'm using a custom loader to wrap the entire file in `:global {}` to prevent namespacing. The raw input to sass-loader is along the lines of:

```scss
:global {
  @font-face {
    font-family: $icon-font-family;
    src: url(...) format('woff');
  }
}
```

Coming out of the sass-loader, it becomes:

```scss
@font-face {
  :global {
    font-family: VideoJS;
    src: url(...) format('woff');
  }
}
```

...which css-modules than turns into:

```scss
@font-face {
  {  👈 🚨🚨🚨
    font-family: VideoJS;
    src: url(...) format('woff');
  }
}
```

I appreciate that `:global` isn't a meaningful switch on `@font-face` rules, but the current behavior is that invalid styles are emitted with any warning or error messages, and in this case, it happens to be a rather tricky error to track down at that.

Ideally, it would be awesome if css-modules simply treated the `:global` switch as a no-op here, but at a minimum, it feels like this should warrant some error messages, as opposed to silently emitting invalid css.

**Comment by omarzion** [comment]
I just ran into a similar thing as @jmar777 mentioned, took me about 4 hours to track down why my font wasn't being loaded.  Shouldn't the brackets be removed from :global after the transpilation?

Upon further inspection, I noticed having comments inside of `:global { /*comments*/ }` will leave the brackets as well, `{/*comments*/} I think this may be a bigger issue than just @font-face

**Comment by jmar777** [comment]
Quick update for anyone else who's running into this, I just created a custom loader that seems to suffice as a workaround for this issue:

```js
// fix-global-font-face-loader.js
const reGlobalFontFamily = /(@font-face[\s]*?{[\s]*?):global([\s]*?){([\s\S]*?)}([\s]*?})/g;

module.exports = function(source) {
  return source.replace(reGlobalFontFamily, '$1$2$3$4');
};
```

I wouldn't consider this an ideal solution (lololol _[sobbing]_), but at least in my case it seemed preferable to reworking everything else. It basically just uses a regex to identify stuff that looks like this:

```scss
@font-face {
  :gobal {
    ...
  }
}
```

...and strips out the `:global {}` wrapper. To use it, you'll want to:

1. Save this in a file somewhere (e.g., `./lib/loaders/fix-global-font-face-loader.js`).

2. Tell webpack how to find your new loader by adding this to your webpack config:

```js
resolveLoader: { // <-- top level config key
  modules: [ 'node_modules', path.join(__dirname, './path/to/lib/loaders') ]
}
```

3. Add the loader such that it runs right after your preprocessor (e.g., Sass), and before your css-loader:

```js
{
  loader: 'css-loader',
  options: { modules: true, ... }
},
{
  loader: 'fix-global-font-face-loader'
},
{
  loader: 'sass-loader',
  ...
}
```

Anyway, hope that helps!

**Comment by t47io** [comment]
@jmar777 I minor tweak to your awesome `fix-global-font-face-loader.js` to handle `sourceMap`:
```js
const reGlobalFontFamily = /(@font-face[\s]*?{[\s]*?):global([\s]*?){([\s\S]*?)}([\s]*?})/g;

export default function loader(source, sourceMap) {
  this.callback(null, source.replace(reGlobalFontFamily, '$1$2$3$4'), sourceMap);
}
```

I found this necessary when used between `resolve-url-loader` and `sass-loader`; see https://github.com/bholloway/resolve-url-loader/issues/88

**Comment by swensorm** [comment]
I would agree that this is a css-loader issue and should be re-opened.  We also ran into this (with Font Awesome 5 Pro) and didn't notice the duplicate curly braces for several hours.

Our solution was a little more hacky; import the `@font-face` files twice (because the `@font-face` and `fab`/`fal`/`far`/`fas` classes are in the same files):
```sass
:global {
  @import '~@fortawesome/fontawesome-pro/scss/fontawesome';
  @import '~@fortawesome/fontawesome-pro/scss/brands';
  @import '~@fortawesome/fontawesome-pro/scss/light';
  @import '~@fortawesome/fontawesome-pro/scss/regular';
  @import '~@fortawesome/fontawesome-pro/scss/solid';
}

@import '~@fortawesome/fontawesome-pro/scss/brands';
@import '~@fortawesome/fontawesome-pro/scss/light';
@import '~@fortawesome/fontawesome-pro/scss/regular';
@import '~@fortawesome/fontawesome-pro/scss/solid';
```
