### ISSUE TITLE
:global and :local for blocks would be better as @global and @local

### ISSUE THREAD

**Issue by pygy** [css-modules/css-modules#96]
Wouldn't they?

```
@global {
    .foo {
        color: #f00;
    }
}
```

I know it's a bit of a bikeshed, but if this were regular CSS, I believe an at-rule would be used rather than a custom, nested selector.

Edit: You could keep the `:` syntax for backwards compatibility.

`:global(.foo)` is fine, off course, I'm suggesting this for declarations that affect whole blocks.

edit2: also, it simplifies parsing a bit (not that it was hard, but still, it's someting).

**Comment by geelen** [comment]
The problem becomes when you have more complex selectors, like `:global(.something) .myComponent {}`

By using [postcss-nested](https://github.com/postcss/postcss-nested) you can do the following:

```css
:global {
  .everything, .here, .is .global {
  }
}
```

That gets compiled to `:global(.everything), :global(.here), :global(.is), :global(.global) {}` which is what you want, I think.
