### ISSUE TITLE
Global theming

### ISSUE THREAD

**Issue by aleksandrenko** [css-modules/css-modules#98]
Hello, there are a lot of ideas i like in this css-modules concept but there is 1 major thing i'm not seeing. And that thing is theming ... 
The theming in my head should have this specific ux:
- the theming should be global
- the theme should be installable - a single place/folder to be applied easy
- the controls should have no idea of the theming
- the theming have to be separate from the logic implementation

I can give a very common use-case and no possible solution with the current state of css-modules. (or at least my understanding of it):

There is a working application, the app dev need to add a calendar. He goes to a ui lib and decides to use one - UICallendar. The controls only have layout styles and some basic colors. The dev does not want to change the control styles and want to do a theming. The current way of doing it is to checkout the css and the generated html and write css styles to override some of the control's styles so the control look as part of the application theme. 

How can I as a app dev. make a theme for a ui component/control if i'm in the use-case from above?

Thanks.

**Comment by EvNaverniouk** [comment]
I'm currently in the process of migrating an internal component library to CSS Modules, and got stuck on theming for a good half-a-day. I think this is where I landed on.

First we'll define the base layout for our component (in this case a `<Button />`). The base styling should only have structural CSS.

__button.css__
```
.button {
    display: block;
    text-align: center;
    white-space: nowrap;
}
```

Next we define a theme file which will hold all the customizable styling for all my components. In this case, it's the 'dark' theme.

__dark_theme.css__
```
.button {
    background: black;
    color: white;
}
```

Now the hard part. Our components need to be smart. They need to know how to apply both the structural CSS and the theme CSS and how to merge the two. For this example, I may be something like this (note that I'm using React components here, but the concept stays true for any Javascript component):

__button.js__
```
// We load the structural styles as a CSS module
import styles from './button.css';

class Button extends Component {
    render () {
        const {className, theme} = this.props;

        const classes =  classnames(
            // Structural CSS applied first from the `button.css`
            styles.button,
            // Theme CSS applied next (if it exists)
            theme.button,
            // (Optional) Style overrides applied last
            className 
        );

        return (
            <button className={classes} />
        )
    }
}
```

And finally, in my application:

__app.js__
```
// We load our component
import Button from './button.js';

// We load our preferred theme package as a CSS module
import theme from './dark_theme.css';

// We load our application styling (which may have additional customizations for a specific area of my application)
import appStyle from './app.css';

// We render the component
render(
  <Button className={appStyle.this_specific_button} theme={theme} />  
);
```

So looking over @aleksandrenko original requirements, how did we do:

- __the theming should be global__
-- Yes. As long as all theme-able components understand the `theme` property, and know how to deal with it
- __the theme should be installable - a single place/folder to be applied easy__
-- Yes. A single `dark_theme.css` will contain all the customizations for all our components 
- __the controls should have no idea of the theming__
-- Yes. Even if component developers insert styling for `background` for the button, it will get replaced by the theme style
- __the theming have to be separate from the logic implementation__
-- Yes. But only if component developers follow the guidelines.

Thoughts?

**Comment by dvkndn** [comment]
Hey guys, I see that you are also interesting in theming subject. I recently think of a new solution which can satisfy some requirements from @aleksandrenko . I shared it in another issue: https://github.com/css-modules/css-modules/issues/160#issuecomment-239665119

**Comment by Scit** [comment]
>         const classes =  classnames(
>             // Structural CSS applied first from the `button.css`
>             styles.button,
>             // Theme CSS applied next (if it exists)
>             theme.button,
>             // (Optional) Style overrides applied last
>             className 
>         );

This class ordering makes no sense. CSS rules priority based on definition ordering in style document.
