### ISSUE TITLE
Babel 6 & much simple CSS Modules example

### ISSUE THREAD

**Issue by reactima** [css-modules/css-modules#99]
After playing with CSS Modules a month ago, I got the feeling that it would be really good to see minimum amount of dev dependency in CSS Modules world.
https://github.com/reactima/reactima-cute-css-modules-demo

Merging Webpack-demo code with my application was really time consuming. Following attempt to upgrade to Babel 6 was disaster for my weekend.
https://github.com/css-modules/webpack-demo

I got feeling that doing CSS Modules transformation through Babel 6 plugin would be much productive idea.
https://github.com/thejameskyle/babel-plugin-handbook

I'm wondering if my gut feeling is correct? 

Please kindly share your thoughts if it's worth to explore idea to get rid of PostCSS and Webpack for minimalistic example, and probably build prove-of-concept with Babel 6.

**Comment by nkbt** [comment]
I started to write a babel plugin for css modules some time  ago. It is a blocker for unit-testing react components in my projects (I use Tape, which is purely Node, no packaging/webpack involved).


Hopefully will get it done quite soon.

**Comment by joeybaker** [comment]
In the meantime, https://www.npmjs.com/package/css-modules-require-hook might suite your needs.

**Comment by nkbt** [comment]
I'm following it, but it is not something that works well in my case, unfortunately.

**Comment by sullenor** [comment]
@nkbt I wonder if you can tell a bit more about your case :)

**Comment by nkbt** [comment]
@sullenor In my case I don't care about styles at all. I also want to statically build test files with babel without having extra runtime burden. 

For the sake of unit-testing components I need to be able to include component's source so it does not fail on css file required in there. And replace it with simple (even empty) object. After all I am testing js logic, not css and usually don't care about classnames on elements.

Well, Ideally it would be nice to actually have babel transformer which would replace required css with actual css-modules object (what I am currently working on). That would cover all cases of course.

I reckon babel will replace Webpack entirely at some point. Babel's transformations is a really powerful concept.

**Comment by sullenor** [comment]
@nkbt sounds reasonable and it can bring benefit for testing and help with rendering on the server side.

I agree that babel can replace Webpack at some point, but I doubt that it can replace it thoroughly. Still, you need to generate CSS somehow.

**Comment by reactima** [comment]
things move fast ))

Extract css class names from required css module files, so we can render it on server.
https://github.com/michalkvasnicak/babel-plugin-css-modules-transform

babel 6 plugin which allows to use webpack loaders - inspiration of the above plugin
https://github.com/istarkov/babel-plugin-webpack-loaders

**Comment by nkbt** [comment]
That's awesome!

**Comment by nkbt** [comment]
I checked out https://github.com/istarkov/babel-plugin-webpack-loaders, it solves pretty much everything. Even better then just css-modules, it can handle everything else too.

I'd close this issue since it is basically solved.
